(()=>{"use strict";
const d=document,$=id=>d.getElementById(id),form=$("ltvForm");if(!form)return;
const fmt=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:0}),fmt1=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:1});
const money=v=>`${fmt.format(Number.isFinite(v)?Math.round(v):0)} Kč`,num=v=>fmt1.format(Number.isFinite(v)?v:0),clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const parse=v=>{const n=Number.parseFloat(String(v??"").replace(/[\s\u00a0]/g,"").replace(",",".").replace(/[^0-9.+-]/g,""));return Number.isFinite(n)?n:0};
const numeric=["purchasePrice","savings","protectedCash","customLtv","basicCosts","basicRepairs","cashLimit","bankValue","advancedLtv","extraCollateralValue","extraCollateralDebt","legalCosts","adminCosts","setupCosts","repairCosts","extraBuffer","advancedCashLimit"];
let mode="basic",step=0,last=null;
const read=id=>{const e=$(id);if(!e)return 0;return clamp(parse(e.value),parse(e.dataset.min??-Infinity),parse(e.dataset.max??Infinity))};
const select=(id,f)=>$(id)?.value??f;
const formatInput=id=>{const e=$(id);if(!e)return;e.value=(id.includes("Ltv")?fmt1:fmt).format(read(id))};
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
function currentLtv(){if(mode==="advanced")return read("advancedLtv");const p=select("targetProfile","80");return p==="custom"?read("customLtv"):parse(p)}
function values(){return mode==="basic"?{
 purchasePrice:read("purchasePrice"),savings:read("savings"),protectedCash:read("protectedCash"),ltv:currentLtv(),bankValue:read("purchasePrice"),extraCollateralValue:0,extraCollateralDebt:0,costs:read("basicCosts"),repairs:read("basicRepairs"),buffer:0,cashLimit:read("cashLimit"),stress:5,exception:false
}:{purchasePrice:read("purchasePrice"),savings:read("savings"),protectedCash:read("protectedCash"),ltv:currentLtv(),bankValue:read("bankValue"),extraCollateralValue:read("extraCollateralValue"),extraCollateralDebt:read("extraCollateralDebt"),costs:read("legalCosts")+read("adminCosts"),repairs:read("setupCosts")+read("repairCosts"),buffer:read("extraBuffer"),cashLimit:read("advancedCashLimit"),stress:parse(select("valuationStress","5")),exception:select("exceptionMode","no")==="yes"}}
function calc(v,override={}){const ltv=clamp(override.ltv??v.ltv,10,100),bankValue=Math.max(0,override.bankValue??v.bankValue),collateral=Math.max(0,bankValue+v.extraCollateralValue),grossLoan=collateral*ltv/100-v.extraCollateralDebt,maxMortgage=Math.max(0,Math.min(v.purchasePrice,grossLoan)),downPayment=Math.max(0,v.purchasePrice-maxMortgage),otherCash=Math.max(0,v.costs+v.repairs+v.buffer),totalCash=downPayment+otherCash,usableSavings=Math.max(0,v.savings-v.protectedCash),cashGap=usableSavings-totalCash,securedExposure=maxMortgage+Math.max(0,v.extraCollateralDebt),actualLtv=collateral>0?securedExposure/collateral*100:0,valuationGap=Math.max(0,v.purchasePrice-bankValue),coverage=totalCash>0?usableSavings/totalCash*100:100;return{...v,ltv,bankValue,collateral,maxMortgage,downPayment,otherCash,totalCash,usableSavings,cashGap,securedExposure,actualLtv,valuationGap,coverage}}
function interpretation(r){if(r.cashGap<0)return{badge:"Hotovost nestačí",title:"Nejdříve doplňte vlastní zdroje",text:`Do celkového hotovostního plánu chybí ${money(Math.abs(r.cashGap))}. Nesnižujte automaticky rezervu; nejdříve ověřte odhad, cenu a skutečné náklady koupě.`};if(r.actualLtv>90)return{badge:"Velmi vysoké LTV",title:"Model stojí na výjimce nebo další zástavě",text:"Takto vysoké LTV není standardní výchozí scénář. Ověřte konkrétní podmínky banky a měsíční rozpočet."};if(r.actualLtv>80)return{badge:"Vyšší LTV",title:"Hotovost vychází, ale úvěr je citlivější",text:`Po koupi zbývá ${money(r.cashGap)}. Vyšší LTV obvykle znamená menší počáteční hotovost, ale vyšší dluh a citlivost na sazbu.`};return{badge:"Stabilnější LTV",title:"Akontace i hotovostní plán jsou pokryté",text:`Po zaplacení akontace a zadaných nákladů zbývá ${money(r.cashGap)}. Dalším krokem je kontrola splátky a příjmové rezervy.`}}
function row(name,value,note,total=false){const el=d.createElement("div");el.className="breakdown-row"+(total?" is-total":"");const c=d.createElement("div"),s=d.createElement("strong"),sm=d.createElement("small"),b=d.createElement("b");s.textContent=name;sm.textContent=note;b.textContent=money(value);c.append(s,sm);el.append(c,b);return el}
function renderBreakdown(r){const list=$("breakdownList");if(!list)return;list.replaceChildren(row("Vlastní podíl kupní ceny",r.downPayment,`${num(100-r.ltv)} % při shodné hodnotě`,true),row("Vedlejší náklady koupě",r.costs,"právní a administrativní výdaje"),row("Vybavení a první opravy",r.repairs,"hotovost mimo kupní cenu"),row("Dodatečný bezpečnostní polštář",r.buffer,"ponechaný nad chráněnou hotovostí"),row("Celkem potřebná hotovost",r.totalCash,"akontace a všechny zadané položky",true))}
function render(){const v=values();if(v.purchasePrice<=0||v.bankValue<=0){set("formStatus","Zadejte platnou cenu a bankovní hodnotu.");return}set("formStatus","");const r=calc(v),i=interpretation(r),stressBank=v.bankValue*(1-v.stress/100),stress=calc(v,{bankValue:stressBank}),low70=calc(v,{ltv:70}),high90=calc(v,{ltv:90});last=r;
set("modeLabel",mode==="basic"?"Rychlý odhad":"Podrobná kontrola");set("totalCash",money(r.totalCash));set("resultRange",`Pracovní rozsah: ${money(r.totalCash*.97)} až ${money(Math.max(r.totalCash,stress.totalCash))}`);set("downPayment",money(r.downPayment));set("maxMortgage",money(r.maxMortgage));set("actualLtv",`${num(r.actualLtv)} %`);set("cashGap",`${r.cashGap>=0?"Zbývá ":"Chybí "}${money(Math.abs(r.cashGap))}`);set("valuationGap",money(r.valuationGap));set("statusBadge",i.badge);set("decisionTitle",i.title);set("decisionText",i.text);set("scenario70",money(low70.downPayment));set("scenarioCurrent",money(r.downPayment));set("scenario90",money(high90.downPayment));set("stressText",`Při odhadu nižším o ${num(v.stress)} % by potřebná hotovost byla ${money(stress.totalCash)}, tedy o ${money(Math.max(0,stress.totalCash-r.totalCash))} více.`);set("contentLtv",`${num(r.actualLtv)} %`);
const check=$("cashCheck");check?.classList.remove("is-positive","is-warning","is-negative");if(r.cashGap>=Math.max(100000,r.totalCash*.08)){check?.classList.add("is-positive");set("cashCheckTitle",`Po koupi zbývá ${money(r.cashGap)}`);set("cashCheckText","Použitelné úspory pokrývají akontaci i zadané náklady a zůstává další polštář.")}else if(r.cashGap>=0){check?.classList.add("is-warning");set("cashCheckTitle",`Zbývá jen ${money(r.cashGap)}`);set("cashCheckText","Plán se vejde do úspor, ale další rezerva je malá. Ověřte opravy, vybavení a termíny plateb.")}else{check?.classList.add("is-negative");set("cashCheckTitle",`Chybí ${money(Math.abs(r.cashGap))}`);set("cashCheckText","Testujte nižší kupní cenu, vyšší úspory nebo schválenou další zástavu. Nezakrývejte mezeru vyčerpáním rezervy.")}
set("heroNeeded",money(r.totalCash));set("heroMortgage",money(r.maxMortgage));set("heroAfter",`${num(r.actualLtv)} %`);set("heroStatus",r.cashGap>=0?`Úspory pokrývají plán, zbývá ${money(r.cashGap)}.`:`Do plánu chybí ${money(Math.abs(r.cashGap))}.`);const bar=$("heroBar");if(bar)bar.style.width=`${clamp(r.coverage,0,100)}%`;renderBreakdown(r);return r}
function setMode(m,renderNow=true){mode=m==="advanced"?"advanced":"basic";d.querySelectorAll(".mode-btn").forEach(b=>{const a=b.dataset.mode===mode;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",String(a))});if($("advancedPanel"))$("advancedPanel").hidden=mode!=="advanced";if(renderNow)render()}
function setStep(n){const stages=[...d.querySelectorAll("[data-stage]")],buttons=[...d.querySelectorAll("[data-step]")];step=clamp(Number(n)||0,0,stages.length-1);stages.forEach((s,i)=>s.hidden=i!==step);buttons.forEach((b,i)=>b.classList.toggle("is-active",i===step));set("stepStatus",`Krok ${step+1} ze ${stages.length}`);if($("prevStep"))$("prevStep").disabled=step===0;if($("nextStep")){const end=step===stages.length-1;$("nextStep").disabled=end;$("nextStep").textContent=end?"Všechny kroky hotové":"Další krok →"}}
function applyPreset(p){if(p==="own"){$("targetProfile").value="80";$('advancedLtv').value="80"}else if(p==="young"){$("targetProfile").value="90";$('advancedLtv').value="90"}else{$("targetProfile").value="70";$('advancedLtv').value="70"}render()}
function reset(){form.reset();numeric.forEach(formatInput);setMode("basic",false);setStep(0);$("breakdownWrap")?.classList.add("is-collapsed");$("toggleBreakdown")?.setAttribute("aria-expanded","false");set("toggleBreakdown","Zobrazit rozpad");render()}
function shareUrl(){const u=new URL(location.href);u.search="";const map={purchasePrice:"cena",savings:"uspory",protectedCash:"chraneno",targetProfile:"profil",customLtv:"ltv",basicCosts:"naklady",basicRepairs:"opravy",bankValue:"odhad",advancedLtv:"proLtv",extraCollateralValue:"dalsiZastava",extraCollateralDebt:"dluhZastava",legalCosts:"pravni",adminCosts:"admin",setupCosts:"vybaveni",repairCosts:"opravyPro",valuationStress:"stres",extraBuffer:"polstar",advancedCashLimit:"limit"};Object.entries(map).forEach(([id,key])=>{const e=$(id);if(e)u.searchParams.set(key,e.tagName==="SELECT"?e.value:String(read(id)))});u.searchParams.set("rezim",mode);return u.toString()}
function loadUrl(){const p=new URLSearchParams(location.search),map={purchasePrice:"cena",savings:"uspory",protectedCash:"chraneno",targetProfile:"profil",customLtv:"ltv",basicCosts:"naklady",basicRepairs:"opravy",bankValue:"odhad",advancedLtv:"proLtv",extraCollateralValue:"dalsiZastava",extraCollateralDebt:"dluhZastava",legalCosts:"pravni",adminCosts:"admin",setupCosts:"vybaveni",repairCosts:"opravyPro",valuationStress:"stres",extraBuffer:"polstar",advancedCashLimit:"limit"};Object.entries(map).forEach(([id,key])=>{if(!p.has(key)||!$(id))return;const e=$(id),v=p.get(key);if(e.tagName==="SELECT"){if([...e.options].some(o=>o.value===v))e.value=v}else{e.value=v;formatInput(id)}});setMode(p.get("rezim")==="advanced"?"advanced":"basic",false)}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);set("copyStatus",msg)}catch{set("copyStatus","Kopírování se nepodařilo. Použijte adresní řádek prohlížeče.")}}
form.addEventListener("submit",e=>{e.preventDefault();render()});numeric.forEach(id=>{const e=$(id);if(!e)return;e.addEventListener("input",render);e.addEventListener("blur",()=>{formatInput(id);render()})});d.querySelectorAll("select").forEach(e=>e.addEventListener("change",render));d.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));d.querySelectorAll("[data-step]").forEach(b=>b.addEventListener("click",()=>setStep(b.dataset.step)));d.querySelectorAll("[data-preset]").forEach(b=>b.addEventListener("click",()=>applyPreset(b.dataset.preset)));$("prevStep")?.addEventListener("click",()=>setStep(step-1));$("nextStep")?.addEventListener("click",()=>setStep(step+1));$("resetBtn")?.addEventListener("click",reset);$("toggleBreakdown")?.addEventListener("click",e=>{const w=$("breakdownWrap"),c=w.classList.toggle("is-collapsed");e.currentTarget.setAttribute("aria-expanded",String(!c));e.currentTarget.textContent=c?"Zobrazit rozpad":"Skrýt rozpad"});$("copyResult")?.addEventListener("click",()=>last&&copy(`Akontace a LTV – RychléVýpočty.cz\nPotřebná hotovost: ${money(last.totalCash)}\nAkontace: ${money(last.downPayment)}\nMaximální hypotéka: ${money(last.maxMortgage)}\nSkutečné LTV: ${num(last.actualLtv)} %\n${last.cashGap>=0?"Zbývá":"Chybí"}: ${money(Math.abs(last.cashGap))}`,"Výsledek byl zkopírován."));$("copyLink")?.addEventListener("click",()=>copy(shareUrl(),"Odkaz s nastavením byl zkopírován."));
loadUrl();numeric.forEach(formatInput);setStep(0);render();
})();
