(()=>{"use strict";
const d=document,$=id=>d.getElementById(id),form=$("ltvForm");if(!form)return;
const fmt=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:0}),fmt1=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:1});
const money=v=>`${fmt.format(Number.isFinite(v)?Math.round(v):0)} Kč`,num=v=>fmt1.format(Number.isFinite(v)?v:0),clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const parse=v=>{const n=Number.parseFloat(String(v??"").replace(/[\s\u00a0]/g,"").replace(",",".").replace(/[^0-9.+-]/g,""));return Number.isFinite(n)?n:0};
const numeric=["purchasePrice","savings","protectedCash","customLtv","basicCosts","basicRepairs","cashLimit","bankValue","advancedLtv","extraCollateralValue","extraCollateralDebt","legalCosts","adminCosts","setupCosts","repairCosts","extraBuffer","advancedCashLimit"];
let mode="basic",step=0,last=null,advancedTouched=false;
const advancedNumeric=new Set(["bankValue","advancedLtv","extraCollateralValue","extraCollateralDebt","legalCosts","adminCosts","setupCosts","repairCosts","extraBuffer","advancedCashLimit"]);
const read=id=>{const e=$(id);if(!e)return 0;return clamp(parse(e.value),parse(e.dataset.min??-Infinity),parse(e.dataset.max??Infinity))};
const select=(id,f)=>$(id)?.value??f;
const formatInput=id=>{const e=$(id);if(!e)return;e.value=(id.includes("Ltv")?fmt1:fmt).format(read(id))};
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
function basicLtv(){const p=select("targetProfile","80");return p==="custom"?read("customLtv"):parse(p)}
function currentLtv(){return mode==="advanced"?read("advancedLtv"):basicLtv()}
function values(){return mode==="basic"?{
 purchasePrice:read("purchasePrice"),savings:read("savings"),protectedCash:read("protectedCash"),ltv:currentLtv(),bankValue:read("purchasePrice"),extraCollateralValue:0,extraCollateralDebt:0,costs:read("basicCosts"),repairs:read("basicRepairs"),buffer:0,cashLimit:read("cashLimit"),stress:5
}:{purchasePrice:read("purchasePrice"),savings:read("savings"),protectedCash:read("protectedCash"),ltv:currentLtv(),bankValue:read("bankValue"),extraCollateralValue:read("extraCollateralValue"),extraCollateralDebt:read("extraCollateralDebt"),costs:read("legalCosts")+read("adminCosts"),repairs:read("setupCosts")+read("repairCosts"),buffer:read("extraBuffer"),cashLimit:read("advancedCashLimit"),stress:parse(select("valuationStress","5"))}}
function calc(v,override={}){const ltv=clamp(override.ltv??v.ltv,10,100),bankValue=Math.max(0,override.bankValue??v.bankValue),collateral=Math.max(0,bankValue+v.extraCollateralValue),grossLoan=collateral*ltv/100-v.extraCollateralDebt,maxMortgage=Math.max(0,Math.min(v.purchasePrice,grossLoan)),downPayment=Math.max(0,v.purchasePrice-maxMortgage),otherCash=Math.max(0,v.costs+v.repairs+v.buffer),totalCash=downPayment+otherCash,usableSavings=Math.max(0,v.savings-v.protectedCash),cashGap=usableSavings-totalCash,securedExposure=maxMortgage+Math.max(0,v.extraCollateralDebt),actualLtv=collateral>0?maxMortgage/collateral*100:0,combinedLoad=collateral>0?securedExposure/collateral*100:0,valuationGap=Math.max(0,v.purchasePrice-bankValue),coverage=totalCash>0?usableSavings/totalCash*100:100;return{...v,ltv,bankValue,collateral,maxMortgage,downPayment,otherCash,totalCash,usableSavings,cashGap,securedExposure,actualLtv,combinedLoad,valuationGap,coverage}}
function interpretation(r){if(r.cashLimit>0&&r.totalCash>r.cashLimit)return{badge:"Nad vaším limitem",title:"Hotovostní plán překračuje váš strop",text:`Potřebná hotovost je o ${money(r.totalCash-r.cashLimit)} vyšší než vámi zadaný limit. Nejdříve ověřte kupní cenu, bankovní odhad a položky mimo akontaci.`};if(r.cashGap<0)return{badge:"Hotovost nestačí",title:"Nejdříve doplňte vlastní zdroje",text:`Do celkového hotovostního plánu chybí ${money(Math.abs(r.cashGap))}. Nesnižujte automaticky rezervu; nejdříve ověřte odhad, cenu a skutečné náklady koupě.`};if(r.combinedLoad>90)return{badge:"Velmi vysoké LTV",title:"Model vyžaduje nestandardní financování",text:"Takto vysoké LTV není standardní výchozí scénář. Ověřte konkrétní podmínky banky, hodnotu zajištění a měsíční rozpočet."};if(r.combinedLoad>80)return{badge:"Vyšší LTV",title:"Hotovost vychází, ale úvěr je citlivější",text:`Po koupi zbývá ${money(r.cashGap)}. Vyšší LTV obvykle znamená menší počáteční hotovost, ale vyšší dluh a citlivost na sazbu.`};return{badge:"Nižší LTV",title:"Akontace i hotovostní plán jsou pokryté",text:`Po zaplacení akontace a zadaných nákladů zbývá ${money(r.cashGap)}. Dalším krokem je kontrola splátky a příjmové rezervy.`}}
function row(name,value,note,total=false){const el=d.createElement("div");el.className="breakdown-row"+(total?" is-total":"");const c=d.createElement("div"),s=d.createElement("strong"),sm=d.createElement("small"),b=d.createElement("b");s.textContent=name;sm.textContent=note;b.textContent=money(value);c.append(s,sm);el.append(c,b);return el}
function renderBreakdown(r){const list=$("breakdownList");if(!list)return;list.replaceChildren(row("Vlastní podíl kupní ceny",r.downPayment,"kupní cena − modelový úvěr",true),row("Vedlejší náklady koupě",r.costs,"právní a administrativní výdaje"),row("Vybavení a první opravy",r.repairs,"hotovost mimo kupní cenu"),row("Dodatečný bezpečnostní polštář",r.buffer,"ponechaný nad chráněnou hotovostí"),row("Celkem potřebná hotovost",r.totalCash,"akontace a všechny zadané položky",true))}
function render(){const v=values();if(v.purchasePrice<=0||v.bankValue<=0){set("formStatus","Zadejte platnou cenu a bankovní hodnotu.");return}set("formStatus","");const r=calc(v),i=interpretation(r),stressBank=v.bankValue*(1-v.stress/100),stress=calc(v,{bankValue:stressBank}),low70=calc(v,{ltv:70}),high90=calc(v,{ltv:90});last=r;
set("modeLabel",mode==="basic"?"Rychlý odhad":"Podrobná kontrola");set("totalCash",money(r.totalCash));set("resultRange",`Akontace ${money(r.downPayment)} + zadané náklady ${money(r.otherCash)}`);set("downPayment",money(r.downPayment));set("maxMortgage",money(r.maxMortgage));set("actualLtv",`${num(r.actualLtv)} %`);set("cashGap",`${r.cashGap>=0?"Zbývá ":"Chybí "}${money(Math.abs(r.cashGap))}`);set("valuationGap",money(r.valuationGap));set("statusBadge",i.badge);set("decisionTitle",i.title);set("decisionText",i.text);set("scenario70",money(low70.downPayment));set("scenarioCurrent",money(r.downPayment));set("scenario90",money(high90.downPayment));set("stressText",mode==="advanced"?(v.stress>0?`Vámi zvolený stres: pokud bankovní odhad klesne o ${num(v.stress)} %, potřebná hotovost vzroste na ${money(stress.totalCash)}, tedy o ${money(Math.max(0,stress.totalCash-r.totalCash))}.`:`Stresový pokles zatím není nastaven. V kroku 3 můžete otestovat odhad nižší o 3, 5 nebo 10 %.`):`Modelový příklad −5 % odhadu: potřebná hotovost by vzrostla na ${money(stress.totalCash)}, tedy o ${money(Math.max(0,stress.totalCash-r.totalCash))}. Vlastní stres nastavíte v podrobném režimu.`);set("contentLtv",`${num(r.actualLtv)} %`);
const check=$("cashCheck");check?.classList.remove("is-positive","is-warning","is-negative");if(r.cashGap>=Math.max(100000,r.totalCash*.08)){check?.classList.add("is-positive");set("cashCheckTitle",`Po koupi zbývá ${money(r.cashGap)}`);set("cashCheckText","Použitelné úspory pokrývají akontaci i zadané náklady a zůstává další polštář.")}else if(r.cashGap>=0){check?.classList.add("is-warning");set("cashCheckTitle",`Zbývá jen ${money(r.cashGap)}`);set("cashCheckText","Plán se vejde do úspor, ale další rezerva je malá. Ověřte opravy, vybavení a termíny plateb.")}else{check?.classList.add("is-negative");set("cashCheckTitle",`Chybí ${money(Math.abs(r.cashGap))}`);set("cashCheckText","Testujte nižší kupní cenu, vyšší úspory nebo schválenou další zástavu. Nezakrývejte mezeru vyčerpáním rezervy.")}
const purchaseLoanPct=r.purchasePrice>0?clamp(r.maxMortgage/r.purchasePrice*100,0,100):0,ownPurchasePct=100-purchaseLoanPct;set("heroNeeded",money(r.downPayment));set("heroMortgage",money(r.maxMortgage));set("heroAfter",`${num(r.actualLtv)} % LTV`);set("blueprintPrice",money(r.purchasePrice));set("blueprintValue",money(r.bankValue));set("blueprintBankPct",`${num(purchaseLoanPct)} % kupní ceny`);set("blueprintOwnPct",`${num(ownPurchasePct)} % kupní ceny`);set("resultBankPct",`${num(purchaseLoanPct)} %`);set("resultOwnPct",`${num(ownPurchasePct)} %`);set("heroStatus",r.cashGap>=0?`Celkem potřebujete ${money(r.totalCash)}; po koupi zbývá ${money(r.cashGap)}.`:`Celkem potřebujete ${money(r.totalCash)}; do plánu chybí ${money(Math.abs(r.cashGap))}.`);const bar=$("heroBar");if(bar)bar.style.width=`${clamp(r.coverage,0,100)}%`;const bank=$("blueprintBank"),own=$("blueprintOwn"),resultSplit=$("vysledek")?.querySelector(".result-funding-split");if(bank)bank.style.flexGrow=String(Math.max(1,purchaseLoanPct));if(own)own.style.flexGrow=String(Math.max(1,ownPurchasePct));if(resultSplit)resultSplit.style.gridTemplateColumns=`minmax(0,${Math.max(1,purchaseLoanPct)}fr) minmax(0,${Math.max(1,ownPurchasePct)}fr)`;renderBreakdown(r);return r}
function seedAdvancedFromBasic(){if(advancedTouched)return;const price=read("purchasePrice"),ltv=basicLtv();if($("bankValue"))$("bankValue").value=fmt.format(price);if($("advancedLtv"))$("advancedLtv").value=fmt1.format(ltv)}
function setMode(m,renderNow=true){const nextMode=m==="advanced"?"advanced":"basic";if(nextMode==="advanced"&&mode!=="advanced")seedAdvancedFromBasic();mode=nextMode;d.querySelectorAll(".mode-btn").forEach(b=>{const a=b.dataset.mode===mode;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",String(a))});if($("advancedPanel"))$("advancedPanel").hidden=mode!=="advanced";if(renderNow)render()}
function setStep(n,focusTab=false){const stages=[...d.querySelectorAll("[data-stage]")],buttons=[...d.querySelectorAll("[data-step]")];step=clamp(Number(n)||0,0,stages.length-1);stages.forEach((s,i)=>s.hidden=i!==step);buttons.forEach((b,i)=>{const active=i===step;b.classList.toggle("is-active",active);b.setAttribute("aria-selected",String(active));b.tabIndex=active?0:-1});set("stepStatus",`Krok ${step+1} ze ${stages.length}`);if($("prevStep"))$("prevStep").disabled=step===0;if($("nextStep")){const end=step===stages.length-1;$("nextStep").disabled=end;$("nextStep").textContent=end?"Všechny kroky hotové":"Další krok →"}if(focusTab)buttons[step]?.focus()}
function applyPreset(p){if(p==="own"){$("targetProfile").value="80";$('advancedLtv').value="80"}else if(p==="young"){$("targetProfile").value="90";$('advancedLtv').value="90"}else{$("targetProfile").value="70";$('advancedLtv').value="70"}render()}
function reset(){form.reset();advancedTouched=false;numeric.forEach(formatInput);setMode("basic",false);setStep(0);$("breakdownWrap")?.classList.add("is-collapsed");$("toggleBreakdown")?.setAttribute("aria-expanded","false");set("toggleBreakdown","Zobrazit rozpad");render()}
function shareUrl(){const u=new URL(location.href);u.search="";const map={purchasePrice:"cena",savings:"uspory",protectedCash:"chraneno",targetProfile:"profil",customLtv:"ltv",basicCosts:"naklady",basicRepairs:"opravy",bankValue:"odhad",advancedLtv:"proLtv",extraCollateralValue:"dalsiZastava",extraCollateralDebt:"dluhZastava",legalCosts:"pravni",adminCosts:"admin",setupCosts:"vybaveni",repairCosts:"opravyPro",valuationStress:"stres",extraBuffer:"polstar",advancedCashLimit:"limit"};Object.entries(map).forEach(([id,key])=>{const e=$(id);if(e)u.searchParams.set(key,e.tagName==="SELECT"?e.value:String(read(id)))});u.searchParams.set("rezim",mode);return u.toString()}
function loadUrl(){const p=new URLSearchParams(location.search),map={purchasePrice:"cena",savings:"uspory",protectedCash:"chraneno",targetProfile:"profil",customLtv:"ltv",basicCosts:"naklady",basicRepairs:"opravy",bankValue:"odhad",advancedLtv:"proLtv",extraCollateralValue:"dalsiZastava",extraCollateralDebt:"dluhZastava",legalCosts:"pravni",adminCosts:"admin",setupCosts:"vybaveni",repairCosts:"opravyPro",valuationStress:"stres",extraBuffer:"polstar",advancedCashLimit:"limit"};Object.entries(map).forEach(([id,key])=>{if(!p.has(key)||!$(id))return;const e=$(id),v=p.get(key);if(e.tagName==="SELECT"){if([...e.options].some(o=>o.value===v))e.value=v}else{e.value=v;formatInput(id)}});advancedTouched=["odhad","proLtv","dalsiZastava","dluhZastava","pravni","admin","vybaveni","opravyPro","stres","polstar","limit"].some(k=>p.has(k));setMode(p.get("rezim")==="advanced"?"advanced":"basic",false)}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);set("copyStatus",msg)}catch{set("copyStatus","Kopírování se nepodařilo. Použijte adresní řádek prohlížeče.")}}
form.addEventListener("submit",e=>{e.preventDefault();render()});numeric.forEach(id=>{const e=$(id);if(!e)return;e.addEventListener("input",()=>{if(advancedNumeric.has(id))advancedTouched=true;render()});e.addEventListener("blur",()=>{formatInput(id);render()})});d.querySelectorAll("select").forEach(e=>e.addEventListener("change",()=>{if(e.id==="valuationStress")advancedTouched=true;if(e.id==="targetProfile"&&e.value==="custom"){const details=$("basicOptional");if(details)details.open=true;setTimeout(()=>$("customLtv")?.focus(),0)}render()}));d.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));d.querySelectorAll("[data-step]").forEach((b,idx,buttons)=>{b.addEventListener("click",()=>setStep(b.dataset.step));b.addEventListener("keydown",e=>{let next=null;if(e.key==="ArrowRight"||e.key==="ArrowDown")next=(idx+1)%buttons.length;else if(e.key==="ArrowLeft"||e.key==="ArrowUp")next=(idx-1+buttons.length)%buttons.length;else if(e.key==="Home")next=0;else if(e.key==="End")next=buttons.length-1;if(next!==null){e.preventDefault();setStep(next,true)}})});d.querySelectorAll("[data-preset]").forEach(b=>b.addEventListener("click",()=>applyPreset(b.dataset.preset)));$("prevStep")?.addEventListener("click",()=>setStep(step-1));$("nextStep")?.addEventListener("click",()=>setStep(step+1));$("resetBtn")?.addEventListener("click",reset);$("toggleBreakdown")?.addEventListener("click",e=>{const w=$("breakdownWrap"),c=w.classList.toggle("is-collapsed");e.currentTarget.setAttribute("aria-expanded",String(!c));e.currentTarget.textContent=c?"Zobrazit rozpad":"Skrýt rozpad"});$("copyResult")?.addEventListener("click",()=>last&&copy(`Akontace a LTV – RychléVýpočty.cz\nPotřebná hotovost: ${money(last.totalCash)}\nAkontace: ${money(last.downPayment)}\nMaximální hypotéka: ${money(last.maxMortgage)}\nLTV nového úvěru: ${num(last.actualLtv)} %\n${last.cashGap>=0?"Zbývá":"Chybí"}: ${money(Math.abs(last.cashGap))}`,"Výsledek byl zkopírován."));$("copyLink")?.addEventListener("click",()=>copy(shareUrl(),"Odkaz s nastavením byl zkopírován."));
loadUrl();numeric.forEach(formatInput);setStep(0);render();
})();
