(function(){
  const form=document.getElementById('vatForm');if(!form)return;
  const resetBtn=document.getElementById('resetBtn');
  const presetButtons=Array.from(document.querySelectorAll('.scenario-chip'));
  const $=id=>document.getElementById(id);
  const outputs={withoutDPH:$('withoutDPH'),dph:$('dph'),withDPH:$('withDPH'),summaryAmount:$('summaryAmount'),summaryMode:$('summaryMode'),summaryRate:$('summaryRate'),summaryShare:$('summaryShare'),statusBadge:$('statusBadge'),decisionStatus:$('decisionStatus'),decisionSummary:$('decisionSummary'),actionStatus:$('actionStatus'),actionSummary:$('actionSummary'),nextActionText:$('nextActionText'),primaryNextCta:$('primaryNextCta'),secondaryNextCta:$('secondaryNextCta'),heroTaxRate:$('heroTaxRate'),heroWith:$('heroWith'),heroWithout:$('heroWithout'),heroTax:$('heroTax'),heroModePill:$('heroModePill'),barWithout:$('barWithout'),barTax:$('barTax')};
  function formatCurrency(value){return new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}
  function formatPercent(value,digits=2){return new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:0,maximumFractionDigits:digits}).format(value)+' %'}
  function getValues(){return{amount:Number($('amount').value),rate:Number($('rate').value),mode:$('mode').value}}
  function validate(values){if(Number.isNaN(values.amount)||values.amount<0)return'Zadejte platnou částku.';if(!values.rate||values.rate<=0)return'Zvolte platnou sazbu DPH.';if(!['with','without'].includes(values.mode))return'Zvolte platný typ výpočtu.';return''}
  function calculateVAT(values){let withoutDPH=0,withDPH=0,dph=0;if(values.mode==='with'){withDPH=values.amount;withoutDPH=values.amount/(1+values.rate/100);dph=withDPH-withoutDPH}else{withoutDPH=values.amount;dph=values.amount*(values.rate/100);withDPH=withoutDPH+dph}const shareOfGross=withDPH>0?(dph/withDPH)*100:0;return{withoutDPH,withDPH,dph,shareOfGross}}
  function updateDecision(values,result){const isWith=values.mode==='with';outputs.statusBadge.className=isWith?'badge success':'badge warning';outputs.statusBadge.textContent=isWith?'Zadaná částka je cena s DPH':'Zadaná částka je cena bez DPH';outputs.decisionStatus.className=isWith?'decision-status safe':'decision-status caution';outputs.decisionStatus.textContent=isWith?'Cena s DPH':'Cena bez DPH';outputs.decisionSummary.textContent=isWith?'Právě dopočítáváte základ daně z částky, která už DPH obsahuje. To se hodí při kontrole faktury, účtenky nebo cenové nabídky.':'Právě dopočítáváte finální cenu s DPH ze základu daně. To se hodí při tvorbě nabídky, kalkulaci ceny nebo kontrole fakturace.';outputs.actionStatus.className=isWith?'decision-status safe':'decision-status caution';outputs.actionStatus.textContent='Další krok';outputs.actionSummary.textContent=isWith?'Ze zadané částky '+formatCurrency(values.amount)+' při sazbě '+formatPercent(values.rate,0)+' vychází základ daně '+formatCurrency(result.withoutDPH)+' a samotná DPH '+formatCurrency(result.dph)+'.':'Ze základu '+formatCurrency(values.amount)+' při sazbě '+formatPercent(values.rate,0)+' vychází DPH '+formatCurrency(result.dph)+' a výsledná cena s DPH '+formatCurrency(result.withDPH)+'.';outputs.nextActionText.textContent=isWith?'Po výpočtu si ověřte, že vstupní částka opravdu byla konečná cena včetně DPH. Pak teprve řešte slevu, marži nebo další cenový krok.':'Po výpočtu si ověřte, že řešíte správnou sazbu a že opravdu vycházíte ze základu bez DPH.';outputs.primaryNextCta.href='/procenta-kalkulacka.html';outputs.primaryNextCta.textContent='Pokračovat na procenta';outputs.secondaryNextCta.href='/business-a-cenotvorba.html';outputs.secondaryNextCta.textContent='Business a cenotvorba';outputs.heroModePill.textContent=isWith?'Cena s DPH rozpočítaná na základ a daň':'Základ navýšený o zvolenou sazbu DPH'}
  function render(values,result){outputs.withoutDPH.textContent=formatCurrency(result.withoutDPH);outputs.dph.textContent=formatCurrency(result.dph);outputs.withDPH.textContent=formatCurrency(result.withDPH);outputs.summaryAmount.textContent=formatCurrency(values.amount);outputs.summaryMode.textContent=values.mode==='with'?'Zadaná částka je cena s DPH':'Zadaná částka je cena bez DPH';outputs.summaryRate.textContent=formatPercent(values.rate,0);outputs.summaryShare.textContent=formatPercent(result.shareOfGross);outputs.heroTaxRate.textContent=formatPercent(values.rate,0)+' DPH';outputs.heroWith.textContent=formatCurrency(result.withDPH);outputs.heroWithout.textContent=formatCurrency(result.withoutDPH);outputs.heroTax.textContent=formatCurrency(result.dph);const withoutShare=result.withDPH>0?Math.max(8,Math.min(100,result.withoutDPH/result.withDPH*100)):0;const taxShare=result.withDPH>0?Math.max(8,Math.min(100,result.dph/result.withDPH*100)):0;outputs.barWithout.style.width=withoutShare+'%';outputs.barTax.style.width=taxShare+'%';updateDecision(values,result)}
  function renderError(message){outputs.withoutDPH.textContent='0 Kč';outputs.dph.textContent='0 Kč';outputs.withDPH.textContent='0 Kč';outputs.summaryAmount.textContent='-';outputs.summaryMode.textContent='-';outputs.summaryRate.textContent='-';outputs.summaryShare.textContent='-';outputs.statusBadge.className='badge warning';outputs.statusBadge.textContent='Chybí vstupní data';outputs.decisionStatus.className='decision-status caution';outputs.decisionStatus.textContent='Zkontrolujte vstup';outputs.decisionSummary.textContent=message;outputs.actionSummary.textContent='Po opravě vstupu kalkulačka hned dopočítá základ daně, DPH i finální cenu.'}
  function runCalculation(){const values=getValues();const error=validate(values);if(error){renderError(error);return}render(values,calculateVAT(values))}
  function setPreset(name){const presets={with21:{amount:1000,mode:'with',rate:'21'},without21:{amount:1000,mode:'without',rate:'21'},with15:{amount:1150,mode:'with',rate:'15'},with12:{amount:1120,mode:'with',rate:'12'}};const preset=presets[name];if(!preset)return;$('amount').value=preset.amount;$('mode').value=preset.mode;$('rate').value=preset.rate;presetButtons.forEach(btn=>{const active=btn.dataset.preset===name;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active?'true':'false')});runCalculation()}
  form.addEventListener('submit',e=>{e.preventDefault();runCalculation()});['amount','mode','rate'].forEach(id=>{$(id).addEventListener('input',runCalculation);$(id).addEventListener('change',runCalculation)});presetButtons.forEach(btn=>btn.addEventListener('click',()=>setPreset(btn.dataset.preset)));resetBtn.addEventListener('click',()=>setPreset('with21'));runCalculation();
})();
