(function(){
'use strict';
const form=document.getElementById('calorieForm'); if(!form)return;
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const nf=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:0});
const adjustments={lose:{gentle:-300,standard:-500,strong:-700},gain:{gentle:200,standard:350,strong:500},maintain:{gentle:0,standard:0,strong:0}};
const activityNames={'1.4':'převážně sedavý','1.6':'běžně aktivní','1.8':'hodně aktivní','2':'velmi aktivní'};
let lastResult=null;
const num=id=>Number(String(qs('#'+id).value).replace(',','.').replace(/\s/g,''));
const picked=name=>{const e=qs('input[name="'+name+'"]:checked',form);return e?e.value:''};
const fmt=v=>nf.format(Math.round(v)); const round10=v=>Math.round(v/10)*10;
function validate(){const a=num('age'),h=num('height'),w=num('weight'); if(!Number.isFinite(a)||a<18||a>79)return'Zadejte věk od 18 do 79 let.'; if(!Number.isFinite(h)||h<130||h>230)return'Zadejte výšku od 130 do 230 cm.'; if(!Number.isFinite(w)||w<35||w>300)return'Zadejte hmotnost od 35 do 300 kg.'; return''}
function setText(id,val){const e=qs('#'+id); if(e)e.textContent=val}
function updateGoalUi(){const goal=picked('goal')||'maintain'; const pf=qs('#paceField'); pf.hidden=goal==='maintain'; if(goal==='lose'){setText('paceGentle','−300 kcal');setText('paceStandard','−500 kcal');setText('paceStrong','−700 kcal')}else if(goal==='gain'){setText('paceGentle','+200 kcal');setText('paceStandard','+350 kcal');setText('paceStrong','+500 kcal')} setText('paceHelp',goal==='maintain'?'Pro udržování se žádná energie nepřičítá ani neodečítá.':'Jde o transparentní matematický scénář proti TDEE, ne o individuální léčebné doporučení.')}
function calculate(announce){const err=validate(),box=qs('#formError'); if(err){if(announce){box.textContent=err;box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'center'})}return} box.hidden=true;box.textContent=''; const age=num('age'),height=num('height'),weight=num('weight'),sex=picked('sex'),pal=Number(picked('activity')); if(!sex||!pal)return; const bmr=10*weight+6.25*height-5*age+(sex==='male'?5:-161); const tdee=bmr*pal; const bmi=weight/Math.pow(height/100,2); const goalPanelOpen=!qs('#goalPanel').hidden; const goal=goalPanelOpen?(picked('goal')||'maintain'):'maintain'; const pace=picked('pace')||'gentle'; let adjustment=adjustments[goal][pace]; const blockedLowBmi=goal==='lose'&&bmi<18.5; const tooLow=goal==='lose'&&(tdee+adjustment)<1200; const blocked=blockedLowBmi||tooLow; if(blocked)adjustment=0; const target=blocked?tdee:tdee+adjustment; const rangeLo=round10(tdee*.9), rangeHi=round10(tdee*1.1); const bmrPct=Math.round(bmr/tdee*100), actPct=100-bmrPct;
let status='Udržování',label='Udržovací příjem',insight='Berete-li '+fmt(round10(tdee))+' kcal jako start, ověřujte ho podle trendu několika týdnů. Jeden den ani jedno vážení nestačí.'; if(goal==='lose'&&!blocked){status='Model snižování';label='Modelový cílový příjem';insight='Scénář odečítá '+fmt(Math.abs(adjustments.lose[pace]))+' kcal od TDEE. Výsledek je modelový start, ne garantované tempo změny hmotnosti.'} if(goal==='gain'&&!blocked){status='Model zvyšování';label='Modelový cílový příjem';insight='Scénář přidává '+fmt(adjustments.gain[pace])+' kcal k TDEE. Kalkulačka neumí předpovědět poměr svalové a tukové hmoty.'} if(blocked){status='Scénář zastaven';label='Udržovací orientace';insight=blockedLowBmi?'Při vypočteném BMI pod 18,5 kalkulačka nevydává další snižování jako cílový příjem.':'Zvolený model by klesl pod 1 200 kcal/den, proto kalkulačka cílové číslo nevydává a ponechává pouze udržovací orientaci.'}
setText('resultStatus',status);setText('mainLabel',label);setText('mainCalories',fmt(round10(target)));setText('mainKilojoules',fmt(round10(target*4.184)));setText('bmrValue',fmt(round10(bmr)));setText('tdeeValue',fmt(round10(tdee)));setText('activityLabel',activityNames[String(pal)]+' · PAL '+String(pal).replace('.',','));setText('rangeLow',fmt(rangeLo));setText('rangeHigh',fmt(rangeHi));setText('adjustmentLabel',goal==='lose'?'Modelový deficit':goal==='gain'?'Modelové navýšení':'Cílová úprava');setText('adjustmentDisplay',blocked?'—':(adjustment>0?'+':'')+fmt(adjustment)+' kcal');setText('goalLabel',blocked?'scénář není vydán jako cíl':'proti TDEE');setText('whyRest','BMR '+bmrPct+' %');setText('whyActivity','aktivita '+actPct+' %');setText('resultInsight',insight);setText('meal3',fmt(target/3)+' kcal');setText('meal4',fmt(target/4)+' kcal');setText('meal5',fmt(target/5)+' kcal');
const marker=qs('#targetMarker'); const span=rangeHi-rangeLo; marker.style.left=Math.max(0,Math.min(100,(target-rangeLo)/span*100))+'%';
const warn=qs('#safetyWarning'); warn.hidden=!blocked; warn.textContent=blockedLowBmi?'Při BMI pod 18,5 kalkulačka blokuje scénář dalšího snižování. Udržovací odhad není léčebné doporučení; vhodný postup řešte individuálně se zdravotníkem.':tooLow?'Zvolený scénář by vyšel pod 1 200 kcal/den. Tato hranice zde slouží jako varování, nikoli jako doporučený příjem. Zvolte mírnější scénář nebo individuální konzultaci.':'';
setText('heroTdee',fmt(round10(tdee)));setText('heroBmr',fmt(round10(bmr))+' kcal');setText('heroActivity','+'+fmt(round10(tdee-bmr))+' kcal');setText('heroRange',fmt(rangeLo)+'–'+fmt(rangeHi)+' kcal'); qs('#heroRing').style.setProperty('--rest',bmrPct+'%'); setText('anatomyBmr',fmt(round10(bmr))+' kcal');setText('anatomyMove','+'+fmt(round10(tdee-bmr))+' kcal');setText('anatomyTdee',fmt(round10(tdee))+' kcal');
lastResult={bmr:round10(bmr),tdee:round10(tdee),target:round10(target),status,goal,pal,blocked};}
qs('#toggleGoal').addEventListener('click',function(){const p=qs('#goalPanel'),open=p.hidden;p.hidden=!open;this.setAttribute('aria-expanded',String(open));this.textContent=open?'Skrýt scénář cíle':'Přidat scénář cíle';if(!open){qs('input[name="goal"][value="maintain"]').checked=true}updateGoalUi();calculate(false)});
form.addEventListener('input',e=>{if(e.target.matches('input'))calculate(false)});form.addEventListener('change',e=>{if(e.target.name==='goal')updateGoalUi();calculate(false)});form.addEventListener('submit',e=>{e.preventDefault();calculate(true);if(qs('#formError').hidden)qs('#vysledek').scrollIntoView({behavior:'smooth',block:'start'})});
qs('#resetForm').addEventListener('click',()=>{form.reset();qs('#goalPanel').hidden=true;qs('#toggleGoal').setAttribute('aria-expanded','false');qs('#toggleGoal').textContent='Přidat scénář cíle';updateGoalUi();calculate(false)});
qs('#copyResult').addEventListener('click',async function(){if(!lastResult)return;const t='Kalorická kalkulačka – orientační výsledek\nBMR: '+fmt(lastResult.bmr)+' kcal/den\nTDEE: '+fmt(lastResult.tdee)+' kcal/den\nZobrazený příjem: '+fmt(lastResult.target)+' kcal/den\nStav: '+lastResult.status+'\nPAL: '+String(lastResult.pal).replace('.',',')+'\nVýsledek je orientační populační odhad a nenahrazuje individuální nutriční doporučení.';try{await navigator.clipboard.writeText(t)}catch(e){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}const old=this.textContent;this.textContent='Zkopírováno';setTimeout(()=>this.textContent=old,1600)});
const menu=qs('.menu-btn'),mobile=qs('#mobile-nav');if(menu&&mobile){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));mobile.classList.toggle('is-open',!open)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');mobile.classList.remove('is-open')}})}
updateGoalUi();calculate(false);
})();
