(function(){
  const form=document.getElementById('leasingForm');if(!form)return;
  const resetBtn=document.getElementById('resetBtn');
  const $=id=>document.getElementById(id);
  const outputs={monthlyPaymentResult:$('monthlyPaymentResult'),downPaymentResult:$('downPaymentResult'),totalPaidResult:$('totalPaidResult'),overpaymentResult:$('overpaymentResult'),financedAmountResult:$('financedAmountResult'),residualValueResult:$('residualValueResult'),installmentsTotalResult:$('installmentsTotalResult'),processingFeeResult:$('processingFeeResult'),monthlyFeesTotalResult:$('monthlyFeesTotalResult'),downPaymentShareResult:$('downPaymentShareResult'),statusBadge:$('statusBadge'),interpretationNote:$('interpretationNote'),summaryTableBody:$('summaryTableBody'),heroMonthlyPayment:$('heroMonthlyPayment'),heroLeaseMeta:$('heroLeaseMeta'),heroDownPayment:$('heroDownPayment'),heroTotalPaid:$('heroTotalPaid'),heroOverpayment:$('heroOverpayment'),heroDownBar:$('heroDownBar'),heroFinancedBar:$('heroFinancedBar')};
  function formatCurrency(value){return new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(value)}
  function formatPercent(value){return new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:0,maximumFractionDigits:1}).format(value)+' %'}
  function ensureDecisionBlocks(){
    const note=document.querySelector('.rv-result-note');
    if(note && !document.querySelector('.rv-leasing-decision')){
      note.insertAdjacentHTML('beforeend','<p class="rv-leasing-decision"><strong id="leasingDecisionTitle">Jak výsledek číst</strong><span id="leasingDecisionText">Výsledek berte jako orientační srovnání scénářů.</span></p><p class="rv-leasing-decision"><strong id="leasingNextTitle">Další krok</strong><span id="leasingNextText">Po leasingu dopočítejte provoz auta a cenu za kilometr.</span></p>');
    }
    if(note && !document.querySelector('.rv-next-actions')){
      note.insertAdjacentHTML('afterend','<div class="rv-next-actions" aria-label="Co spočítat dál"><strong>Co spočítat dál</strong><div class="rv-next-actions__grid"><a href="/kalkulacka-splatky-auta.html">Porovnat se splátkou auta</a><a href="/naklady-na-provoz-auta-kalkulacka.html">Přidat provoz auta</a><a href="/cena-za-km-kalkulacka.html">Přepočítat na cenu za km</a></div></div>');
    }
  }
  function setText(id,value){const el=$(id);if(el)el.textContent=value}
  function getValues(){return{assetPrice:Number($('assetPrice').value),downPaymentPercent:Number($('downPaymentPercent').value),leaseMonths:Number($('leaseMonths').value),annualRate:Number($('annualRate').value),residualPercent:Number($('residualPercent').value),processingFee:Number($('processingFee').value),monthlyFee:Number($('monthlyFee').value),leaseType:$('leaseType').value}}
  function applyLeaseType(values){if(values.leaseType==='lowDown'){values.downPaymentPercent=10;values.residualPercent=10;$('downPaymentPercent').value=10;$('residualPercent').value=10}else if(values.leaseType==='higherResidual'){values.downPaymentPercent=15;values.residualPercent=20;$('downPaymentPercent').value=15;$('residualPercent').value=20}else if(values.leaseType==='standard'){values.downPaymentPercent=20;values.residualPercent=10;$('downPaymentPercent').value=20;$('residualPercent').value=10}return values}
  function validate(values){if(!values.assetPrice||values.assetPrice<=0)return'Zadejte platnou cenu předmětu leasingu.';if(Number.isNaN(values.downPaymentPercent)||values.downPaymentPercent<0||values.downPaymentPercent>=100)return'Zadejte platnou akontaci v procentech.';if(!values.leaseMonths||values.leaseMonths<=0)return'Zadejte platnou délku leasingu.';if(Number.isNaN(values.annualRate)||values.annualRate<0)return'Zadejte platnou roční úrokovou sazbu.';if(Number.isNaN(values.residualPercent)||values.residualPercent<0||values.residualPercent>=100)return'Zadejte platnou zůstatkovou hodnotu v procentech.';if(values.downPaymentPercent+values.residualPercent>=100)return'Součet akontace a zůstatkové hodnoty musí být nižší než 100 %.';if(Number.isNaN(values.processingFee)||values.processingFee<0)return'Zadejte platný jednorázový poplatek.';if(Number.isNaN(values.monthlyFee)||values.monthlyFee<0)return'Zadejte platný měsíční doplňkový poplatek.';return''}
  function calculateLeasing(values){const downPayment=values.assetPrice*(values.downPaymentPercent/100);const residualValue=values.assetPrice*(values.residualPercent/100);const financedAmount=values.assetPrice-downPayment;const principalForInstallments=financedAmount-residualValue;const monthlyRate=values.annualRate/100/12;let monthlyPaymentCore=0;if(monthlyRate===0){monthlyPaymentCore=principalForInstallments/values.leaseMonths}else{monthlyPaymentCore=(principalForInstallments*monthlyRate)/(1-Math.pow(1+monthlyRate,-values.leaseMonths))}const monthlyPayment=monthlyPaymentCore+values.monthlyFee;const installmentsTotal=monthlyPayment*values.leaseMonths;const monthlyFeesTotal=values.monthlyFee*values.leaseMonths;const totalPaid=downPayment+installmentsTotal+residualValue+values.processingFee;const overpayment=totalPaid-values.assetPrice;return{downPayment,residualValue,financedAmount,monthlyPayment,installmentsTotal,monthlyFeesTotal,totalPaid,overpayment}}
  function renderTable(result){outputs.summaryTableBody.innerHTML='<tr><td>Financovaná částka</td><td>'+formatCurrency(result.financedAmount)+'</td><td>Cena po odečtení akontace</td></tr><tr><td>Zůstatková hodnota</td><td>'+formatCurrency(result.residualValue)+'</td><td>Částka ponechaná na konec leasingu</td></tr><tr><td>Měsíční splátka</td><td>'+formatCurrency(result.monthlyPayment)+'</td><td>Orientační pravidelná platba</td></tr><tr><td>Celkem zaplatíte</td><td>'+formatCurrency(result.totalPaid)+'</td><td>Součet akontace, splátek, poplatků a zůstatku</td></tr>'}
  function getInterpretation(values,result){
    const overpaymentShare=result.overpayment/values.assetPrice;
    const residualShare=result.residualValue/values.assetPrice;
    if(result.monthlyPayment>values.assetPrice*0.025||overpaymentShare>0.25){
      return{badge:'Dražší scénář',tone:'warning',note:'Leasing vychází citelně dražší. Nízká měsíční splátka sama o sobě nestačí, protože rozhoduje také akontace, zůstatková hodnota, poplatky a celkem zaplacená částka.',decision:'Než půjdete dál, porovnejte stejný vůz se splátkou auta a ověřte, jestli celkové náklady dávají smysl proti hodnotě vozu.',next:'Zkuste vyšší akontaci, kratší dobu financování nebo nižší zůstatkovou hodnotu. Potom přidejte provoz auta, pojištění a servis.'};
    }
    if(residualShare>0.18){
      return{badge:'Pozor na zůstatek',tone:'border',note:'Splátka působí přijatelně, ale větší část ceny zůstává na konec. To může být v pořádku, pokud víte, jak s autem po skončení leasingu naložíte.',decision:'Důležité je mít jasno, zda auto odkoupíte, vrátíte, nebo navážete dalším financováním.',next:'Dopočítejte cenu za kilometr a porovnejte, jestli se varianta vyplatí proti běžnému úvěru na auto.'};
    }
    return{badge:'Rozumný scénář',tone:'success',note:'Zadaný scénář působí jako použitelná orientační varianta. Přesto ho berte jako model, ne jako závaznou nabídku poskytovatele.',decision:'Pro dobré rozhodnutí sledujte hlavně celkem zaplaceno a měsíční dopad včetně pojištění, servisu a poplatků.',next:'Navazujte výpočtem provozu auta a ceny za kilometr, aby leasing nebyl posuzovaný odděleně od reálného používání vozu.'};
  }
  function render(values,result){const interpretation=getInterpretation(values,result);outputs.monthlyPaymentResult.textContent=formatCurrency(result.monthlyPayment);outputs.downPaymentResult.textContent=formatCurrency(result.downPayment);outputs.totalPaidResult.textContent=formatCurrency(result.totalPaid);outputs.overpaymentResult.textContent=formatCurrency(result.overpayment);outputs.financedAmountResult.textContent=formatCurrency(result.financedAmount);outputs.residualValueResult.textContent=formatCurrency(result.residualValue);outputs.installmentsTotalResult.textContent=formatCurrency(result.installmentsTotal);outputs.processingFeeResult.textContent=formatCurrency(values.processingFee);outputs.monthlyFeesTotalResult.textContent=formatCurrency(result.monthlyFeesTotal);outputs.downPaymentShareResult.textContent=formatPercent(values.downPaymentPercent);outputs.interpretationNote.textContent=interpretation.note;outputs.statusBadge.className='badge '+interpretation.tone;outputs.statusBadge.textContent=interpretation.badge;setText('leasingDecisionText',interpretation.decision);setText('leasingNextText',interpretation.next);outputs.heroMonthlyPayment.textContent=formatCurrency(result.monthlyPayment);outputs.heroLeaseMeta.textContent=formatCurrency(values.assetPrice)+', '+values.leaseMonths+' měsíců';outputs.heroDownPayment.textContent=formatCurrency(result.downPayment);outputs.heroTotalPaid.textContent=formatCurrency(result.totalPaid);outputs.heroOverpayment.textContent=formatCurrency(result.overpayment);outputs.heroDownBar.style.width=Math.max(6,Math.min(80,values.downPaymentPercent))+'%';outputs.heroFinancedBar.style.width=Math.max(10,Math.min(94,100-values.downPaymentPercent))+'%';renderTable(result)}
  function renderError(error){outputs.statusBadge.className='badge warning';outputs.statusBadge.textContent='Zkontrolujte zadání';outputs.monthlyPaymentResult.textContent='0 Kč';outputs.interpretationNote.textContent=error;setText('leasingDecisionText','Některá vstupní hodnota nedává smysl, proto výsledek zatím není možné spolehlivě interpretovat.');setText('leasingNextText','Upravte cenu, akontaci, zůstatkovou hodnotu nebo dobu leasingu a výpočet se znovu přepočítá.')}
  function runCalculation(){let values=getValues();if(values.leaseType!=='custom')values=applyLeaseType(values);const error=validate(values);if(error){renderError(error);return}render(values,calculateLeasing(values))}
  ensureDecisionBlocks();form.addEventListener('submit',e=>{e.preventDefault();runCalculation()});['assetPrice','downPaymentPercent','leaseMonths','annualRate','residualPercent','processingFee','monthlyFee','leaseType'].forEach(id=>{const el=$(id);function update(){if(id==='downPaymentPercent'||id==='residualPercent')$('leaseType').value='custom';runCalculation()}el.addEventListener('input',update);el.addEventListener('change',update)});resetBtn.addEventListener('click',()=>{$('assetPrice').value=650000;$('downPaymentPercent').value=20;$('leaseMonths').value=60;$('annualRate').value=6.9;$('residualPercent').value=10;$('processingFee').value=5000;$('monthlyFee').value=0;$('leaseType').value='standard';runCalculation()});runCalculation();
})();
