(()=>{"use strict";
const $=id=>document.getElementById(id);const form=$("maternityForm");if(!form)return;
const RH1=1633,RH2=2449,RH3=4897;const money=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:0});const dateFmt=new Intl.DateTimeFormat("cs-CZ",{day:"numeric",month:"short",year:"numeric"});
let mode="basic",caseType="motherSingle";
const duration={motherSingle:196,motherMultiple:259,takeoverSingle:154,takeoverMultiple:217};
const weeks={motherSingle:28,motherMultiple:37,takeoverSingle:22,takeoverMultiple:31};
function parseNum(v){const n=Number(String(v??"").replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0}
function fmt(n){return `${money.format(Math.round(Number.isFinite(n)?n:0))} Kč`}
function signed(n){const v=Math.round(n);return `${v>0?'+':''}${money.format(v)} Kč`}
function set(id,v){const el=$(id);if(el)el.textContent=v}
function reduceDvz(dvz){const p1=Math.min(Math.max(dvz,0),RH1);const p2=Math.min(Math.max(dvz-RH1,0),RH2-RH1)*.6;const p3=Math.min(Math.max(dvz-RH2,0),RH3-RH2)*.3;return Math.ceil(p1+p2+p3)}
function benefit(dvz){return Math.ceil(reduceDvz(dvz)*.7)}
function addInclusive(date,days){if(!date)return null;const d=new Date(date.getTime());d.setDate(d.getDate()+Math.max(1,Math.round(days))-1);return d}
function readDate(id){const v=$(id)?.value;return v?new Date(`${v}T12:00:00`):null}
function syncDates(source){const a=$("startDate"),b=$("startDateAdvanced");if(source===a&&b)b.value=a.value;if(source===b&&a)a.value=b.value}
function inputs(){if(mode==="basic"){const monthly=parseNum($("monthlyIncome").value);return{monthly,total:monthly*12,days:365,dvz:monthly*12/365,source:"employee",start:readDate("startDate")}}const total=parseNum($("periodIncome").value),days=Math.max(1,parseNum($("periodDays").value));return{monthly:total/12,total,days,dvz:total/days,source:$("incomeSource").value,start:readDate("startDateAdvanced")}}
function render(){const v=inputs();const rdvz=reduceDvz(v.dvz);const daily=benefit(v.dvz);const daysTotal=duration[caseType];const total=daily*daysTotal;const m28=daily*28,m30=daily*30,m31=daily*31;const end=addInclusive(v.start,daysTotal);const grossBase=mode==="basic"?v.monthly:v.total/12;
set("monthlyResult",fmt(m30));set("dailyResult",fmt(daily));set("totalResult",fmt(total));set("durationResult",`${daysTotal} dnů · ${weeks[caseType]} týdnů`);set("endResult",end?dateFmt.format(end):"zadejte datum");set("resultSentence",`Při zadaném příjmu vychází denní PPM přibližně na ${fmt(daily)}.`);set("resultMode",mode==="basic"?"RYCHLÝ ODHAD":"PŘESNĚJŠÍ MODEL");
set("heroGross",fmt(grossBase));set("heroPpm",fmt(m30));set("heroDaily",`${fmt(daily)} / den`);set("heroEnd",end?dateFmt.format(end):"—");set("month28",fmt(m28));set("month30",fmt(m30));set("month31",fmt(m31));set("meaningMonth",fmt(m30));set("meaningGap",signed(m30-grossBase));set("meaningEnd",end?dateFmt.format(end):"—");set("handoffText",end?`PPM v tomto modelu končí ${dateFmt.format(end)}. Před tímto datem si zkontrolujte návaznost rodičovského příspěvku a rozpočet domácnosti.`:"Po skončení PPM si zkontrolujte návaznost rodičovského příspěvku a rozpočet domácnosti.");
const max=m31||1;[["bar28",m28],["bar30",m30],["bar31",m31]].forEach(([id,val])=>{const el=$(id);if(el)el.style.width=`${Math.max(8,val/max*100)}%`});updateEligibility()}
function updateEligibility(){const card=$("eligibilityCard");card.classList.remove("is-success","is-warning");if(mode!=="advanced"){set("eligibilityIcon","i");set("eligibilityTitle","Nárok ještě neověřujeme.");set("eligibilityText","Přepněte na přesnější režim a doplňte údaje o pojištění.");return}const ins=parseNum($("insuranceDays").value),active=$("insuredAtStart").checked,osvc=$("incomeSource").value==="osvc",osvcDays=parseNum($("osvcInsuranceDays").value);const ok=ins>=270&&active&&(!osvc||osvcDays>=180);if(ok){card.classList.add("is-success");set("eligibilityIcon","✓");set("eligibilityTitle","Základní podmínky podle zadaných údajů vycházejí kladně.");set("eligibilityText","Jde jen o orientační kontrolu čekací doby a stavu pojištění. Konečný nárok potvrzuje ČSSZ.")}else{card.classList.add("is-warning");const reasons=[];if(ins<270)reasons.push(`${Math.round(ins)} z 270 dnů pojištění`);if(!active)reasons.push("není potvrzené pojištění ani ochranná lhůta");if(osvc&&osvcDays<180)reasons.push(`${Math.round(osvcDays)} z 180 dnů pojištění OSVČ`);set("eligibilityIcon","!");set("eligibilityTitle","Některá základní podmínka nemusí být splněna.");set("eligibilityText",`Zkontrolujte: ${reasons.join(", ")}. Individuální situaci ověřte u OSSZ.`)}}
function setMode(next){mode=next;const basic=mode==="basic";$("mat80BasicPanel").hidden=!basic;$("mat80AdvancedPanel").hidden=basic;$("mat80BasicTab").classList.toggle("is-active",basic);$("mat80AdvancedTab").classList.toggle("is-active",!basic);$("mat80BasicTab").setAttribute("aria-selected",String(basic));$("mat80AdvancedTab").setAttribute("aria-selected",String(!basic));$("mat80BasicTab").tabIndex=basic?0:-1;$("mat80AdvancedTab").tabIndex=basic?-1:0;set("modeHelp",basic?"Pro rychlý odhad stačí běžná měsíční hrubá mzda, datum nástupu a situace po porodu.":"Přesnější režim používá skutečný započitatelný příjem a počet dnů z rozhodného období.");updateSource();render()}
function updateSource(){const osvc=mode==="advanced"&&$("incomeSource").value==="osvc";document.querySelectorAll(".mat80-osvc-only").forEach(el=>el.hidden=!osvc);set("periodIncomeHelp",osvc?"Součet základů, ze kterých bylo zaplaceno nemocenské pojištění OSVČ. Nezadávejte obrat ani daňový zisk.":"Příjem zahrnutý do vyměřovacího základu nemocenského pojištění.");set("incomeSourceHelp",osvc?"U OSVČ je pro PPM nutné dobrovolné nemocenské pojištění a další čekací doba.":"U zaměstnance se vychází z pojištěného příjmu.")}
function defaultStart(){const d=new Date();d.setDate(d.getDate()+42);const s=d.toISOString().slice(0,10);if(!$("startDate").value)$("startDate").value=s;if(!$("startDateAdvanced").value)$("startDateAdvanced").value=s}
form.addEventListener("submit",e=>{e.preventDefault();render()});document.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));document.querySelectorAll("[data-case]").forEach(b=>b.addEventListener("click",()=>{caseType=b.dataset.case;document.querySelectorAll("[data-case]").forEach(x=>x.classList.toggle("is-active",x===b));render()}));
["monthlyIncome","periodIncome","periodDays","insuranceDays","osvcInsuranceDays"].forEach(id=>$(id)?.addEventListener("input",render));["insuredAtStart","incomeSource"].forEach(id=>$(id)?.addEventListener("change",()=>{if(id==="incomeSource")updateSource();render()}));$("startDate")?.addEventListener("change",e=>{syncDates(e.target);render()});$("startDateAdvanced")?.addEventListener("change",e=>{syncDates(e.target);render()});
const menu=document.querySelector(".mat80-menu"),mobile=document.querySelector(".mat80-mobile-nav");menu?.addEventListener("click",()=>{const open=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!open));mobile.hidden=open});
defaultStart();setMode("basic");
window.RV_MAT80_TEST={reduceDvz,benefit,duration};
})();
