/* Calculator-specific V2 logic. Shared helpers live in /assets/js/rv-tool-core.js. */
window.rvTrack = window.rvTrack || function(eventName, params){ window.dataLayer = window.dataLayer || []; window.dataLayer.push({event:eventName, ...params}); };
    (function(){
      const form = document.getElementById('mortgageForm');
      const resetBtn = document.getElementById('resetBtn');
      const presetButtons = Array.from(document.querySelectorAll('.scenario-chip'));
      const outputs = {
        errorBox: document.getElementById('errorBox'), monthlyPayment: document.getElementById('monthlyPayment'), monthlyWithFees: document.getElementById('monthlyWithFees'), mobileMonthly: document.getElementById('mobileMonthly'), heroMonthly: document.getElementById('heroMonthly'),
        totalPaid: document.getElementById('totalPaid'), totalInterest: document.getElementById('totalInterest'), neededIncomeInline: document.getElementById('neededIncomeInline'), ownFunds: document.getElementById('ownFunds'), ltvValue: document.getElementById('ltvValue'), heroLtv: document.getElementById('heroLtv'), heroRisk: document.getElementById('heroRisk'),
        affordabilityStatus: document.getElementById('affordabilityStatus'), affordabilityText: document.getElementById('affordabilityText'), primaryNextCta: document.getElementById('primaryNextCta'), actionStatus: document.getElementById('actionStatus'), decisionHeadline: document.getElementById('decisionHeadline'), decisionSummary: document.getElementById('decisionSummary'), decisionMonthly: document.getElementById('decisionMonthly'),
        stressIncreaseText: document.getElementById('stressIncreaseText'), summaryInstallments: document.getElementById('summaryInstallments'), ltvBadge: document.getElementById('ltvBadge'), ltvMeterFill: document.getElementById('ltvMeterFill'), incomeMeterLabel: document.getElementById('incomeMeterLabel'), incomeMeterFill: document.getElementById('incomeMeterFill'), nextActionText: document.getElementById('nextActionText'), stressTestText: document.getElementById('stressTestText'), scheduleBody: document.getElementById('scheduleBody')
      };
      function formatCurrency(value){ return new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Number.isFinite(value)?value:0); }
      function formatPercent(value,digits=1){ return new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:0,maximumFractionDigits:digits}).format(Number.isFinite(value)?value:0) + ' %'; }
      function getNumber(id){ return Number(document.getElementById(id).value); }
      function getValues(){ return { loanAmount:getNumber('loanAmount'), propertyValue:getNumber('propertyValue'), interestRate:getNumber('interestRate'), years:getNumber('years'), monthlyFee:getNumber('monthlyFee'), incomeShare:getNumber('incomeShare') }; }
      function validate(values){ if(!values.propertyValue || values.propertyValue<=0) return 'Zadejte platnou cenu nemovitosti.'; if(!values.loanAmount || values.loanAmount<=0) return 'Zadejte platnou výši hypotéky.'; if(values.interestRate < 0 || !Number.isFinite(values.interestRate)) return 'Zadejte platnou úrokovou sazbu.'; if(!values.years || values.years<=0 || values.years>45) return 'Zadejte platnou dobu splácení.'; if(values.incomeShare<=0 || values.incomeShare>90) return 'Zadejte rozumný podíl splátky na příjmu.'; if(values.loanAmount>values.propertyValue*1.5) return 'Výše hypotéky je neobvykle vysoká vůči ceně nemovitosti. Zkontrolujte zadání.'; return ''; }
      function calculateMortgage(values){ const months=values.years*12; const monthlyRate=values.interestRate/100/12; const monthlyPayment = monthlyRate===0 ? values.loanAmount/months : values.loanAmount*(monthlyRate*Math.pow(1+monthlyRate,months))/(Math.pow(1+monthlyRate,months)-1); const totalPaidWithoutFees=monthlyPayment*months; const totalInterestWithoutFees=totalPaidWithoutFees-values.loanAmount; const monthlyWithFees=monthlyPayment+values.monthlyFee; const totalFees=values.monthlyFee*months; const totalPaid=totalPaidWithoutFees+totalFees; const totalInterest=totalInterestWithoutFees+totalFees; const ltv=(values.loanAmount/values.propertyValue)*100; const neededIncome=monthlyWithFees/(values.incomeShare/100); return {months,monthlyPayment,monthlyWithFees,totalPaid,totalInterest,ltv,neededIncome}; }
      function buildSchedule(values, monthlyPayment, months){ const monthlyRate=values.interestRate/100/12; let balance=values.loanAmount; const rows=[]; for(let i=1;i<=months;i++){ const interestPart=monthlyRate===0?0:balance*monthlyRate; const principalPart=monthlyPayment-interestPart; balance=Math.max(0,balance-principalPart); rows.push({month:i,payment:monthlyPayment,interest:interestPart,principal:principalPart,balance}); } const preview=[]; rows.slice(0,4).forEach(r=>preview.push(r)); if(rows.length>8) preview.push({separator:true}); rows.slice(-4).forEach(r=>preview.push(r)); return preview; }
      function renderSchedule(schedule){ outputs.scheduleBody.innerHTML = schedule.map(row => row.separator ? '<tr><td colspan="5">...</td></tr>' : `<tr><td>${row.month}.</td><td>${formatCurrency(row.payment)}</td><td>${formatCurrency(row.interest)}</td><td>${formatCurrency(row.principal)}</td><td>${formatCurrency(row.balance)}</td></tr>`).join(''); }
      function getAffordability(result, values){ const ltv=result.ltv; const income=result.neededIncome; const stress=calculateMortgage({...values, interestRate: values.interestRate + 1}); let data={className:'warning',label:'Na hraně rozpočtu',headline:'Scénář je použitelný, ale hlídejte rezervu',text:'Splátka může být zvládnutelná, ale je dobré počítat i s provozem bydlení, rezervou a možným růstem sazby.',summary:'Porovnejte nižší úvěr, vyšší vlastní zdroje nebo delší splatnost. Největší riziko bývá kombinace vysokého LTV a napjatého příjmu.',next:'Pokud výsledek vychází těsně, zkuste snížit úvěr, prodloužit splatnost nebo navýšit vlastní zdroje.',cta:'/kalkulacka-vlastnich-zdroju-na-koupi-nemovitosti.html',ctaText:'Spočítat vlastní zdroje',heroRisk:'na hraně'}; if(income<=45000 && ltv<=80){ data={className:'success',label:'Rozumnější scénář',headline:'Scénář působí relativně zdravě',text:'Při těchto hodnotách vychází splátka a LTV rozumněji, pokud má domácnost stabilní příjem a finanční rezervu.',summary:'Teď dává smysl porovnat nájem vs hypotéku, ověřit náklady vlastnictví a zkontrolovat více sazeb.',next:'Jste v lepší výchozí pozici. Další krok je porovnat varianty bydlení a celkové náklady.',cta:'/porovnani-najem-vs-hypoteka-kalkulacka.html',ctaText:'Porovnat nájem vs hypotéka',heroRisk:'rozumnější scénář'}; } else if(income>65000 || ltv>90){ data={className:'risk',label:'Rizikovější scénář',headline:'Scénář je citlivý na příjem i sazbu',text:'Vyšší potřebný příjem nebo vysoké LTV znamená větší tlak na rozpočet. Doporučujeme přepočítat konzervativnější variantu.',summary:'Největší páka je nižší úvěr, vyšší vlastní zdroje, delší splatnost nebo ověření reálného čistého příjmu domácnosti.',next:'Začněte snížením LTV nebo ověřením čistého příjmu. U takového scénáře je rezerva zásadní.',cta:'/cista-mzda-kalkulacka.html',ctaText:'Ověřit čistý příjem',heroRisk:'rizikovější scénář'}; } data.stress=stress; return data; }
      function classForLtv(ltv){ return ltv<=80 ? 'success' : ltv<=90 ? 'warning' : 'risk'; }
      function classForIncomeShare(share){ return share<=35 ? 'success' : share<=45 ? 'warning' : 'risk'; }
      function render(values,result){ outputs.errorBox.classList.remove('is-visible'); outputs.monthlyPayment.textContent=formatCurrency(result.monthlyPayment); outputs.monthlyWithFees.textContent=formatCurrency(result.monthlyWithFees); outputs.mobileMonthly.textContent=formatCurrency(result.monthlyWithFees); outputs.heroMonthly.textContent=formatCurrency(result.monthlyWithFees); outputs.decisionMonthly.textContent=formatCurrency(result.monthlyWithFees); outputs.totalPaid.textContent=formatCurrency(result.totalPaid); outputs.totalInterest.textContent=formatCurrency(result.totalInterest); outputs.neededIncomeInline.textContent=formatCurrency(result.neededIncome); const ownFunds=Math.max(0,values.propertyValue-values.loanAmount); outputs.ownFunds.textContent=formatCurrency(ownFunds); const ltvRounded=Number(result.ltv.toFixed(1)); const ltvClass=classForLtv(ltvRounded); outputs.ltvValue.textContent=formatPercent(ltvRounded); outputs.heroLtv.textContent=formatPercent(ltvRounded,0); outputs.ltvBadge.textContent='LTV: '+formatPercent(ltvRounded); outputs.ltvBadge.className='badge '+ltvClass; outputs.ltvMeterFill.style.width=Math.min(100,Math.max(0,ltvRounded))+'%'; outputs.ltvMeterFill.className=ltvClass; outputs.incomeMeterFill.style.width=Math.min(100,Math.max(0,values.incomeShare))+'%'; outputs.incomeMeterFill.className=classForIncomeShare(values.incomeShare); outputs.incomeMeterLabel.textContent=formatPercent(values.incomeShare,0)+' příjmu'; outputs.incomeMeterLabel.className='badge '+classForIncomeShare(values.incomeShare); outputs.summaryInstallments.textContent=String(result.months); const affordability=getAffordability(result,values); outputs.affordabilityStatus.textContent=affordability.label; outputs.affordabilityStatus.className='decision-status '+affordability.className; outputs.affordabilityText.textContent=affordability.text; outputs.primaryNextCta.href=affordability.cta; outputs.primaryNextCta.textContent=affordability.ctaText; outputs.actionStatus.textContent=affordability.label; outputs.actionStatus.className='decision-status '+affordability.className; outputs.decisionHeadline.textContent=affordability.headline; outputs.decisionSummary.textContent=affordability.summary; outputs.nextActionText.textContent=affordability.next; outputs.heroRisk.textContent=affordability.heroRisk; const stressIncrease=affordability.stress.monthlyWithFees-result.monthlyWithFees; outputs.stressIncreaseText.textContent=(stressIncrease>=0?'+':'')+formatCurrency(stressIncrease); outputs.stressTestText.textContent='Při sazbě vyšší o 1 procentní bod by měsíční zatížení vyšlo přibližně na '+formatCurrency(affordability.stress.monthlyWithFees)+'.'; renderSchedule(buildSchedule(values,result.monthlyPayment,result.months)); }
      function runCalculation(track=false){ const values=getValues(); const error=validate(values); if(error){ outputs.errorBox.textContent=error; outputs.errorBox.classList.add('is-visible'); return; } const result=calculateMortgage(values); render(values,result); if(track) window.rvTrack('mortgage_calculated',{loan_amount:values.loanAmount,property_value:values.propertyValue,ltv:Math.round(result.ltv),years:values.years}); }
      function setPreset(name){ const presets={standard:{loanAmount:4000000,propertyValue:5000000,interestRate:4.89,years:30,monthlyFee:0,incomeShare:40},conservative:{loanAmount:3500000,propertyValue:5000000,interestRate:4.89,years:30,monthlyFee:0,incomeShare:35},'higher-loan':{loanAmount:4500000,propertyValue:5000000,interestRate:4.89,years:30,monthlyFee:0,incomeShare:40},shorter:{loanAmount:4000000,propertyValue:5000000,interestRate:4.89,years:25,monthlyFee:0,incomeShare:40}}; const preset=presets[name]; if(!preset) return; Object.entries(preset).forEach(([key,value])=>{ document.getElementById(key).value=value; }); presetButtons.forEach(btn=>btn.classList.toggle('active',btn.dataset.preset===name)); window.rvTrack('mortgage_preset_selected',{preset:name}); runCalculation(); }
      form.addEventListener('submit', e => { e.preventDefault(); runCalculation(true); }); form.addEventListener('input', () => runCalculation()); resetBtn.addEventListener('click', () => setPreset('standard')); presetButtons.forEach(btn => btn.addEventListener('click', () => setPreset(btn.dataset.preset))); runCalculation();
    })();
