(function(){
  const $=(id)=>document.getElementById(id), form=$('diapersForm'); if(!form) return;
  const money=(v)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Math.max(0,v||0));
  const money2=(v)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',minimumFractionDigits:2,maximumFractionDigits:2}).format(Math.max(0,v||0));
  const pct=(v,d=1)=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:d}).format(v)+' %';
  const num=(v,d=1)=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:d}).format(v);
  const ids=['diapersPerDay','packPrice','piecesInPack','wipesMonthly','monthsPeriod','householdIncome','incomeShare'];
  const out=['monthlyCost','periodCost','pricePerDiaper','yearlyCost','diapersPerMonth','packsPerMonth','monthlyWithExtras','incomeShareResult','neededIncome','budgetBadge','budgetStatus','budgetText','actionStatus','decisionSummary','nextActionText','scenarioTableBody','heroMonthly','heroPiece','heroYearly','heroPacks','heroDiaperBar','heroWipesBar','heroPeriodBar'];
  const el=Object.fromEntries(out.map(id=>[id,$(id)]));
  function val(){return Object.fromEntries(ids.map(id=>[id,Number($(id).value)||0]));}
  function calc(v){const piece=v.packPrice/v.piecesInPack; const monthPieces=v.diapersPerDay*30; const diaperMonthly=monthPieces*piece; const packs=monthPieces/v.piecesInPack; const monthly=diaperMonthly+v.wipesMonthly; return {piece,monthPieces,diaperMonthly,packs,monthly,yearly:monthly*12,period:monthly*v.monthsPeriod,share:v.householdIncome>0?monthly/v.householdIncome*100:0,needed:v.incomeShare>0?monthly/(v.incomeShare/100):0};}
  function msg(r){if(r.share<=2.5)return['success','Položka spíše v pohodě','Vůči zadanému příjmu působí pleny zvládnutelně. Nejdůležitější je hlídat cenu za kus a slevové balení.','Dobrá pozice','Výsledek vypadá rozumně. Teď ho zasaďte do prvního roku dítěte.']; if(r.share>4||r.piece>7)return['risk','Položka: vyšší zátěž','Pleny už tvoří výraznější pravidelný výdaj. Zkontrolujte cenu za kus, denní spotřebu a související hygienu.','Pozor','Tento scénář je citlivý na dražší značku i vyšší spotřebu.']; return['warning','Položka na hraně','Pleny jsou viditelná měsíční položka. Vyplatí se porovnat cenu za kus a sledovat součet s ubrousky.','Další krok','Nejdřív ověřte, jestli problém dělá cena balení, nebo počet plen za den.'];}
  function rows(v){return[{label:'Úspornější balení',packPrice:v.packPrice*.88,pieces:v.piecesInPack,day:v.diapersPerDay,wipes:v.wipesMonthly},{label:'Běžný scénář',packPrice:v.packPrice,pieces:v.piecesInPack,day:v.diapersPerDay,wipes:v.wipesMonthly},{label:'Vyšší spotřeba',packPrice:v.packPrice,pieces:v.piecesInPack,day:v.diapersPerDay*1.2,wipes:v.wipesMonthly},{label:'Dražší značka',packPrice:v.packPrice*1.18,pieces:v.piecesInPack,day:v.diapersPerDay,wipes:v.wipesMonthly}].map(row=>{const piece=row.packPrice/row.pieces; const monthly=row.day*30*piece+row.wipes; return {label:row.label,piece,monthly,yearly:monthly*12,share:v.householdIncome>0?monthly/v.householdIncome*100:0};});}
  function render(){const v=val(), r=calc(v), m=msg(r); el.monthlyCost.textContent=money(r.diaperMonthly); el.periodCost.textContent=money(r.period); el.pricePerDiaper.textContent=money2(r.piece); el.yearlyCost.textContent=money(r.yearly); el.diapersPerMonth.textContent=num(r.monthPieces,0)+' ks'; el.packsPerMonth.textContent=num(r.packs,2); el.monthlyWithExtras.textContent=money(r.monthly); el.incomeShareResult.textContent=pct(r.share); el.neededIncome.textContent=money(r.needed); el.budgetBadge.textContent=m[1]; el.budgetBadge.className='rv-family-score '+m[0]; el.budgetStatus.textContent=m[1].replace('Položka: ',''); el.budgetText.textContent=m[2]; el.actionStatus.textContent=m[3]; el.decisionSummary.textContent=m[4]; el.nextActionText.textContent='Pokud výsledek vychází vysoko, porovnejte cenu za kus a až potom řešte značku nebo velikost balení.'; el.scenarioTableBody.innerHTML=rows(v).map(row=>`<tr><td>${row.label}</td><td>${money2(row.piece)}</td><td>${money(row.monthly)}</td><td>${money(row.yearly)}</td><td>${pct(row.share)}</td></tr>`).join(''); if(el.heroMonthly){el.heroMonthly.textContent=money(r.monthly); el.heroPiece.textContent=money2(r.piece); el.heroYearly.textContent=money(r.yearly); el.heroPacks.textContent=num(r.packs,1)+' bal./měs.'; el.heroDiaperBar.style.width=Math.min(100,(r.diaperMonthly/r.monthly)*100)+'%'; el.heroWipesBar.style.width=Math.min(100,(v.wipesMonthly/r.monthly)*100)+'%'; el.heroPeriodBar.style.width=Math.min(100,(v.monthsPeriod/24)*100)+'%';}}
  const presets={standard:{diapersPerDay:7,packPrice:449,piecesInPack:84,wipesMonthly:350,monthsPeriod:12,householdIncome:65000,incomeShare:3},saving:{diapersPerDay:7,packPrice:359,piecesInPack:96,wipesMonthly:280,monthsPeriod:12,householdIncome:65000,incomeShare:3},'higher-use':{diapersPerDay:9,packPrice:449,piecesInPack:84,wipesMonthly:420,monthsPeriod:12,householdIncome:65000,incomeShare:4},premium:{diapersPerDay:7,packPrice:579,piecesInPack:76,wipesMonthly:420,monthsPeriod:12,householdIncome:65000,incomeShare:4}};
  document.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>{const p=presets[btn.dataset.preset]; if(!p)return; Object.entries(p).forEach(([k,v])=>{$(k).value=v}); document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b===btn)); render();}));
  $('resetBtn')?.addEventListener('click',()=>document.querySelector('[data-preset="standard"]')?.click());
  ids.forEach(id=>{$(id).addEventListener('input',render);$(id).addEventListener('change',render)}); form.addEventListener('submit',e=>{e.preventDefault();render()}); render();
})();
