(() => {
  'use strict';
  const d=document,$=id=>d.getElementById(id),root=d.body,form=$('diaperForm');
  if(!form)return;
  const nf=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2});
  const money=v=>`${new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:0}).format(Number.isFinite(v)?v:0)} Kč`;
  const num=v=>nf.format(Number.isFinite(v)?v:0);
  const clamp=(v,min,max)=>Math.min(Math.max(v,min),max);
  const numeric=['packPrice','packCount','dailyUse','extras','days','buffer','months','budget','p1Months','p1Piece','p1Daily','p2Months','p2Piece','p2Daily','p3Months','p3Piece','p3Daily','wipes','care','supplies','equipment','discount','waste','clothSetup','washesWeek','washCost','detergent','clothExtras','residual'];
  let mode='basic',step=0,last=null;
  function parse(v){const n=Number.parseFloat(String(v??'').replace(/[\s\u00a0]/g,'').replace(',','.').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:0}
  function read(id){const el=$(id);if(!el)return 0;return clamp(parse(el.value),parse(el.dataset.min??'-1e99'),parse(el.dataset.max??'1e99'))}
  function fmtInput(id){const el=$(id);if(!el)return;el.value=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:['packPrice','dailyUse','days','buffer','p1Piece','p1Daily','p2Piece','p2Daily','p3Piece','p3Daily','discount','waste','washesWeek','washCost','detergent'].includes(id)?2:0}).format(read(id))}
  const text=(id,v)=>{const el=$(id);if(el)el.textContent=v};
  function basicValues(){return {price:read('packPrice'),count:read('packCount'),daily:read('dailyUse'),extras:read('extras'),days:read('days'),buffer:read('buffer'),months:read('months'),budget:read('budget')}}
  function calcBasic(v){const piece=v.price/Math.max(v.count,1),pieces=v.daily*v.days,packs=pieces/Math.max(v.count,1),diaper=pieces*piece*(1+v.buffer/100),monthly=diaper+v.extras,period=monthly*v.months;return {mode:'basic',piece,pieces,packs,diaper,extras:v.extras,monthly,period,months:v.months,budget:v.budget,cloth:null}}
  function advancedValues(){return {periods:[1,2,3].map(i=>({months:read(`p${i}Months`),piece:read(`p${i}Piece`),daily:read(`p${i}Daily`)})),days:read('days'),wipes:read('wipes'),care:read('care'),supplies:read('supplies'),equipment:read('equipment'),discount:read('discount'),waste:read('waste'),budget:read('budget'),clothSetup:read('clothSetup'),washesWeek:read('washesWeek'),washCost:read('washCost'),detergent:read('detergent'),clothExtras:read('clothExtras'),residual:read('residual')}}
  function calcAdvanced(v){let diaper=0,pieces=0,months=0,weightedPiece=0;v.periods.forEach(p=>{const qty=p.daily*v.days*p.months;const cost=qty*p.piece;pieces+=qty;diaper+=cost;months+=p.months;weightedPiece+=p.piece*qty});diaper*=1+v.waste/100;const extrasMonthly=(v.wipes+v.care+v.supplies)*(1-v.discount/100);const extras=extrasMonthly*months;const period=diaper+extras+v.equipment;const monthly=months>0?period/months:0;const piece=pieces>0?weightedPiece/pieces:0;const packs=piece>0?0:0;const washCycles=v.washesWeek*52/12*months;const cloth=Math.max(0,v.clothSetup+washCycles*(v.washCost+v.detergent)+v.clothExtras-v.residual);return {mode:'advanced',piece,pieces:months?pieces/months:0,packs,diaper:months?diaper/months:0,extras:months?extras/months:0,monthly,period,months,budget:v.budget,cloth,periodPieces:pieces}}
  function decide(r){if(r.budget>0&&r.monthly>r.budget)return ['Nad zadaným limitem',`Aktuální odhad překračuje měsíční limit o ${money(r.monthly-r.budget)}. Nejprve ověřte cenu za kus, skutečnou spotřebu a doplňky; nesnižujte potřebnou péči jen kvůli výsledku.`];if(r.piece>7)return ['Vyšší cena za kus',`Jedna plena vychází přibližně na ${money(r.piece)}. Porovnejte stejné velikosti a ověřte, zda dražší balení přináší hodnotu, kterou skutečně využijete.`];if(r.extras/r.monthly>.3)return ['Doplňky tvoří velkou část',`Samotné pleny nejsou jedinou položkou. Doplňky tvoří přibližně ${num(r.extras/r.monthly*100)} % měsíčního rozpočtu, proto je sledujte samostatně.`];return ['Použitelný rozpočtový rámec',`Měsíční odhad je ${money(r.monthly)}. Pro nákup sledujte cenu za kus a stav domácí zásoby; pro dlouhodobý plán používejte průměr bez automatického zaokrouhlení každého měsíce nahoru.`]}
  function breakdown(r){const list=$('breakdownList');if(!list)return;const rows=[['Samotné pleny',r.diaper,'spotřeba × cena za kus'],['Hygiena a doplňky',r.extras,'pravidelné měsíční výdaje'],['Celkem měsíčně',r.monthly,'finanční průměr'],[`Celkem za ${num(r.months)} měsíců`,r.period,'bez dalšího růstu cen']];list.replaceChildren(...rows.map((x,i)=>{const row=d.createElement('div');row.className='breakdown-row'+(i>1?' is-total':'');const c=d.createElement('div'),s=d.createElement('strong'),sm=d.createElement('small'),b=d.createElement('b');s.textContent=x[0];sm.textContent=x[2];b.textContent=money(x[1]);c.append(s,sm);row.append(c,b);return row}))}
  function render(){const r=mode==='advanced'?calcAdvanced(advancedValues()):calcBasic(basicValues());last=r;const [head,copy]=decide(r);text('modeLabel',mode==='advanced'?'Podrobný plán':'Rychlý odhad');text('monthlyTotal',money(r.monthly));text('range',`Pracovní interval: ${money(r.monthly*.9)} až ${money(r.monthly*1.12)}`);text('summary',`Samotné pleny tvoří ${num(r.diaper/Math.max(r.monthly,1)*100)} % a doplňky ${num(r.extras/Math.max(r.monthly,1)*100)} % měsíčního odhadu.`);text('piecePrice',`${num(r.piece)} Kč`);text('piecesMonth',`${num(r.pieces)} ks`);text('packsMonth',mode==='basic'?num(r.packs):'více období');text('periodTotal',money(r.period));text('periodLabel',`${num(r.months)} měsíců`);text('badge',head);text('decisionHeadline',head);text('decisionText',copy);text('scenarioLow',money(Math.max(0,r.monthly-r.piece*read('days'))));text('scenarioCurrent',money(r.monthly));text('scenarioHigh',money(r.monthly+r.piece*read('days')));text('heroTotal',money(r.monthly));text('heroPiece',`${num(r.piece)} Kč`);text('heroPacks',mode==='basic'?num(r.packs):'plán');text('heroYear',money(r.monthly*12));const bd=$('barDiapers'),be=$('barExtras');if(bd)bd.style.width=`${clamp(r.diaper/Math.max(r.monthly,1)*100,5,100)}%`;if(be)be.style.width=`${clamp(r.extras/Math.max(r.monthly,1)*100,5,100)}%`;const box=$('budgetCheck');box?.classList.remove('is-positive','is-negative');if(r.budget>0){const diff=r.budget-r.monthly;text('budgetDifference',diff>=0?`Zbývá ${money(diff)}`:`Chybí ${money(-diff)}`);text('budgetMessage',diff>=0?'Měsíční limit pokrývá aktuální odhad.':'Aktuální odhad je nad zadaným limitem.');box?.classList.add(diff>=0?'is-positive':'is-negative')}else{text('budgetDifference','Limit nebyl zadán');text('budgetMessage','Doplňte vlastní měsíční limit pro rychlou kontrolu.')}if(r.cloth!==null){text('clothTotal',money(r.cloth));const delta=r.period-r.cloth;text('clothMessage',delta>0?`Látkový model je o ${money(delta)} nižší než jednorázový model za stejné období.`:`Látkový model je o ${money(-delta)} vyšší než jednorázový model za stejné období.`)}else{text('clothTotal','Otevřete podrobný režim');text('clothMessage','Výsledek se zobrazí po zadání výbavy a nákladů praní.')}breakdown(r);return r}
  function setMode(next){mode=next==='advanced'?'advanced':'basic';root.dataset.mode=mode;d.querySelectorAll('.mode').forEach(b=>{const a=b.dataset.mode===mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});$('advanced').hidden=mode!=='advanced';render()}
  function setStep(i){const stages=[...d.querySelectorAll('[data-stage]')],buttons=[...d.querySelectorAll('[data-step]')];step=clamp(Number(i)||0,0,stages.length-1);stages.forEach((s,j)=>s.hidden=j!==step);buttons.forEach((b,j)=>b.classList.toggle('active',j===step));$('prev').disabled=step===0;$('next').disabled=step===stages.length-1;text('stepStatus',`Krok ${step+1} ze ${stages.length}`);$('next').textContent=step===stages.length-1?'Všechny kroky hotové':'Další krok →'}
  function share(){const u=new URL(location.href);u.search='';numeric.forEach(id=>u.searchParams.set(id,String(read(id))));u.searchParams.set('rezim',mode);return u.toString()}
  function load(){const p=new URLSearchParams(location.search);numeric.forEach(id=>{if(p.has(id)&&$(id)){$(id).value=p.get(id);fmtInput(id)}});setMode(p.get('rezim')==='advanced'?'advanced':'basic')}
  async function copy(v,msg){try{await navigator.clipboard.writeText(v);text('copyStatus',msg)}catch{const ta=d.createElement('textarea');ta.value=v;d.body.append(ta);ta.select();d.execCommand('copy');ta.remove();text('copyStatus',msg)}}
  function resultText(){if(!last)return'';return [`Kalkulačka nákladů na pleny – RychléVýpočty.cz`,`Režim: ${last.mode==='advanced'?'podrobný':'rychlý'}`,`Cena za kus: ${num(last.piece)} Kč`,`Pleny měsíčně: ${money(last.diaper)}`,`Doplňky měsíčně: ${money(last.extras)}`,`Celkem měsíčně: ${money(last.monthly)}`,`Za ${num(last.months)} měsíců: ${money(last.period)}`,'Výsledek je orientační finanční model.'].join('\n')}
  function reset(){form.reset();numeric.forEach(fmtInput);setStep(0);setMode('basic');text('copyStatus','')}
  form.addEventListener('submit',e=>{e.preventDefault();render()});numeric.forEach(id=>{const el=$(id);if(!el)return;el.addEventListener('input',render);el.addEventListener('change',render);el.addEventListener('blur',()=>{fmtInput(id);render()})});d.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));d.querySelectorAll('.step').forEach(b=>b.addEventListener('click',()=>setStep(b.dataset.step)));$('prev')?.addEventListener('click',()=>setStep(step-1));$('next')?.addEventListener('click',()=>setStep(step+1));$('resetBtn')?.addEventListener('click',reset);$('toggleBreakdown')?.addEventListener('click',e=>{const w=$('breakdownWrap'),c=w.classList.toggle('is-collapsed');e.currentTarget.setAttribute('aria-expanded',String(!c));e.currentTarget.textContent=c?'Zobrazit rozpad':'Skrýt rozpad'});$('copyResult')?.addEventListener('click',()=>copy(resultText(),'Výsledek byl zkopírován.'));$('copyLink')?.addEventListener('click',()=>copy(share(),'Odkaz s nastavením byl zkopírován.'));
  numeric.forEach(fmtInput);setStep(0);load();render();
})();
