(function(){
  const form=document.getElementById('loanForm');if(!form)return;
  const resetBtn=document.getElementById('resetBtn');
  const presetButtons=Array.from(document.querySelectorAll('.scenario-chip'));
  const $=id=>document.getElementById(id);
  const outputs={monthlyPayment:$('monthlyPayment'),monthlyWithFees:$('monthlyWithFees'),totalPaid:$('totalPaid'),totalOverpayment:$('totalOverpayment'),summaryLoan:$('summaryLoan'),summaryYears:$('summaryYears'),summaryRate:$('summaryRate'),summaryInstallments:$('summaryInstallments'),neededIncome:$('neededIncome'),neededIncomeKpi:$('neededIncomeKpi'),monthlyWithFeesDetail:$('monthlyWithFeesDetail'),summaryInstallmentsCompact:$('summaryInstallmentsCompact'),loanBadge:$('loanBadge'),scheduleBody:$('scheduleBody'),affordabilityStatus:$('affordabilityStatus'),affordabilityText:$('affordabilityText'),actionStatus:$('actionStatus'),decisionSummary:$('decisionSummary'),nextActionText:$('nextActionText'),primaryNextCta:$('primaryNextCta'),secondaryNextCta:$('secondaryNextCta'),heroMonthly:$('heroMonthly'),heroAmount:$('heroAmount'),heroPaid:$('heroPaid'),heroOverpayment:$('heroOverpayment'),heroRate:$('heroRate'),heroBarPaid:$('heroBarPaid'),heroBarOverpay:$('heroBarOverpay')};
  function formatCurrency(value){return new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(value)}
  function formatPercent(value,digits=2){return new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:0,maximumFractionDigits:digits}).format(value)+' %'}
  function pluralYears(years){return years+(years===1?' rok':(years>=2&&years<=4?' roky':' let'))}
  function getValues(){return{loanAmount:Number($('loanAmount').value),interestRate:Number($('interestRate').value),years:Number($('years').value),monthlyFee:Number($('monthlyFee').value),incomeShare:Number($('incomeShare').value)}}
  function validate(values){if(!values.loanAmount||values.loanAmount<=0)return'Zadejte platnou výši půjčky.';if(values.interestRate<0)return'Zadejte platnou úrokovou sazbu.';if(!values.years||values.years<=0)return'Zadejte platnou dobu splácení.';if(!values.incomeShare||values.incomeShare<=0)return'Zadejte platný podíl splátky na příjmu.';return''}
  function calculateLoan(values){const months=values.years*12;const monthlyRate=values.interestRate/100/12;let monthlyPayment=0;if(monthlyRate===0){monthlyPayment=values.loanAmount/months}else{monthlyPayment=values.loanAmount*(monthlyRate*Math.pow(1+monthlyRate,months))/(Math.pow(1+monthlyRate,months)-1)}const totalPaidWithoutFees=monthlyPayment*months;const totalFees=values.monthlyFee*months;const totalPaid=totalPaidWithoutFees+totalFees;const totalOverpayment=totalPaid-values.loanAmount;const monthlyWithFees=monthlyPayment+values.monthlyFee;const neededIncome=monthlyWithFees/(values.incomeShare/100);const overpaymentRatio=values.loanAmount>0?(totalOverpayment/values.loanAmount)*100:0;return{months,monthlyPayment,monthlyWithFees,totalPaid,totalOverpayment,neededIncome,overpaymentRatio}}
  function buildSchedule(values,monthlyPayment,months){const monthlyRate=values.interestRate/100/12;let balance=values.loanAmount;const rows=[];for(let i=1;i<=months;i++){const interestPart=monthlyRate===0?0:balance*monthlyRate;const principalPart=monthlyPayment-interestPart;balance=Math.max(0,balance-principalPart);rows.push({month:i,payment:monthlyPayment,interest:interestPart,principal:principalPart,balance})}const preview=rows.slice(0,4);if(rows.length>8)preview.push({separator:true});return preview.concat(rows.slice(-4))}
  function renderSchedule(schedule){if(!schedule.length){outputs.scheduleBody.innerHTML='<tr><td colspan="5">Po zadání údajů se zobrazí orientační přehled splátek.</td></tr>';return}outputs.scheduleBody.innerHTML=schedule.map(row=>row.separator?'<tr><td colspan="5">…</td></tr>':'<tr><td>'+row.month+'.</td><td>'+formatCurrency(row.payment)+'</td><td>'+formatCurrency(row.interest)+'</td><td>'+formatCurrency(row.principal)+'</td><td>'+formatCurrency(row.balance)+'</td></tr>').join('')}
  function getAffordabilityMessage(result){const monthlyLoadRatio=result.monthlyWithFees/result.neededIncome*100;const overpay=result.overpaymentRatio;let data={statusClass:'caution',statusLabel:'Na hraně',statusText:'Splátka může být zvládnutelná, ale je dobré počítat i s rezervou pro ostatní měsíční výdaje.',actionLabel:'Další krok',summaryText:'Dává smysl porovnat více scénářů: jinou dobu splácení, nižší částku nebo ověření vůči čistému příjmu.',nextActionText:'Pokud výsledek vychází těsně, zkuste nižší částku, jinou dobu splácení nebo výsledek porovnejte s čistou mzdou.',primaryHref:'/cista-mzda-kalkulacka.html',primaryText:'Porovnat s příjmem',secondaryHref:'/finance-a-hypoteky.html',secondaryText:'Další scénáře'};if(monthlyLoadRatio<=30&&overpay<=25){data={statusClass:'safe',statusLabel:'Spíše bezpečné',statusText:'Při těchto hodnotách působí splátka relativně rozumně, pokud máte stabilní příjem a rezervu.',actionLabel:'Dobrá pozice',summaryText:'Výsledek vypadá relativně zdravě. Další krok je porovnat varianty a nebrat první scénář jako jediný.',nextActionText:'Jste ve slušné pozici. Teď má smysl porovnat alternativy a ověřit, jestli kratší splatnost nezlepší celkovou cenu.',primaryHref:'/kalkulacka-slozeneho-uroku.html',primaryText:'Porovnat alternativu',secondaryHref:'/finance-a-hypoteky.html',secondaryText:'Projít další scénáře'}}else if(monthlyLoadRatio>35||overpay>50){data={statusClass:'risk',statusLabel:'Rizikovější varianta',statusText:'Vyšší potřebný příjem nebo vysoké přeplacení naznačují větší tlak na rozpočet i dražší celkový scénář.',actionLabel:'Pozor',summaryText:'Tento scénář je citlivější na výpadek příjmu a další výdaje. Vyplatí se přepočítat nižší částku nebo jinou dobu splácení.',nextActionText:'Největší páka bývá nižší půjčka, rozumnější doba splácení a reálné ověření, jestli splátka sedí k čistému příjmu.',primaryHref:'/cista-mzda-kalkulacka.html',primaryText:'Ověřit podle čisté mzdy',secondaryHref:'/kalkulacka-slozeneho-uroku.html',secondaryText:'Porovnat alternativu'}}return data}
  function render(values,result){outputs.monthlyPayment.textContent=formatCurrency(result.monthlyPayment);outputs.monthlyWithFees.textContent=formatCurrency(result.monthlyWithFees);outputs.monthlyWithFeesDetail.textContent=formatCurrency(result.monthlyWithFees);outputs.neededIncomeKpi.textContent=formatCurrency(result.neededIncome);outputs.totalPaid.textContent=formatCurrency(result.totalPaid);outputs.totalOverpayment.textContent=formatCurrency(result.totalOverpayment);outputs.summaryLoan.textContent=formatCurrency(values.loanAmount);outputs.summaryYears.textContent=pluralYears(values.years);outputs.summaryRate.textContent=formatPercent(values.interestRate);outputs.summaryInstallments.textContent=String(result.months);outputs.summaryInstallmentsCompact.textContent=String(result.months);outputs.neededIncome.textContent=formatCurrency(result.neededIncome);if(result.overpaymentRatio<=20){outputs.loanBadge.className='badge success';outputs.loanBadge.textContent='Zatížení rozpočtu: nižší'}else if(result.overpaymentRatio<=50){outputs.loanBadge.className='badge warning';outputs.loanBadge.textContent='Zatížení rozpočtu: střední'}else{outputs.loanBadge.className='badge risk';outputs.loanBadge.textContent='Zatížení rozpočtu: vyšší'}const affordability=getAffordabilityMessage(result);outputs.affordabilityStatus.textContent=affordability.statusLabel;outputs.affordabilityStatus.className='decision-status '+affordability.statusClass;outputs.affordabilityText.textContent=affordability.statusText;outputs.actionStatus.textContent=affordability.actionLabel;outputs.actionStatus.className='decision-status '+affordability.statusClass;outputs.decisionSummary.textContent=affordability.summaryText;outputs.nextActionText.textContent=affordability.nextActionText;outputs.primaryNextCta.href=affordability.primaryHref;outputs.primaryNextCta.textContent=affordability.primaryText;outputs.secondaryNextCta.href=affordability.secondaryHref;outputs.secondaryNextCta.textContent=affordability.secondaryText;outputs.heroMonthly.textContent=formatCurrency(result.monthlyWithFees);outputs.heroAmount.textContent=formatCurrency(values.loanAmount);outputs.heroPaid.textContent=formatCurrency(result.totalPaid);outputs.heroOverpayment.textContent=formatCurrency(result.totalOverpayment);outputs.heroRate.textContent=formatPercent(values.interestRate,1)+' na '+pluralYears(values.years);outputs.heroBarPaid.style.width=Math.min(100,Math.max(12,values.loanAmount/result.totalPaid*100))+'%';outputs.heroBarOverpay.style.width=Math.min(100,Math.max(12,result.totalOverpayment/result.totalPaid*100))+'%';renderSchedule(buildSchedule(values,result.monthlyPayment,result.months))}
  function runCalculation(){const values=getValues();const error=validate(values);if(error){window.alert(error);return}render(values,calculateLoan(values))}
  function setPreset(name){const presets={standard:{loanAmount:250000,interestRate:7.9,years:5,monthlyFee:0,incomeShare:30},safe:{loanAmount:180000,interestRate:7.9,years:4,monthlyFee:0,incomeShare:25},'higher-loan':{loanAmount:400000,interestRate:8.9,years:7,monthlyFee:0,incomeShare:30},shorter:{loanAmount:250000,interestRate:7.9,years:3,monthlyFee:0,incomeShare:30}};const preset=presets[name];if(!preset)return;Object.keys(preset).forEach(key=>{$(key).value=preset[key]});presetButtons.forEach(btn=>{const active=btn.dataset.preset===name;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active?'true':'false')});runCalculation()}
  form.addEventListener('submit',e=>{e.preventDefault();runCalculation()});['loanAmount','interestRate','years','monthlyFee','incomeShare'].forEach(id=>{$(id).addEventListener('input',runCalculation);$(id).addEventListener('change',runCalculation)});presetButtons.forEach(btn=>btn.addEventListener('click',()=>setPreset(btn.dataset.preset)));resetBtn.addEventListener('click',()=>setPreset('standard'));runCalculation();
})();
