(() => {
'use strict';
const $=id=>document.getElementById(id), form=$('loanForm'); if(!form)return;
const f={amount:$('amount'),rate:$('rate'),years:$('years'),upfront:$('upfront'),monthlyFee:$('monthlyFee'),insurance:$('insurance'),extra:$('extra')};
const moneyFmt=new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}), numFmt=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2});
const parse=v=>{const n=Number(String(v??'').trim().replace(/\s+/g,'').replace(',','.').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:NaN};
const money=n=>moneyFmt.format(Math.round(Number.isFinite(n)?n:0)), pct=n=>`${numFmt.format(Number.isFinite(n)?n:0)} %`, set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
function annuity(P,annual,n){const r=annual/1200;if(n<=0)return NaN;if(Math.abs(r)<1e-12)return P/n;return P*r/(1-Math.pow(1+r,-n))}
function apr(P,upfront,monthly,n){const net=P-upfront;if(net<=0||monthly<=0||n<=0)return NaN;const pv=r=>Math.abs(r)<1e-12?monthly*n:monthly*(1-Math.pow(1+r,-n))/r;if(pv(0)<net)return 0;let lo=0,hi=1;for(let i=0;i<140;i++){const mid=(lo+hi)/2;if(pv(mid)>net)lo=mid;else hi=mid}return (Math.pow(1+(lo+hi)/2,12)-1)*100}
function simulate(P,annual,base,monthlyCosts,extra,max=1200){const r=annual/1200;let bal=P,interest=0,paid=0,m=0,firstInterest=0,firstPrincipal=0,rows=[];while(bal>.005&&m<max){m++;const i=bal*r;const planned=Math.max(0,base-i);const p=Math.min(bal,planned+extra);if(m===1){firstInterest=i;firstPrincipal=Math.min(bal,planned)}const core=i+p;bal=Math.max(0,bal-p);interest+=i;paid+=core+monthlyCosts;if(m<=12||m%12===0)rows.push({m,balance:bal,interest:i,principal:p});if(p<=0&&bal>0)break}return{months:m,interest,paid,firstInterest,firstPrincipal,rows,finished:bal<=.005}}
function values(){return Object.fromEntries(Object.entries(f).map(([k,e])=>[k,parse(e.value)]))}
function validate(d){const rules=[['amount',1000,1e8,'Výše půjčky musí být 1 000 až 100 000 000 Kč.'],['rate',0,100,'Sazba musí být 0 až 100 %.'],['years',1,40,'Doba musí být 1 až 40 celých let.'],['upfront',0,1e8,'Poplatek nesmí být záporný.'],['monthlyFee',0,1e5,'Měsíční poplatek nesmí být záporný.'],['insurance',0,1e5,'Pojištění nesmí být záporné.'],['extra',0,1e7,'Platba navíc nesmí být záporná.']];let msg='';for(const [k,min,max,m] of rules){if(!Number.isFinite(d[k])||d[k]<min||d[k]>max||(k==='years'&&!Number.isInteger(d[k]))){msg=m;break}}if(!msg&&d.upfront>=d.amount)msg='Jednorázový poplatek musí být nižší než čerpaná částka.';$('formError').hidden=!msg;$('formError').textContent=msg;return !msg}
function renderAmortization(sim,P){const box=$('amortizationRows');box.replaceChildren();const points=[1,Math.max(1,Math.round(sim.months*.25)),Math.max(1,Math.round(sim.months*.5)),Math.max(1,Math.round(sim.months*.75)),sim.months];let bal=P;const d=values(),base=annuity(d.amount,d.rate,d.years*12),r=d.rate/1200;const balances={};for(let m=1;m<=sim.months;m++){const i=bal*r;const p=Math.min(bal,Math.max(0,base-i)+d.extra);bal=Math.max(0,bal-p);if(points.includes(m))balances[m]=bal}for(const m of [...new Set(points)]){const art=document.createElement('article'),s=document.createElement('span'),track=document.createElement('div'),fill=document.createElement('i'),b=document.createElement('b');s.textContent=m===1?'1. měsíc':m===sim.months?'Konec':`${m}. měsíc`;fill.style.width=`${Math.max(0,Math.min(100,(balances[m]/P)*100))}%`;b.textContent=money(balances[m]);track.append(fill);art.append(s,track,b);box.append(art)}}
function renderRateScenarios(d,monthlyCosts){const box=$('rateScenarios');box.replaceChildren();for(const delta of [-2,0,2]){const r=Math.max(0,d.rate+delta),a=annuity(d.amount,r,d.years*12),sim=simulate(d.amount,r,a,monthlyCosts,0,d.years*12+5),total=sim.paid+d.upfront,art=document.createElement('article');if(delta===0)art.className='is-current';const s=document.createElement('span'),strong=document.createElement('strong'),b=document.createElement('b');s.textContent=delta===0?'Vaše sazba':delta<0?'−2 p. b.':'+2 p. b.';strong.textContent=pct(r);b.textContent=`${money(a+monthlyCosts)} / měs. · ${money(total)} celkem`;art.append(s,strong,b);box.append(art)}}
function render(){const d=values();if(!validate(d))return;const n=d.years*12,monthlyCosts=d.monthlyFee+d.insurance,base=annuity(d.amount,d.rate,n),monthly=base+monthlyCosts,standard=simulate(d.amount,d.rate,base,monthlyCosts,0,n+5),total=standard.paid+d.upfront,fees=d.upfront+monthlyCosts*standard.months,cost=total-d.amount,modelApr=apr(d.amount,d.upfront,monthly,n),accelerated=simulate(d.amount,d.rate,base,monthlyCosts,d.extra,1200),accTotal=accelerated.paid+d.upfront,saved=Math.max(0,total-accTotal),monthsSaved=Math.max(0,n-accelerated.months);set('monthlyResult',money(monthly));set('totalResult',money(total));set('costResult',money(cost));set('aprResult',Number.isFinite(modelApr)?pct(modelApr):'—');set('answerMeta',`${standard.months} splátek · ${fees>0?'včetně zadaných poplatků':'bez poplatků'}`);set('resultBadge',fees>0||d.extra>0?'Rozšířený model':'Základní model');set('principalValue',money(d.amount));set('interestValue',money(standard.interest));set('feesValue',money(fees));
const pShare=Math.max(0,Math.min(100,d.amount/total*100)),iShare=Math.max(0,Math.min(100,standard.interest/total*100)),feeShare=Math.max(0,100-pShare-iShare);$('principalFill').style.width=pShare+'%';$('interestFill').style.width=iShare+'%';$('feeFill').style.width=feeShare+'%';$('heroPrincipal').style.width=pShare+'%';$('heroInterest').style.width=iShare+'%';$('heroFees').style.width=feeShare+'%';set('heroLoan',money(d.amount));set('heroMonthly',money(monthly));set('heroTerm',`${standard.months} měsíců`);set('heroCost',money(cost));set('heroTotal',money(total));set('heroApr',Number.isFinite(modelApr)?pct(modelApr):'—');set('firstPayment',money(base));set('firstPrincipalValue',money(standard.firstPrincipal));set('firstInterestValue',money(standard.firstInterest));const firstP=standard.firstPrincipal/base*100;$('firstPrincipalBar').style.width=Math.max(0,Math.min(100,firstP))+'%';$('firstInterestBar').style.width=Math.max(0,Math.min(100,100-firstP))+'%';
$('extraBox').hidden=!(d.extra>0);if(d.extra>0){set('extraTitle',`${monthsSaved} měsíců rychleji · úspora cca ${money(saved)}`);set('extraText',`Modelové celkové platby klesnou na ${money(accTotal)}. Skutečné podmínky předčasného splácení ověřte ve smlouvě.`)}
const cnb=7.91,delta=d.rate-cnb;set('userRateBenchmark',pct(d.rate));set('rateDelta',`${delta>=0?'+':''}${numFmt.format(delta)} p. b. proti červnu 2026`);set('benchmarkCompare',Math.abs(delta)<.15?'Vaše sazba je přibližně na průměru.':delta<0?'Vaše sazba je pod červnovým průměrem ČNB.':'Vaše sazba je nad červnovým průměrem ČNB.');renderAmortization(d.extra>0?accelerated:standard,d.amount);renderRateScenarios(d,monthlyCosts)}
Object.values(f).forEach(e=>{e.addEventListener('input',render);e.addEventListener('change',render)});form.addEventListener('submit',e=>{e.preventDefault();render();if(matchMedia('(max-width:880px)').matches)$('vysledek').scrollIntoView({behavior:'smooth',block:'start'})});$('resetBtn').addEventListener('click',()=>{f.amount.value='250 000';f.rate.value='7,9';f.years.value='5';f.upfront.value='0';f.monthlyFee.value='0';f.insurance.value='0';f.extra.value='0';$('advanced').open=false;render()});$('copyBtn').addEventListener('click',async()=>{const text=`Půjčka ${$('heroLoan').textContent}: měsíční výdaj ${$('monthlyResult').textContent}, celkem ${$('totalResult').textContent}, cena financování ${$('costResult').textContent}, modelová RPSN ${$('aprResult').textContent}.`;try{await navigator.clipboard.writeText(text);$('copyBtn').textContent='Zkopírováno';setTimeout(()=>$('copyBtn').textContent='Zkopírovat stručný výsledek',1400)}catch(_){$('copyBtn').textContent='Kopírování není dostupné'}});const menu=$('menuBtn'),mobile=$('mobile-nav');if(menu&&mobile){menu.addEventListener('click',()=>{const on=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!on));mobile.classList.toggle('is-open',!on)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');mobile.classList.remove('is-open')}})}render();
})();