(function(){
  const $=(id)=>document.getElementById(id), money=(v)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Math.max(0,v||0));
  const ids=['fuelCost','tollCost','parkingCost','peopleCount','driverDiscountEnabled','driverDiscount'];
  function v(id){const el=$(id); return el?.type==='checkbox'?el.checked:Number(el?.value)||0}
  function calcBasic(){const fuel=v('fuelCost'), toll=v('tollCost'), parking=v('parkingCost'), people=Math.max(1,v('peopleCount')), enabled=v('driverDiscountEnabled'), discount=Math.max(0,Math.min(100,v('driverDiscount'))); const total=fuel+toll+parking; const base=total/people; let driver=base, passenger=base; if(enabled&&people>1){driver=base*(1-discount/100); passenger=(total-driver)/(people-1)} return {fuel,toll,parking,people,total,base,driver,passenger,enabled,discount};}
  function renderBasic(){const r=calcBasic(); $('totalCostResult').textContent=money(r.total); $('standardShareResult').textContent=money(r.base); $('driverShareResult').textContent=money(r.driver); $('passengerShareResult').textContent=money(r.passenger); $('fuelCostResult').textContent=money(r.fuel); $('tollCostResult').textContent=money(r.toll); $('parkingCostResult').textContent=money(r.parking); $('peopleCountResult').textContent=String(r.people); $('resultBadge').textContent=r.enabled&&r.people>1?'Řidič má zvýhodněný podíl':'Rovnoměrné rozdělení'; $('resultNote').textContent=r.enabled&&r.people>1?`Řidič platí přibližně ${money(r.driver)} a každý další cestující ${money(r.passenger)}.`:`Každý člověk zaplatí přibližně ${money(r.base)}.`; $('heroTotal').textContent=money(r.total); $('heroShare').textContent=money(r.base); $('heroPeople').textContent=r.people+' osoby'; $('heroFuel').style.width=Math.min(100,r.fuel/r.total*100||0)+'%'; $('heroToll').style.width=Math.min(100,r.toll/r.total*100||0)+'%'; $('heroParking').style.width=Math.min(100,r.parking/r.total*100||0)+'%'; renderTable(r);}
  function renderTable(r){$('summaryTableBody').innerHTML=[['Palivo',r.fuel,'Společné náklady na palivo'],['Mýto a poplatky',r.toll,'Dálniční poplatky, mýto nebo známka'],['Parkování a ostatní',r.parking,'Další společné výdaje'],['Celkem',r.total,'Součet pro rozdělení'],['Podíl na osobu',r.base,'Rovnoměrné dělení']].map(row=>`<tr><td>${row[0]}</td><td>${money(row[1])}</td><td>${row[2]}</td></tr>`).join('');}
  ids.forEach(id=>$(id)?.addEventListener('input',renderBasic)); ids.forEach(id=>$(id)?.addEventListener('change',renderBasic)); $('resetBtn')?.addEventListener('click',()=>{fuelCost.value=900;tollCost.value=300;parkingCost.value=150;peopleCount.value=4;driverDiscountEnabled.checked=false;driverDiscount.value=25;renderBasic()});
  renderBasic();
})();
