(() => {
'use strict';
const $=(id)=>document.getElementById(id); const $$=(sel,scope=document)=>Array.from(scope.querySelectorAll(sel));
const num=(v,f=0)=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:f};
const ceil=(v)=>Math.ceil(v-1e-9); const fmt=(v,d=1)=>new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v); const area=(v)=>`${fmt(v,2)} m²`; const metres=(v)=>`${fmt(v,1)} m`;
const boards={
 'rb1250x2600':{label:'Rigips RB (A) 12,5 · 1250×2600',type:'A',w:1.25,h:2.6,area:3.25,use:'standardní interiér · délka vhodná pro běžnou výšku místnosti',source:'https://www.rigips.cz/produkty/stavebni-deska-rb-a/'},
 'rb1250x2000':{label:'Rigips RB (A) 12,5 · 1250×2000',type:'A',w:1.25,h:2,area:2.5,use:'standardní interiér · kratší formát',source:'https://www.rigips.cz/produkty/stavebni-deska-rb-a/'},
 'rb1200x2600':{label:'Rigips RB (A) 12,5 · 1200×2600',type:'A',w:1.2,h:2.6,area:3.12,use:'standardní interiér · modul 600 mm',source:'https://www.rigips.cz/produkty/stavebni-deska-rb-a/'},
 'rb1250x3000':{label:'Rigips RB (A) 12,5 · 1250×3000',type:'A',w:1.25,h:3,area:3.75,use:'standardní interiér · delší formát',source:'https://www.rigips.cz/produkty/stavebni-deska-rb-a/'},
 'rbi1250x2600':{label:'Rigips RBI (H2) 12,5 · 1250×2600',type:'H2',w:1.25,h:2.6,area:3.25,use:'zvýšená vlhkost v přerušovaném cyklu',source:'https://www.rigips.cz/produkty/impregnovana-deska-rbi-h2/'},
 'rf1250x2600':{label:'Rigips RF (DF) 12,5 · 1250×2600',type:'DF',w:1.25,h:2.6,area:3.25,use:'součást požárně odolných systémů',source:'https://www.rigips.cz/produkty/protipozarni-deska-rf-df/'}
};
let mode='partition'; let last=null;
function optionMarkup(){return Object.entries(boards).map(([k,b])=>`<option value="${k}">${b.label}</option>`).join('')+`<option value="custom">— Vlastní deska / technický list —</option>`}
['pBoard','cBoard','lBoard'].forEach(id=>{$(id).innerHTML=optionMarkup()});
function getBoard(prefix){const key=$(prefix+'Board').value;if(key!=='custom')return boards[key];const w=Math.max(.1,num($(prefix+'BoardWidth').value)/1000),h=Math.max(.1,num($(prefix+'BoardHeight').value)/1000);return{label:($(prefix+'BoardName').value||'Vlastní deska').trim()||'Vlastní deska',type:'CUSTOM',w,h,area:w*h,use:'vlastní výrobek podle technického listu',source:'',custom:true}}
function boardCard(id,b){const source=b.custom?'':`<a href="${b.source}" target="_blank" rel="noopener noreferrer">Technický zdroj výrobce ↗</a>`;$(id).classList.toggle('is-custom',!!b.custom);$(id).innerHTML=`<strong>${b.label}</strong><p>${b.use}. Přesná plocha jedné desky: ${fmt(b.area,2)} m².</p><ul><li>${b.type}</li><li>${Math.round(b.w*1000)} × ${Math.round(b.h*1000)} mm</li><li>${fmt(b.area,2)} m² / deska</li></ul>${source}`}
function syncCustom(prefix){const custom=$(prefix+'Board').value==='custom';$(prefix+'CustomBoard').hidden=!custom}
function expectedSpacing(b){return Math.round(b.w*1000/2)}
function panelMode(next){mode=next; document.body.dataset.sdkMode=mode; const tabs=$$('[role="tab"][data-mode]'); tabs.forEach(t=>{const a=t.dataset.mode===mode;t.classList.toggle('is-active',a);t.setAttribute('aria-selected',String(a));t.tabIndex=a?0:-1}); ['partition','ceiling','lining'].forEach(m=>$(m+'Panel').hidden=m!==mode); calculate()}
function partitionLike(prefix,sides,label){const L=Math.max(.1,num($(prefix+'Length').value)),H=Math.max(.1,num($(prefix+'Height').value)),open=Math.max(0,num($(prefix+'Openings').value)),layers=Math.max(1,num($(prefix+'Layers').value,1)),reserve=Math.max(0,num($(prefix+'Reserve').value)),spacing=Math.max(.3,num($(prefix+'Spacing').value)/1000),profileLen=Math.max(1,num($(prefix+'ProfileLength').value,3)); const b=getBoard(prefix); const rawFace=Math.max(0,L*H-open); const cladding=rawFace*sides*layers; const required=cladding*(1+reserve/100); const boardCount=ceil(required/b.area); const purchased=boardCount*b.area; const studs=ceil(L/spacing)+1; const studLen=Math.max(0,H-.0125); const door=prefix==='p'?Math.min(L,Math.max(0,num($('pDoorWidth').value))):0; const trackLen=Math.max(0,2*L-door); const trackPieces=ceil(trackLen/profileLen); const studPieces=profileLen>=studLen?studs:null; const expected=expectedSpacing(b); const spacingMm=spacing*1000; const sanity=b.custom?{ok:false,text:`Vlastní deska ${Math.round(b.w*1000)} × ${Math.round(b.h*1000)} mm: geometrický modul poloviny šířky je ${expected} mm, ale systémovou vhodnost rozteče ${Math.round(spacingMm)} mm musí potvrdit dokumentace výrobce.`}:Math.abs(spacingMm-expected)<=5?{ok:true,text:`Modul ${Math.round(spacingMm)} mm odpovídá polovině šířky desky (${expected} mm).`}:{ok:false,text:`Zadaná rozteč ${Math.round(spacingMm)} mm neodpovídá běžnému modulu ${expected} mm pro desku šířky ${Math.round(b.w*1000)} mm. Ověřte systémovou dokumentaci.`}; const gap=H-b.h; let layout;if(gap<=.02){layout={ok:true,title:'Klad desek je jednodušší',text:`Délka desky ${Math.round(b.h*1000)} mm pokrývá výšku ${Math.round(H*1000)} mm po běžném zaříznutí. U svislé konstrukce tak lze omezit vodorovné spáry.`}}else if(gap>=.4){layout={ok:true,title:'Počítejte s vodorovným nastavením',text:`Deska je o ${Math.round(gap*1000)} mm kratší než konstrukce. Rigips připouští doplňky min. 400 mm a požaduje vystřídat vodorovné spáry sousedních polí alespoň o 400 mm.`}}else{layout={ok:false,title:'Zvažte delší formát desky',text:`Do výšky chybí ${Math.round(gap*1000)} mm. Takto malý doplněk je pod 400 mm — pod minimem, které Rigips uvádí pro využití zbytků při opláštění příček. Delší formát bude bezpečnější volba.`}}; return {mode,label,b,cladding,required,boardCount,purchased,leftover:purchased-required,reserve,spacingMm,studs,studLen,trackLen,trackPieces,studPieces,profileLen,sanity,layout,screw:`max. 250 mm`,lines:[['Desky',`${boardCount} ks`,`${fmt(purchased,2)} m² nakoupeno`],[label==='Příčka'?'CW stojiny':'CW stojiny',`${studs} ks`,`${fmt(studLen,2)} m / stojina`],[label==='Příčka'?'UW vedení':'UW vedení',`${trackPieces} ks × ${fmt(profileLen,1)} m`,`${fmt(trackLen,1)} m čisté délky`],['Vruty TN','ověřit systém',`max. rozteč 250 mm`]]}}
function ceiling(){const L=Math.max(.1,num($('cLength').value)),W=Math.max(.1,num($('cWidth').value)),layers=Math.max(1,num($('cLayers').value,1)),reserve=Math.max(0,num($('cReserve').value)),spacing=Math.max(.25,num($('cSpacing').value)/1000),hangerSpacing=Math.max(.4,num($('cHangerSpacing').value)/1000),profileLen=Math.max(1,num($('cProfileLength').value,3)),b=getBoard('c'); const cladding=L*W*layers,required=cladding*(1+reserve/100),boardCount=ceil(required/b.area),purchased=boardCount*b.area; const options=[{run:L,span:W},{run:W,span:L}].map(o=>{const rows=Math.max(1,ceil(o.span/spacing)-1);return {...o,rows,cd:rows*o.run,hangers:rows*Math.max(1,ceil(o.run/hangerSpacing))}}).sort((a,b)=>a.cd-b.cd); const g=options[0],ud=2*(L+W),udPieces=ceil(ud/profileLen),cdPieces=ceil(g.cd/profileLen); const ok=spacing<=.5+1e-9 && hangerSpacing<=1.2+1e-9; const sanity=ok?{ok:true,text:`Rošt respektuje pracovní limity: CD ${Math.round(spacing*1000)} mm a závěsy ${Math.round(hangerSpacing*1000)} mm.`}:{ok:false,text:`Zadaný rošt překračuje běžný limit Rigips pro přímo montovaný podhled (CD max. 500 mm, závěsy ve směru CD max. 1 200 mm).`}; const layout={ok:true,title:'Klad podhledu má vlastní pravidlo',text:`Desky se orientují délkou kolmo k montážním R-CD profilům a příčné hrany musí ležet na profilu. Počet kusů je nákupní odhad; kalkulačka neoptimalizuje mapu všech dořezů.`}; return {mode:'ceiling',label:'Podhled',b,cladding,required,boardCount,purchased,leftover:purchased-required,reserve,spacingMm:spacing*1000,sanity,layout,lines:[['Desky',`${boardCount} ks`,`${fmt(purchased,2)} m² nakoupeno`],['CD profily',`${cdPieces} ks × ${fmt(profileLen,1)} m`,`${fmt(g.cd,1)} m · ${g.rows} řad`],['UD obvod',`${udPieces} ks × ${fmt(profileLen,1)} m`,`${fmt(ud,1)} m čisté délky`],['Přímé závěsy',`≈ ${g.hangers} ks`,`pracovní síť podle max. roztečí`],['Vruty TN','ověřit systém','max. rozteč 170 mm']],module:`${Math.round(spacing*1000)} mm`}}
function calculate(){try{let r;if(mode==='partition')r=partitionLike('p',2,'Příčka');else if(mode==='lining')r=partitionLike('l',1,'Předstěna');else r=ceiling(); last=r; $('formError').hidden=true; render(r)}catch(e){$('formError').textContent=e.message||'Zkontrolujte vstupy.';$('formError').hidden=false}}
function render(r){$('resultTitle').textContent=`PLÁN NÁKUPU · ${r.label.toUpperCase()}`;const boardWord=r.boardCount===1?'deska':r.boardCount>=2&&r.boardCount<=4?'desky':'desek';$('resultPrimary').textContent=`${r.boardCount} ${boardWord}`;$('resultSub').textContent=`${fmt(r.purchased,2)} m² skutečně nakoupeno`;$('resultArea').textContent=area(r.cladding);$('resultRequired').textContent=area(r.required);$('resultLeftover').textContent=area(Math.max(0,r.leftover));$('resultModule').textContent=r.module||`${Math.round(r.spacingMm)} mm`;$('layoutBox').classList.toggle('is-warn',!r.layout.ok);$('layoutTitle').textContent=r.layout.title;$('layoutText').textContent=r.layout.text;$('resultList').innerHTML=r.lines.map(x=>`<div class="sdk-result-row"><div><strong>${x[0]}</strong><small>${x[2]}</small></div><span>${x[1]}</span></div>`).join('');$('sanityBox').classList.toggle('is-warn',!r.sanity.ok);$('sanityText').textContent=r.sanity.text; ['p','c','l'].forEach(prefix=>{const select=$(prefix+'Board');if(select){syncCustom(prefix);boardCard(prefix+'ProductCard',getBoard(prefix))}})}
function bind(){const tabs=$$('[role="tab"][data-mode]');tabs.forEach(t=>t.addEventListener('click',()=>panelMode(t.dataset.mode)));document.querySelector('.sdk-mode').addEventListener('keydown',e=>{const i=tabs.indexOf(document.activeElement);if(i<0)return;let n=i;if(['ArrowRight','ArrowDown'].includes(e.key))n=(i+1)%tabs.length;else if(['ArrowLeft','ArrowUp'].includes(e.key))n=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();panelMode(tabs[n].dataset.mode);tabs[n].focus()});$$('input,select',$('drywallPlanner')).forEach(el=>el.addEventListener('input',calculate));$('copyResult').addEventListener('click',async()=>{if(!last)return;const txt=[`${last.label}: ${last.boardCount} desek`,...last.lines.map(x=>`${x[0]}: ${x[1]} (${x[2]})`),`Klad desek: ${last.layout.text}`,`Systémová kontrola: ${last.sanity.text}`].join('\n');try{await navigator.clipboard.writeText(txt);$('copyResult').textContent='Zkopírováno';setTimeout(()=>$('copyResult').textContent='Kopírovat plán',1200)}catch{}});$('printResult').addEventListener('click',()=>window.print());const menu=$('menuToggle'),nav=$('mobileNav');menu.addEventListener('click',()=>{const o=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!o));menu.setAttribute('aria-label',o?'Otevřít navigaci':'Zavřít navigaci');nav.classList.toggle('is-open',!o)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Otevřít navigaci');nav.classList.remove('is-open')}})}
bind();calculate();
})();