(()=>{"use strict";
const $=id=>document.getElementById(id);
const form=$("compoundForm");
if(!form)return;
const ids=["initialDeposit","monthlyContribution","annualRate","years","contributionGrowth","targetAmount","entryFee","annualFee","inflationRate"];
const money0=new Intl.NumberFormat("cs-CZ",{style:"currency",currency:"CZK",maximumFractionDigits:0});
const number2=new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:2});
const compactMoney=new Intl.NumberFormat("cs-CZ",{style:"currency",currency:"CZK",notation:"compact",maximumFractionDigits:2});
const money=v=>money0.format(Number.isFinite(v)?v:0);
const compact=v=>compactMoney.format(Number.isFinite(v)?v:0);
const pct=v=>`${number2.format(Number.isFinite(v)?v:0)} %`;
const set=(id,value)=>{const el=$(id);if(el)el.textContent=value};
const parseLocale=value=>{const raw=String(value??"").trim().replace(/[\s\u00a0]/g,"").replace(/,/g,".");if(raw==="")return NaN;const num=Number(raw);return Number.isFinite(num)?num:NaN};
const formatInput=(id,digits=0)=>{const el=$(id);const value=parseLocale(el.value);if(!Number.isFinite(value))return;el.value=new Intl.NumberFormat("cs-CZ",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)};
const read=()=>({initialDeposit:parseLocale($("initialDeposit").value),monthlyContribution:parseLocale($("monthlyContribution").value),annualRate:parseLocale($("annualRate").value),years:parseLocale($("years").value),contributionGrowth:parseLocale($("contributionGrowth").value),targetAmount:parseLocale($("targetAmount").value),entryFee:parseLocale($("entryFee").value),annualFee:parseLocale($("annualFee").value),inflationRate:parseLocale($("inflationRate").value),contributionTiming:$("contributionTiming").value});
const limits={initialDeposit:[0,1e12],monthlyContribution:[0,1e9],annualRate:[-99,100],years:[1,80],contributionGrowth:[-20,30],targetAmount:[0,1e13],entryFee:[0,30],annualFee:[0,20],inflationRate:[0,30]};
function clearErrors(){ids.forEach(id=>{const field=$(id)?.closest(".field");if(field)field.classList.remove("has-error");set(`${id}Error`,"")});$("formMessage").hidden=true;$("formMessage").textContent=""}
function markError(id,message){const field=$(id)?.closest(".field");if(field)field.classList.add("has-error");set(`${id}Error`,message)}
function validate(v){clearErrors();let first=null;const errors=[];const check=(id,condition,message)=>{if(condition){markError(id,message);errors.push(message);if(!first)first=$(id)}};check("initialDeposit",!Number.isFinite(v.initialDeposit)||v.initialDeposit<limits.initialDeposit[0]||v.initialDeposit>limits.initialDeposit[1],"Zadejte částku od 0 do 1 bilionu Kč.");check("monthlyContribution",!Number.isFinite(v.monthlyContribution)||v.monthlyContribution<limits.monthlyContribution[0]||v.monthlyContribution>limits.monthlyContribution[1],"Zadejte částku od 0 do 1 miliardy Kč.");if(Number.isFinite(v.initialDeposit)&&Number.isFinite(v.monthlyContribution)&&v.initialDeposit+v.monthlyContribution<=0){markError("initialDeposit","Alespoň jeden vklad musí být vyšší než nula.");markError("monthlyContribution","Alespoň jeden vklad musí být vyšší než nula.");errors.push("Zadejte počáteční nebo měsíční vklad vyšší než nula.");if(!first)first=$("initialDeposit")};check("annualRate",!Number.isFinite(v.annualRate)||v.annualRate<=-100||v.annualRate>100,"Zadejte sazbu vyšší než −100 % a nejvýše 100 %.");check("years",!Number.isFinite(v.years)||!Number.isInteger(v.years)||v.years<1||v.years>80,"Zadejte celé číslo od 1 do 80 let.");check("contributionGrowth",!Number.isFinite(v.contributionGrowth)||v.contributionGrowth<-20||v.contributionGrowth>30,"Zadejte změnu od −20 % do 30 % ročně.");check("targetAmount",!Number.isFinite(v.targetAmount)||v.targetAmount<0||v.targetAmount>1e13,"Zadejte cíl od 0 do 10 bilionů Kč.");check("entryFee",!Number.isFinite(v.entryFee)||v.entryFee<0||v.entryFee>30,"Zadejte poplatek od 0 do 30 %.");check("annualFee",!Number.isFinite(v.annualFee)||v.annualFee<0||v.annualFee>20,"Zadejte poplatek od 0 do 20 % ročně.");check("inflationRate",!Number.isFinite(v.inflationRate)||v.inflationRate<0||v.inflationRate>30,"Zadejte inflaci od 0 do 30 % ročně.");if(errors.length){$("formMessage").hidden=false;$("formMessage").textContent="Opravte označené hodnoty. Výsledek se zobrazí až po platném zadání.";return{valid:false,first}}return{valid:true,first:null}}
function simulate(v,rateOverride=v.annualRate,monthlyOverride=v.monthlyContribution,ignoreFees=false){const months=v.years*12;const grossMonthly=Math.pow(1+rateOverride/100,1/12)-1;const feeMonthly=ignoreFees?0:Math.pow(1+v.annualFee/100,1/12)-1;const entryMultiplier=ignoreFees?1:1-v.entryFee/100;let balance=v.initialDeposit*entryMultiplier;let grossDeposits=v.initialDeposit;let netDeposits=v.initialDeposit*entryMultiplier;let reachedMonth=v.targetAmount>0&&balance>=v.targetAmount?0:null;const yearly=[{year:0,balance,grossDeposits,realValue:balance}];for(let month=1;month<=months;month++){const yearIndex=Math.floor((month-1)/12);const monthlyContribution=monthlyOverride*Math.pow(1+v.contributionGrowth/100,yearIndex);const netContribution=monthlyContribution*entryMultiplier;if(v.contributionTiming==="beginning"){balance+=netContribution;grossDeposits+=monthlyContribution;netDeposits+=netContribution}balance*=1+grossMonthly;balance/=1+feeMonthly;if(v.contributionTiming==="end"){balance+=netContribution;grossDeposits+=monthlyContribution;netDeposits+=netContribution}if(reachedMonth===null&&v.targetAmount>0&&balance>=v.targetAmount)reachedMonth=month;if(month%12===0){const year=month/12;yearly.push({year,balance,grossDeposits,realValue:balance/Math.pow(1+v.inflationRate/100,year)})}}const realValue=balance/Math.pow(1+v.inflationRate/100,v.years);return{...v,rateOverride,monthlyOverride,months,grossMonthly,feeMonthly,balance,grossDeposits,netDeposits,profit:balance-grossDeposits,realValue,reachedMonth,yearly}}
function requiredMonthly(v){if(v.targetAmount<=0)return null;const initialOnly=simulate(v,v.annualRate,0).balance;if(initialOnly>=v.targetAmount)return 0;let low=0,high=Math.max(v.monthlyContribution,100);let guard=0;while(simulate(v,v.annualRate,high).balance<v.targetAmount&&high<1e9&&guard<80){high*=2;guard++}if(high>=1e9&&simulate(v,v.annualRate,high).balance<v.targetAmount)return null;for(let i=0;i<70;i++){const mid=(low+high)/2;if(simulate(v,v.annualRate,mid).balance>=v.targetAmount)high=mid;else low=mid}return high}
function pathFor(points,x0,y0,width,height,maxValue,key){if(!points.length||!Number.isFinite(maxValue)||maxValue<=0)return"";return points.map((p,i)=>{const x=x0+(points.length===1?0:i/(points.length-1)*width);const y=y0+height-(Math.max(0,p[key])/maxValue*height);return`${i===0?"M":"L"}${x.toFixed(2)} ${y.toFixed(2)}`}).join(" ")}
function areaPath(linePath,xStart,xEnd,yBase){return linePath?`${linePath} L${xEnd} ${yBase} L${xStart} ${yBase} Z`:""}
function renderHeroChart(result){const points=result.yearly;const max=Math.max(...points.map(p=>p.balance),1);const line=pathFor(points,0,12,520,128,max,"balance");$("heroLinePath").setAttribute("d",line);$("heroAreaPath").setAttribute("d",areaPath(line,0,520,150));set("heroStart",compact(result.netDeposits>0?result.netDeposits:result.initialDeposit));set("heroEnd",compact(result.balance))}
function renderChart(result){const points=result.yearly;const max=Math.max(...points.map(p=>Math.max(p.balance,p.grossDeposits)),1);const valueLine=pathFor(points,36,18,584,196,max,"balance");const depositLine=pathFor(points,36,18,584,196,max,"grossDeposits");$("valueLinePath").setAttribute("d",valueLine);$("depositLinePath").setAttribute("d",depositLine);$("valueAreaPath").setAttribute("d",areaPath(valueLine,36,620,214));$("depositAreaPath").setAttribute("d",areaPath(depositLine,36,620,214));const g=$("chartLabels");g.replaceChildren();const labelYears=[0,Math.round(result.years/2),result.years].filter((v,i,a)=>a.indexOf(v)===i);labelYears.forEach(year=>{const text=document.createElementNS("http://www.w3.org/2000/svg","text");const x=36+(result.years===0?0:year/result.years*584);text.setAttribute("x",String(x));text.setAttribute("y","236");text.setAttribute("text-anchor",year===0?"start":year===result.years?"end":"middle");text.setAttribute("class","chart-year-label");text.textContent=year===0?"dnes":`${year}. rok`;g.append(text)});set("chartCaption",`${result.years}letý horizont`);$("growthChartDesc").textContent=`Hodnota investice roste z ${money(result.yearly[0].balance)} na ${money(result.balance)}. Vlastní vklady dosáhnou ${money(result.grossDeposits)}.`}
function renderMilestones(result){const wanted=new Set([1,5,10,15,20,25,30,40,50,60,70,80,result.years].filter(y=>y<=result.years));if(result.years<=8)for(let y=1;y<=result.years;y++)wanted.add(y);const rows=result.yearly.filter(row=>wanted.has(row.year));const box=$("milestoneRows");box.replaceChildren();rows.forEach(row=>{const div=document.createElement("div");div.className="milestone-row";const span=document.createElement("span");span.textContent=`${row.year}. rok · vloženo ${money(row.grossDeposits)}`;const strong=document.createElement("strong");strong.textContent=money(row.balance);div.append(span,strong);box.append(div)})}
function renderScenarios(v){const items=[{key:"low",label:"Opatrný",rate:Math.max(-99,v.annualRate-2)},{key:"base",label:"Základní",rate:v.annualRate},{key:"high",label:"Vyšší",rate:Math.min(100,v.annualRate+2)}].map(item=>({...item,result:simulate(v,item.rate)}));items.forEach(item=>{const cap=item.key.charAt(0).toUpperCase()+item.key.slice(1);set(`scenario${cap}Rate`,`${number2.format(item.rate)} % p. a.`);set(`scenario${cap}Value`,compact(item.result.balance))});const body=$("scenarioTableBody");body.replaceChildren();items.forEach(item=>{const tr=document.createElement("tr");if(item.key==="base")tr.className="is-base";[`${item.label} · ${number2.format(item.rate)} %`,money(item.result.balance),money(item.result.grossDeposits),money(item.result.profit),money(item.result.realValue)].forEach(value=>{const td=document.createElement("td");td.textContent=value;tr.append(td)});body.append(tr)})}
function goalInsight(v,result,required){if(v.targetAmount<=0)return{badge:"Cíl není zadaný",title:"Výsledek čtěte jako otevřený scénář",text:"V pokročilém režimu můžete doplnit cílovou částku a kalkulačka porovná termín i potřebný měsíční vklad."};if(result.balance>=v.targetAmount){const when=result.reachedMonth===0?"už na začátku":result.reachedMonth!==null?`přibližně za ${Math.ceil(result.reachedMonth/12)} let`:"v zadaném horizontu";return{badge:"Cíl dosažen",title:`Rezerva nad cílem je ${money(result.balance-v.targetAmount)}`,text:`Cílovou částku ${money(v.targetAmount)} model dosáhne ${when}. Opatrný scénář ověřte snížením očekávaného výnosu.`}}const gap=v.targetAmount-result.balance;if(required===null)return{badge:"Cíl je mimo rozsah modelu",title:`K cíli chybí ${money(gap)}`,text:"Zadaný cíl vyžaduje mimořádně vysoký vklad. Zvažte delší horizont, nižší cíl nebo realističtější kombinaci obou."};return{badge:"Cíl zatím nevychází",title:`K cíli chybí ${money(gap)}`,text:`Při stejných předpokladech vychází potřebný měsíční vklad přibližně na ${money(required)}.`}}
function render(v,result){const noFee=simulate(v,v.annualRate,v.monthlyContribution,true);const feeDrag=Math.max(0,noFee.balance-result.balance);const required=requiredMonthly(v);const netAnnual=((1+v.annualRate/100)/(1+v.annualFee/100)-1)*100;const profitPositive=Math.max(0,result.profit);const depositShare=result.balance>0?Math.min(100,Math.max(0,result.grossDeposits/result.balance*100)):100;const profitShare=result.balance>0?Math.min(100,Math.max(0,profitPositive/result.balance*100)):0;set("finalValue",money(result.balance));set("totalDeposits",money(result.grossDeposits));set("netProfit",money(result.profit));set("realValue",money(result.realValue));set("feeDrag",money(feeDrag));set("depositDetail",v.contributionGrowth===0?"součet všech hrubých vkladů":`vklad roste o ${pct(v.contributionGrowth)} ročně`);set("profitDetail",result.profit>=0?"po zadaných poplatcích":"výsledek je pod vlastními vklady");set("realDetail",`při inflaci ${pct(v.inflationRate)}`);set("feeDetail",v.entryFee===0&&v.annualFee===0?"ve scénáři nejsou zadané poplatky":"přímé náklady i ztracený výnos");set("resultSentence",`${v.years} let · hrubý scénář ${pct(v.annualRate)} · efektivně po průběžném poplatku přibližně ${pct(netAnnual)} ročně.`);set("profitShare",result.profit>=0?`${number2.format(profitShare)} % výnos`:`výnos je záporný`);$("depositShareBar").style.width=`${depositShare}%`;$("profitShareBar").style.width=`${profitShare}%`;const goal=goalInsight(v,result,required);set("goalBadge",goal.badge);set("goalTitle",goal.title);set("goalText",goal.text);set("heroFinal",compact(result.balance));set("heroYears",`za ${v.years} let`);set("heroInvested",compact(result.grossDeposits));set("heroProfit",compact(result.profit));set("heroReal",compact(result.realValue));set("heroNote",`Model používá zhodnocení ${pct(v.annualRate)} ročně, vklad ${money(v.monthlyContribution)} měsíčně, poplatek ${pct(v.annualFee)} a inflaci ${pct(v.inflationRate)}.`);set("leverTime",`${v.years} ${v.years===1?"rok":v.years>=2&&v.years<=4?"roky":"let"}`);set("leverContribution",`${money(v.monthlyContribution)} měsíčně`);set("leverRate",`${pct(netAnnual)} p. a.`);set("leverReal",result.balance>0?`${number2.format(result.realValue/result.balance*100)} % nominálu`:"—");set("resultStatus","Scénář přepočítán");renderHeroChart(result);renderChart(result);renderMilestones(result);renderScenarios(v)}
function update(options={}){const v=read();const check=validate(v);if(!check.valid){set("resultStatus","Opravte zadání");return false}const result=simulate(v);if(!Number.isFinite(result.balance)||!Number.isFinite(result.realValue)){$("formMessage").hidden=false;$("formMessage").textContent="Zadaná kombinace vytváří příliš vysoké hodnoty. Snižte částku, sazbu nebo horizont.";set("resultStatus","Výsledek mimo rozsah");return false}render(v,result);if(options.scroll&&matchMedia("(max-width: 720px)").matches)$("vysledek").scrollIntoView({behavior:"smooth",block:"start"});return true}
function setMode(mode){const advanced=mode==="advanced";document.querySelectorAll("[data-mode]").forEach(button=>{const active=button.dataset.mode===mode;button.classList.toggle("is-active",active);button.setAttribute("aria-pressed",String(active))});$("advancedPanel").classList.toggle("is-hidden",!advanced);$("advancedPanel").setAttribute("aria-hidden",String(!advanced))}
document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>setMode(button.dataset.mode)));
form.addEventListener("submit",event=>{event.preventDefault();update({scroll:true})});
ids.forEach(id=>{const el=$(id);el.addEventListener("input",()=>update());el.addEventListener("change",()=>{update();if(["initialDeposit","monthlyContribution","targetAmount","years"].includes(id))formatInput(id,0)})});
$("contributionTiming").addEventListener("change",()=>update());
$("resetButton").addEventListener("click",()=>{form.reset();setMode("basic");["initialDeposit","monthlyContribution","targetAmount","years"].forEach(id=>formatInput(id,0));update()});
["initialDeposit","monthlyContribution","targetAmount","years"].forEach(id=>$(id).addEventListener("blur",()=>formatInput(id,0)));
update();
})();
