(() => {
'use strict';
const PRESETS={mix032:{name:'Štěrkodrť 0/32',short:'0/32',density:1.75,compaction:1.15,price:650,reserve:5},mix063:{name:'Štěrkodrť 0/63',short:'0/63',density:1.80,compaction:1.18,price:620,reserve:5},gravel48:{name:'Kamenivo 4/8',short:'4/8',density:1.55,compaction:1.08,price:850,reserve:5},gravel816:{name:'Kamenivo 8/16',short:'8/16',density:1.55,compaction:1.07,price:900,reserve:5},gravel1632:{name:'Kamenivo 16/32',short:'16/32',density:1.50,compaction:1.05,price:880,reserve:5},sand04:{name:'Písek / drť 0/4',short:'0/4',density:1.65,compaction:1.12,price:600,reserve:5},decorative:{name:'Okrasné kamenivo',short:'okrasné',density:1.55,compaction:1.03,price:2500,reserve:8}};
const PURPOSES={driveway:{material:'mix032',thickness:15,label:'příjezdová cesta'},paving:{material:'mix032',thickness:12,label:'pod dlažbu'},drainage:{material:'gravel1632',thickness:30,label:'drenáž a obsyp'},decorative:{material:'decorative',thickness:5,label:'okrasná plocha'}};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const num=(id,f=0)=>{const e=typeof id==='string'?document.getElementById(id):id;if(!e)return f;const v=Number(String(e.value).replace(',','.'));return Number.isFinite(v)?v:f};
const fmt=(v,d=0)=>new Intl.NumberFormat('cs-CZ',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number.isFinite(v)?v:0);
const money=v=>`${fmt(Math.round(v))} Kč`,area=v=>`${fmt(v,1)} m²`,vol=v=>`${fmt(v,2)} m³`,weight=v=>v>=1000?`${fmt(v/1000,2)} t`:`${fmt(v)} kg`;
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let mode='basic',layers=[],counter=0,last=null;
const form=$('#gravelForm'),layerList=$('#layerList');
function presetOptions(sel){return Object.entries(PRESETS).map(([k,p])=>`<option value="${k}"${k===sel?' selected':''}>${esc(p.name)}</option>`).join('')}
function addLayer(data={}){counter++;const key=PRESETS[data.material]?data.material:'mix032',p=PRESETS[key];layers.push({id:`layer-${counter}`,name:data.name||`Vrstva ${counter}`,length:data.length??8,width:data.width??3,area:data.area??24,useArea:data.useArea??false,thickness:data.thickness??15,count:data.count??1,material:key,density:data.density??p.density,compaction:data.compaction??p.compaction,reserve:data.reserve??p.reserve,price:data.price??p.price});renderLayers();calculate()}
function layerTemplate(l,i){return `<article class="layer-card" data-layer-id="${l.id}"><div class="layer-head"><div class="layer-title"><span class="layer-index">${String(i+1).padStart(2,'0')}</span><input class="layer-name" type="text" value="${esc(l.name)}" aria-label="Název vrstvy"></div>${layers.length>1?'<button type="button" class="remove-layer">Odebrat</button>':''}</div><div class="layer-grid"><label class="layer-field layer-field-wide"><span>Materiál / frakce</span><select class="layer-material">${presetOptions(l.material)}</select></label><label class="layer-field"><span>Délka</span><input class="layer-length" type="number" min="0.1" step="0.1" value="${l.length}"><small>m</small></label><label class="layer-field"><span>Šířka</span><input class="layer-width" type="number" min="0.1" step="0.1" value="${l.width}"><small>m</small></label><label class="layer-field"><span>Tloušťka</span><input class="layer-thickness" type="number" min="1" step="1" value="${l.thickness}"><small>cm po zhutnění</small></label><label class="layer-field"><span>Počet stejných ploch</span><input class="layer-count" type="number" min="1" step="1" value="${l.count}"><small>opakování</small></label><label class="layer-field"><span>Rezerva</span><input class="layer-reserve" type="number" min="0" max="40" step="1" value="${l.reserve}"><small>%</small></label><label class="layer-field"><span>Cena</span><input class="layer-price" type="number" min="0" step="10" value="${l.price}"><small>Kč/t</small></label></div><details class="layer-technical"><summary>Technické parametry vrstvy</summary><div class="technical-grid"><label class="layer-field"><span>Sypná hmotnost</span><input class="layer-density" type="number" min="0.1" max="3" step="0.01" value="${l.density}"><small>t/m³</small></label><label class="layer-field"><span>Hutnění</span><input class="layer-compaction" type="number" min="1" max="2" step="0.01" value="${l.compaction}"><small>součinitel</small></label><label class="layer-field"><span>Přímá plocha</span><input class="layer-area" type="number" min="0.1" step="0.1" value="${l.area}"><small>m², použije se pokud je zaškrtnuto</small></label><label class="layer-field layer-field-wide"><span><input class="layer-use-area" type="checkbox" ${l.useArea?'checked':''}> Použít přímou plochu místo délky × šířky</span></label></div></details></article>`}
function renderLayers(){layerList.innerHTML=layers.map(layerTemplate).join('')}
function syncLayers(){layers=layers.map(l=>{const c=$(`[data-layer-id="${l.id}"]`);if(!c)return l;return {...l,name:$('.layer-name',c).value||l.name,length:num($('.layer-length',c),l.length),width:num($('.layer-width',c),l.width),thickness:num($('.layer-thickness',c),l.thickness),count:num($('.layer-count',c),l.count),reserve:num($('.layer-reserve',c),l.reserve),price:num($('.layer-price',c),l.price),density:num($('.layer-density',c),l.density),compaction:num($('.layer-compaction',c),l.compaction),area:num($('.layer-area',c),l.area),useArea:$('.layer-use-area',c).checked,material:$('.layer-material',c).value}})}
function basicValues(){const material=$('#basicMaterial').value,p=PRESETS[material],measure=$('input[name="basicMeasure"]:checked').value;const a=measure==='area'?num('basicArea',0):num('basicLength',0)*num('basicWidth',0);return {name:p.name,short:p.short,purpose:PURPOSES[$('input[name="basicPurpose"]:checked').value].label,area:a,thickness:num('basicThickness',0),density:num('basicDensity',p.density),compaction:num('basicCompaction',p.compaction),reserve:num('basicReserve',p.reserve),price:num('basicPrice',p.price),bagWeight:num('basicBagWeight',25)}}
function calcItem(v){const compacted=v.area*(v.thickness/100)*(v.count||1),loose=compacted*v.compaction,order=loose*(1+v.reserve/100),kg=order*v.density*1000,cost=kg/1000*v.price;return {...v,compacted,loose,order,kg,cost,reserveKg:kg-(loose*v.density*1000)}}
function basicCalc(){const v=basicValues();return {mode:'basic',items:[calcItem(v)],bagWeight:v.bagWeight}}
function advancedCalc(){syncLayers();const items=layers.map(l=>{const p=PRESETS[l.material],a=(l.useArea?l.area:l.length*l.width);return calcItem({...l,name:l.name,short:p.short,area:a,purpose:'projektová vrstva'})});const totalArea=Math.max(0,...items.map(i=>i.area*(i.count||1))),totalCompacted=items.reduce((s,i)=>s+i.compacted,0),totalLoose=items.reduce((s,i)=>s+i.loose,0),totalOrder=items.reduce((s,i)=>s+i.order,0),totalKg=items.reduce((s,i)=>s+i.kg,0),materialCost=items.reduce((s,i)=>s+i.cost,0);const delivery=$('#enableDelivery').checked,cap=num('truckCapacity',12)*1000,minTrips=num('minimumTrips',1),trips=delivery?Math.max(minTrips,Math.ceil(totalKg/Math.max(cap,1))):0,deliveryCost=delivery?trips*num('tripPrice',0)+num('handlingCost',0):0;const bb=$('#enableBigBags').checked,bbW=num('bigBagWeight',1000),bigBags=bb?Math.ceil(totalKg/Math.max(bbW,1)):0,bigBagCost=bb?bigBags*num('bigBagSurcharge',0):0;const geo=$('#enableGeotextile').checked,geoArea=geo?totalArea*(1+num('geotextileOverlap',0)/100):0,rolls=geo?Math.ceil(geoArea/Math.max(num('geotextileRollArea',100),1)):0,geoCost=geo?rolls*num('geotextileRollPrice',0):0;const work=$('#enableWork').checked,workCost=work?totalArea*(num('spreadingPrice',0)+num('compactionWorkPrice',0))+num('equipmentCost',0)+num('otherCost',0):0;const excav=$('#enableExcavation').checked,excavCost=excav?totalCompacted*num('excavationPrice',0):0,totalCost=materialCost+deliveryCost+bigBagCost+geoCost+workCost+excavCost;return {mode:'advanced',items,totalArea,totalCompacted,totalLoose,totalOrder,totalKg,materialCost,trips,deliveryCost,bigBags,bigBagCost,geoArea,rolls,geoCost,workCost,excavCost,totalCost,bagWeight:25}}
function totals(r){if(r.mode==='basic'){const i=r.items[0];return {totalArea:i.area,totalCompacted:i.compacted,totalLoose:i.loose,totalOrder:i.order,totalKg:i.kg,materialCost:i.cost,totalCost:i.cost,trips:0,bigBags:Math.ceil(i.kg/1000)}}return r}
function updateResult(r){last=r;const t=totals(r),first=r.items[0]||{short:'-',name:'-',purpose:'-',thickness:0,density:0,compaction:1,reserveKg:0,kg:0};$('#resultModeBadge').textContent=r.mode==='basic'?'Základní režim':'Rozšířený projekt';$('#resultTitle').textContent=r.mode==='basic'?'Objednávka štěrku':'Souhrn celého projektu';$('#resultMaterialLabel').textContent=r.mode==='basic'?first.name:`${r.items.length} vrstev`;$('#resultWeight').textContent=weight(t.totalKg);$('#resultVolumeLine').textContent=`${vol(t.totalOrder)} sypaného materiálu`;$('#resultMainText').textContent=r.mode==='basic'?'Výsledek zahrnuje hutnění a zvolenou rezervu. Převod na tuny před objednávkou ověřte s dodavatelem.':`Projekt zahrnuje ${r.items.length} ${r.items.length===1?'vrstvu':'vrstvy/vrstev'} a ${fmt(t.totalArea,1)} m² půdorysné plochy.`;const baseKg=Math.max(0,t.totalKg-(r.items.reduce((s,i)=>s+i.reserveKg,0))),reserveKg=t.totalKg-baseKg,pct=t.totalKg?baseKg/t.totalKg*100:100;$('#gaugeBase').style.width=`${pct}%`;$('#gaugeReserve').style.width=`${100-pct}%`;$('#gaugeBaseLabel').textContent=weight(baseKg);$('#gaugeReserveLabel').textContent=weight(reserveKg);$('#metricCompactedVolume').textContent=vol(t.totalCompacted);$('#metricLooseVolume').textContent=vol(t.totalLoose);$('#metricBigBags').textContent=`${Math.ceil(t.totalKg/1000)} ks`;$('#metricSmallBags').textContent=`${Math.ceil(t.totalKg/(r.bagWeight||25))} ks`;$('#metricSmallBagLabel').textContent=`po ${fmt(r.bagWeight||25)} kg`;$('#summaryArea').textContent=area(t.totalArea);$('#summaryThickness').textContent=r.mode==='basic'?`vrstva ${fmt(first.thickness)} cm`:`${r.items.length} samostatných vrstev`;$('#summaryDensity').textContent=r.mode==='basic'?`${fmt(first.density,2)} t/m³`:'různé podle vrstev';$('#summaryCompaction').textContent=r.mode==='basic'?`hutnění × ${fmt(first.compaction,2)}`:'samostatné součinitele';$('#summaryMaterial').textContent=r.mode==='basic'?first.short:`${r.items.length} materiálů/vrstev`;$('#summaryPurpose').textContent=r.mode==='basic'?first.purpose:'projektová skladba';$('#summaryMaterialCost').textContent=money(t.materialCost);$('#advancedResults').hidden=r.mode!=='advanced';if(r.mode==='advanced'){$('#advancedLayerCount').textContent=r.items.length;$('#advancedTrips').textContent=r.trips;$('#advancedMaterialCost').textContent=money(r.materialCost);$('#advancedTotalCost').textContent=money(r.totalCost)}updateHero(t,first);updateScenarios(r);updateBreakdown(r);updateCosts(r);updateInsight(r,t)}
function updateHero(t,f){$('[data-hero-weight]').textContent=weight(t.totalKg);$('[data-hero-volume]').textContent=vol(t.totalOrder);$('[data-hero-bags]').textContent=`${Math.ceil(t.totalKg/1000)} ks`;$('[data-hero-compaction]').textContent=mode==='basic'?`+${fmt((f.compaction-1)*100)} %`:`${last.items.length} vrstvy`}
function updateScenarios(r){const base=r.mode==='basic'?basicValues():null;const opts=r.mode==='basic'?[{label:'Úsporná',c:Math.max(1,base.compaction-.05),res:3},{label:'Aktuální',c:base.compaction,res:base.reserve,current:true},{label:'Bezpečná',c:base.compaction+.05,res:8},{label:'Vyšší rezerva',c:base.compaction+.08,res:12}]:[{label:'Bez rezervy',mul:.94},{label:'Aktuální',mul:1,current:true},{label:'+ 5 % množství',mul:1.05},{label:'+ 10 % množství',mul:1.10}];$('#scenarioGrid').innerHTML=opts.map(o=>{let kg;if(r.mode==='basic'){const i=calcItem({...base,compaction:o.c,reserve:o.res});kg=i.kg}else kg=totals(r).totalKg*o.mul;return `<article class="scenario-card${o.current?' is-current':''}"><span>${o.label}</span><strong>${weight(kg)}</strong><small>${r.mode==='basic'?`hutnění × ${fmt(o.c,2)}, rezerva ${o.res} %`:`oproti aktuálnímu projektu`}</small></article>`}).join('')}
function updateBreakdown(r){$('#breakdownBody').innerHTML=r.items.map(i=>`<tr><td>${esc(i.name||i.short)}</td><td>${area(i.area*(i.count||1))}</td><td>${fmt(i.thickness)} cm</td><td>${vol(i.order)}</td><td>${weight(i.kg)}</td><td>${money(i.cost)}</td></tr>`).join('')}
function updateCosts(r){if(r.mode!=='advanced'){$('#costBreakdown').innerHTML='<div class="empty-cost">Přepněte do rozšířeného režimu pro kompletní rozpočet projektu.</div>';return}const rows=[['Kamenivo',r.materialCost],['Doprava a složení',r.deliveryCost],['Big bagy / obaly',r.bigBagCost],['Geotextilie',r.geoCost],['Rozprostření, hutnění a technika',r.workCost],['Výkop a odvoz',r.excavCost],['Celkem',r.totalCost]];$('#costBreakdown').innerHTML=rows.filter(([,v],i)=>v>0||i===rows.length-1).map(([n,v],i)=>`<div${i===rows.length-1?' class="cost-total"':''}><span>${n}</span><strong>${money(v)}</strong></div>`).join('')}
function updateInsight(r,t){let title='Objednávejte podle tun, ne pouze podle m³',text='Sypná hmotnost se mezi lomy a frakcemi liší. Kalkulaci použijte jako podklad pro potvrzení konkrétní nabídky.';if(r.mode==='advanced'){if(r.trips>1){title=`Logistika vychází na ${r.trips} jízdy`;text='Zvažte, zda dodavatel nabízí větší vozidlo nebo zda lze různé frakce přivézt efektivně v návazných jízdách.'}else if(r.geoCost>r.materialCost*.35){title='Geotextilie tvoří významnou část rozpočtu';text='Zkontrolujte rozměr role a skutečný přídavek na přesahy. Celé role mohou u malé plochy vytvořit větší zbytek.'}else{title='Projekt odděluje materiál od realizace';text=`Kamenivo tvoří ${t.totalCost?fmt(r.materialCost/t.totalCost*100):0} % celkového rozpočtu. Zbytek připadá na logistiku a navazující práce.`}}$('#insightTitle').textContent=title;$('#insightText').textContent=text}
function calculate(){try{const r=mode==='basic'?basicCalc():advancedCalc();updateResult(r)}catch(e){console.error(e)}}
function setMode(next){mode=next;document.body.dataset.calculatorMode=next;form.dataset.mode=next;$$('.mode-button').forEach(b=>{const a=b.dataset.mode===next;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',String(a))});$('#basicCalculation').hidden=next!=='basic';$('#advancedCalculation').hidden=next!=='advanced';if(next==='advanced'&&!layers.length)transferBasic();calculate()}
function applyPurpose(key){const p=PURPOSES[key],m=PRESETS[p.material];$('#basicMaterial').value=p.material;$('#basicThickness').value=p.thickness;$('#basicDensity').value=m.density;$('#basicCompaction').value=m.compaction;$('#basicPrice').value=m.price;$('#basicReserve').value=m.reserve;syncReserve(m.reserve)}
function applyMaterial(key){const p=PRESETS[key];$('#basicDensity').value=p.density;$('#basicCompaction').value=p.compaction;$('#basicPrice').value=p.price}
function syncReserve(v){$('#basicReserve').value=v;$('#basicReserveOutput').textContent=`${v} %`;$$('[data-reserve]').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.reserve)===Number(v)))}
function transferBasic(){const b=basicValues();layers=[];counter=0;addLayer({name:b.purpose.charAt(0).toUpperCase()+b.purpose.slice(1),length:num('basicLength',8),width:num('basicWidth',3),area:b.area,useArea:$('input[name="basicMeasure"]:checked').value==='area',thickness:b.thickness,material:$('#basicMaterial').value,density:b.density,compaction:b.compaction,reserve:b.reserve,price:b.price})}
function resetBasic(){document.querySelector('input[name="basicPurpose"][value="driveway"]').checked=true;document.querySelector('input[name="basicMeasure"][value="dimensions"]').checked=true;$('#basicLength').value=8;$('#basicWidth').value=3;$('#basicArea').value=24;$('#basicThickness').value=15;$('#basicMaterial').value='mix032';$('#basicDensity').value=1.75;$('#basicCompaction').value=1.15;$('#basicPrice').value=650;$('#basicBagWeight').value=25;syncReserve(5);toggleMeasure();calculate()}
function resetAdvanced(){layers=[];counter=0;addLayer({name:'Nosná vrstva 0/32'});$('#enableDelivery').checked=true;$('#enableBigBags').checked=false;$('#enableGeotextile').checked=true;$('#enableWork').checked=true;$('#enableExcavation').checked=false;toggleExtras();calculate()}
function toggleMeasure(){const a=$('input[name="basicMeasure"]:checked').value==='area';$('.dimensions-fields').hidden=a;$('.area-fields').hidden=!a}
function toggleExtras(){$('[data-delivery-fields]').hidden=!$('#enableDelivery').checked;$('[data-bigbag-fields]').hidden=!$('#enableBigBags').checked;$('[data-geotextile-fields]').hidden=!$('#enableGeotextile').checked;$('[data-work-fields]').hidden=!$('#enableWork').checked;$('[data-excavation-fields]').hidden=!$('#enableExcavation').checked}
form.addEventListener('submit',e=>{e.preventDefault();calculate()});form.addEventListener('input',e=>{if(e.target.id==='basicReserve')syncReserve(e.target.value);if(e.target.matches('input[name="basicMeasure"]'))toggleMeasure();if(e.target.matches('#enableDelivery,#enableBigBags,#enableGeotextile,#enableWork,#enableExcavation'))toggleExtras();calculate()});form.addEventListener('change',e=>{if(e.target.matches('input[name="basicPurpose"]'))applyPurpose(e.target.value);if(e.target.id==='basicMaterial')applyMaterial(e.target.value);if(e.target.classList.contains('layer-material')){const c=e.target.closest('.layer-card'),p=PRESETS[e.target.value];$('.layer-density',c).value=p.density;$('.layer-compaction',c).value=p.compaction;$('.layer-reserve',c).value=p.reserve;$('.layer-price',c).value=p.price}calculate()});form.addEventListener('click',e=>{const modeBtn=e.target.closest('.mode-button');if(modeBtn){setMode(modeBtn.dataset.mode);return}const res=e.target.closest('[data-reserve]');if(res){syncReserve(res.dataset.reserve);calculate();return}if(e.target.closest('.remove-layer')){const c=e.target.closest('.layer-card');layers=layers.filter(l=>l.id!==c.dataset.layerId);renderLayers();calculate()}});
$('#addLayer').addEventListener('click',()=>addLayer({name:`Vrstva ${layers.length+1}`}));$('#basicToAdvanced').addEventListener('click',()=>{transferBasic();setMode('advanced');document.querySelector('#kalkulacka').scrollIntoView({behavior:'smooth'})});$('#resetBasic').addEventListener('click',resetBasic);$('#resetAdvanced').addEventListener('click',resetAdvanced);$('#copyResult').addEventListener('click',async()=>{if(!last)return;const t=totals(last),txt=`Kalkulačka štěrku – RychléVýpočty.cz\nDoporučené množství: ${weight(t.totalKg)}\nObjednávaný objem: ${vol(t.totalOrder)}\nPlocha: ${area(t.totalArea)}\nMateriál: ${money(t.materialCost)}${last.mode==='advanced'?`\nCelý projekt: ${money(last.totalCost)}`:''}`;try{await navigator.clipboard.writeText(txt);$('#copyResult').textContent='Zkopírováno';setTimeout(()=>$('#copyResult').textContent='Kopírovat výsledek',1400)}catch{}});$('#printResult').addEventListener('click',()=>window.print());
toggleMeasure();toggleExtras();addLayer({name:'Nosná vrstva 0/32'});calculate();
})();