(() => {
'use strict';
const $=id=>document.getElementById(id);
const qsa=s=>[...document.querySelectorAll(s)];
const money=v=>`${Math.max(0,Math.ceil(Number.isFinite(v)?v:0)).toLocaleString('cs-CZ')} Kč`;
const num=v=>Number(String(v??'').replace(/\s/g,'').replace(',','.'))||0;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const LIFE={individual:4860,firstAdult:4470,otherAdult:4040,childUnder6:2480,child6to15:3050,child15to26:3490,existence:3130};
const SERVICE={standard:[880,1240,1600,1710,1820],vulnerable:[1310,1770,2230,2370,2380]};
const ENERGY=[2300,2800,3300,3800,4300];
const SOLID=[1500,2000,2500,3000,3500];
const NORM={standard:{small:[7580,9245,10600,11230,11487],large:[9430,10950,12300,12632,12052],prague:[12831,14466,16600,17710,17320]},vulnerable:{small:[10310,12109,13758,14370,14880],large:[12310,13770,15394,16230,15780],prague:[15910,18103,20230,22170,22380]}};
const templates={single:[{type:'adult',active:true,vulnerable:false,plan:false}],singleChild:[{type:'adult',active:true,vulnerable:false,plan:false},{type:'child6to15',active:false,vulnerable:true,plan:false}],couple:[{type:'adult',active:true,vulnerable:false,plan:false},{type:'adult',active:true,vulnerable:false,plan:false}],coupleTwoChildren:[{type:'adult',active:true,vulnerable:false,plan:false},{type:'adult',active:true,vulnerable:false,plan:false},{type:'childUnder6',active:false,vulnerable:true,plan:false},{type:'child6to15',active:false,vulnerable:true,plan:false}]};
let members=structuredClone(templates.coupleTwoChildren);let activeMode='basic';let basicTemplate='coupleTwoChildren';
const el={form:$('dsspForm'),modeBtns:qsa('.sd87-mode [data-mode]'),basic:$('sd87BasicPanel'),advanced:$('sd87AdvancedPanel'),memberList:$('memberList'),add:$('addMember'),reset:$('resetBtn'),status:$('resultStatus'),total:$('totalBenefit'),explanation:$('resultExplanation'),housing:$('housingComponent'),living:$('livingComponent'),child:$('childComponent'),work:$('workComponent'),life:$('lifeMinimum'),ratio:$('incomeRatio'),recognised:$('recognisedHousing'),asset:$('assetLimit'),warnBox:$('warningBox'),warnList:$('warningList'),heroTotal:$('heroTotal'),heroGate:$('heroGateStatus'),days:$('daysToOctober'),menu:document.querySelector('.sd87-menu'),mobile:document.querySelector('.sd87-mobile-nav')};
function clone(t){return structuredClone(templates[t]);}
function countAdults(list){return list.filter(m=>m.type==='adult').length}
function countChildren(list){return list.filter(m=>m.type!=='adult').length}
function idx(count){return clamp(Math.floor(count),1,5)-1}
function savingsLimit(count){return Math.min(400000,150000+50000*count)}
function memberLabel(type){return type==='adult'?'Dospělá osoba':type==='childUnder6'?'Dítě do 6 let':type==='child6to15'?'Dítě 6–15 let':'Dítě 15–26 let'}
function lifeMinimum(list){if(list.length===1)return list[0].type==='adult'?LIFE.individual:LIFE[list[0].type];let first=false;return list.reduce((s,m)=>{if(m.type==='adult'){const v=first?LIFE.otherAdult:LIFE.firstAdult;first=true;return s+v}return s+LIFE[m.type]},0)}
function adultLifeMinimum(member,index,list){if(list.length===1)return LIFE.individual;const a=list.map((m,i)=>m.type==='adult'?i:-1).filter(i=>i>=0);return index===a[0]?LIFE.firstAdult:LIFE.otherAdult}
function formatInput(node){if(!node)return;const v=Math.max(0,Math.round(num(node.value)));node.value=v.toLocaleString('cs-CZ')}
function renderMembers(){if(!el.memberList)return;el.memberList.innerHTML=members.map((m,i)=>`<article class="sd87-member" data-member-card="${i}"><div class="sd87-member-head"><strong>Osoba ${i+1}</strong>${members.length>1?`<button type="button" data-remove="${i}">Odebrat</button>`:''}</div><div class="sd87-member-grid"><label><select data-index="${i}" data-key="type" aria-label="Typ osoby ${i+1}"><option value="adult" ${m.type==='adult'?'selected':''}>Dospělá osoba</option><option value="childUnder6" ${m.type==='childUnder6'?'selected':''}>Dítě do 6 let</option><option value="child6to15" ${m.type==='child6to15'?'selected':''}>Dítě 6–15 let</option><option value="child15to26" ${m.type==='child15to26'?'selected':''}>Dítě 15–26 let</option></select></label><div class="sd87-member-checks ${m.type!=='adult'?'is-child':''}"><label><input type="checkbox" data-index="${i}" data-key="active" ${m.active?'checked':''} ${m.type!=='adult'?'disabled':''}> aktivní / evidence ÚP</label><label><input type="checkbox" data-index="${i}" data-key="vulnerable" ${m.vulnerable?'checked':''} ${m.type!=='adult'?'disabled':''}> zranitelná osoba</label><label><input type="checkbox" data-index="${i}" data-key="plan" ${m.plan?'checked':''} ${m.type!=='adult'?'disabled':''}> podpůrný plán</label></div></div></article>`).join('');
el.memberList.querySelectorAll('[data-index]').forEach(c=>c.addEventListener('change',()=>{const i=+c.dataset.index,key=c.dataset.key;if(key==='type'){members[i].type=c.value;if(c.value!=='adult'){members[i].active=false;members[i].vulnerable=true;members[i].plan=false}renderMembers()}else members[i][key]=c.checked;syncAllPeople();calculate()}));
el.memberList.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{members.splice(+b.dataset.remove,1);if(!members.length)members.push({type:'adult',active:true,vulnerable:false,plan:false});renderMembers();syncAllPeople();calculate()}));}
function syncAllPeople(){const a=$('allPeople');if(a&&num(a.value)<members.length)a.value=members.length}
function basicValues(){return{workIncome:Math.max(0,num($('basicWorkIncome').value)),otherIncome:Math.max(0,num($('basicOtherIncome').value)),housingType:$('basicHousingType').value,region:$('basicRegion').value,rent:Math.max(0,num($('basicRent').value)),energyActual:Math.max(0,num($('basicEnergy').value)),allPeople:members.length,solidFuel:false,schoolOk:true,savings:0,cars:Math.min(1,countAdults(members)),homes:1,secondHomeException:false,assumeAssets:true}}
function advancedValues(){return{workIncome:Math.max(0,num($('workIncome').value)),otherIncome:Math.max(0,num($('otherIncome').value)),housingType:$('housingType').value,region:$('region').value,rent:Math.max(0,num($('rentCosts').value)),energyActual:Math.max(0,num($('energyCosts').value)),allPeople:Math.max(members.length,Math.floor(num($('allPeople').value)||members.length)),solidFuel:$('solidFuel').checked,schoolOk:$('schoolOk').checked,savings:Math.max(0,num($('savings').value)),cars:Math.max(0,Math.floor(num($('cars').value))),homes:Math.max(0,Math.floor(num($('homes').value))),secondHomeException:$('secondHomeException').checked,assumeAssets:false}}
function engine(v){const work=v.workIncome,other=v.otherIncome,income=work+other,count=members.length,adults=countAdults(members),children=countChildren(members),allVulnerable=members.every(m=>m.type!=='adult'||m.vulnerable),allRequiredActive=members.filter(m=>m.type==='adult').every(m=>m.vulnerable||m.active),eligible=members.filter(m=>m.type!=='adult'||m.active||m.vulnerable),effectiveCount=Math.max(1,eligible.length),life=lifeMinimum(members),ratio=life?income/life:0,i=idx(effectiveCount),group=allVulnerable?'vulnerable':'standard',norm=NORM[group][v.region][i],service=SERVICE[group][i],energyP=ENERGY[i]*(allVulnerable?1.4:1),solid=v.solidFuel?SOLID[i]*(allVulnerable?1.4:1):0;let recEnergy=ratio>=1.43?energyP:Math.min(v.energyActual+solid,energyP*1.2);let recBase;if(v.housingType==='owner')recBase=.3*Math.max(0,norm-service)+service;else if(v.housingType==='other')recBase=Math.min(v.rent,norm*.8);else recBase=Math.min(v.rent,norm);let recHousing=(recBase+recEnergy)*(count/v.allPeople);const determined=.3*income+(income>2*life?.1*(income-2*life):0);const housing=Math.max(0,recHousing-determined);let needs=0;members.forEach((m,index)=>{if(m.type!=='adult')needs+=LIFE[m.type];else if(m.active||m.vulnerable)needs+=m.plan?adultLifeMinimum(m,index,members):LIFE.existence});const living=ratio<=1.43?Math.max(0,needs-.7*income):0;let childPer=0;if(children&&allRequiredActive&&v.schoolOk&&ratio<=4){if(ratio<=1.43)childPer=allVulnerable?1000:500;else if(ratio<3)childPer=1000;else childPer=Math.max(0,1000*(4-ratio))}const child=children*childPer;let workBonus=0;if(work>0&&(housing>0||living>0||child>0)){if(ratio<=1.6)workBonus=.4*work;else{const excess=Math.max(0,income-1.6*life);workBonus=Math.max(0,.4*Math.max(0,work-excess)-.3*excess)}}const limit=savingsLimit(count);const issues=[];if(!v.assumeAssets){if(v.savings>limit)issues.push(`Úspory překračují limit ${money(limit)}.`);if(v.cars>adults)issues.push(`Počet aut je vyšší než počet dospělých (${adults}).`);if(v.homes>2)issues.push('Domácnost vlastní více nemovitostí, než připouští základní majetkový test.');if(v.homes===2&&!v.secondHomeException)issues.push('Druhá nemovitost vyžaduje ověření časově omezené výjimky.')}if(count===1&&adults===1&&!members[0].active&&!members[0].vulnerable)issues.push('Jednočlenná domácnost bez pracovní aktivity a bez zranitelnosti podle základního pravidla neprochází.');if(children&&!v.schoolOk)issues.push('Bonus na dítě je vypnutý, protože není potvrzena školní docházka.');if(!allRequiredActive&&children)issues.push('Bonus na dítě může zaniknout kvůli pracovní neaktivitě nezranitelného dospělého.');const hard=issues.some(x=>x.includes('Úspory')||x.includes('Počet aut')||x.includes('více nemovitostí')||x.includes('Jednočlenná'));const raw=Math.ceil(housing+living+child+workBonus);return{total:hard?0:raw,housing,living,child,work:workBonus,life,ratio,recHousing,limit,issues,hard,assumeAssets:v.assumeAssets}}
function setText(id,v){const n=$(id);if(n)n.textContent=v}
function render(result){setText('totalBenefit',money(result.total));setText('housingComponent',money(result.housing));setText('livingComponent',money(result.living));setText('childComponent',money(result.child));setText('workComponent',money(result.work));setText('lifeMinimum',money(result.life));setText('incomeRatio',`${result.ratio.toLocaleString('cs-CZ',{maximumFractionDigits:2})}× minima`);setText('recognisedHousing',money(result.recHousing));setText('assetLimit',money(result.limit));if(el.heroTotal)el.heroTotal.textContent=money(result.total);const comps=[['housingBar',result.housing],['livingBar',result.living],['childBar',result.child],['workBar',result.work]],max=Math.max(1,...comps.map(x=>x[1]));comps.forEach(([id,v])=>{const n=$(id);if(n)n.style.width=`${Math.min(100,(v/max)*100)}%`});if(result.hard){el.status.textContent='Základní test neprošel';el.status.className='is-risk';el.explanation.textContent='Zadaný scénář obsahuje překážku, která podle základního modelu může nárok vyloučit.';if(el.heroGate)el.heroGate.textContent='Něco blokuje nárok'}else if(result.total>0){el.status.textContent=result.assumeAssets?'Orientační částka':'Předběžně prochází';el.status.className='is-success';el.explanation.textContent=result.assumeAssets?'Výsledek předpokládá splněný majetkový test. Přesnější režim ho umí orientačně prověřit.':'Podle zadaných údajů nevznikla v základních testech zjevná překážka.';if(el.heroGate)el.heroGate.textContent='Scénář předběžně prochází'}else{el.status.textContent='Bez vypočtené dávky';el.status.className='is-neutral';el.explanation.textContent='Podle zadaných hodnot nevychází kladná částka jednotlivých složek.';if(el.heroGate)el.heroGate.textContent='Bez kladné složky'}const warnings=[...result.issues];if(result.assumeAssets)warnings.unshift('Základní režim neověřuje skutečné úspory, auta ani další nemovitosti.');if(new Date()>=new Date(2026,9,1))warnings.unshift('Tento engine je historický model do 30. 9. 2026. Pro aktuální žádost použijte kalkulačku MPSV.');el.warnList.innerHTML=warnings.map(x=>`<li>${x}</li>`).join('');el.warnBox.hidden=!warnings.length}
function calculate(){const v=activeMode==='basic'?basicValues():advancedValues();const r=engine(v);render(r);return r}
function setMode(mode,focus=false){activeMode=mode;el.modeBtns.forEach(b=>{const a=b.dataset.mode===mode;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',String(a));b.tabIndex=a?0:-1;if(a&&focus)b.focus()});el.basic.hidden=mode!=='basic';el.advanced.hidden=mode!=='advanced';$('modeHelp').textContent=mode==='basic'?'Vyberte domácnost, zadejte příjem a bydlení. Majetek můžete prověřit až v přesnějším režimu.':'Přesnější režim přidá konkrétní členy domácnosti, pracovní aktivitu, zranitelnost a základní majetkový test.';calculate()}
function syncBasicToAdvanced(){$('workIncome').value=$('basicWorkIncome').value;$('otherIncome').value=$('basicOtherIncome').value;$('housingType').value=$('basicHousingType').value;$('region').value=$('basicRegion').value;$('rentCosts').value=$('basicRent').value;$('energyCosts').value=$('basicEnergy').value;$('allPeople').value=members.length;renderMembers()}
function applyTemplate(key){basicTemplate=key;members=clone(key);qsa('[data-template]').forEach(b=>b.classList.toggle('is-active',b.dataset.template===key));syncBasicToAdvanced();calculate()}
qsa('[data-template]').forEach(b=>b.addEventListener('click',()=>applyTemplate(b.dataset.template)));
el.modeBtns.forEach((b,i)=>{b.addEventListener('click',()=>{if(b.dataset.mode==='advanced')syncBasicToAdvanced();setMode(b.dataset.mode)});b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let next=i;if(e.key==='ArrowRight')next=(i+1)%el.modeBtns.length;if(e.key==='ArrowLeft')next=(i-1+el.modeBtns.length)%el.modeBtns.length;if(e.key==='Home')next=0;if(e.key==='End')next=el.modeBtns.length-1;const n=el.modeBtns[next];if(n.dataset.mode==='advanced')syncBasicToAdvanced();setMode(n.dataset.mode,true)})});
['basicWorkIncome','basicOtherIncome','basicRent','basicEnergy','workIncome','otherIncome','rentCosts','energyCosts','allPeople','savings','cars','homes'].forEach(id=>{const n=$(id);n?.addEventListener('input',calculate);n?.addEventListener('change',()=>{if(!['allPeople','cars','homes'].includes(id))formatInput(n);calculate()})});
['basicHousingType','basicRegion','housingType','region','schoolOk','solidFuel','secondHomeException'].forEach(id=>$(id)?.addEventListener('change',calculate));
el.add?.addEventListener('click',()=>{if(members.length>=12)return;members.push({type:'adult',active:true,vulnerable:false,plan:false});renderMembers();syncAllPeople();calculate()});
el.form?.addEventListener('submit',e=>{e.preventDefault();calculate()});el.reset?.addEventListener('click',()=>{members=clone('coupleTwoChildren');basicTemplate='coupleTwoChildren';$('basicWorkIncome').value='36 000';$('basicOtherIncome').value='0';$('basicHousingType').value='rent';$('basicRegion').value='large';$('basicRent').value='18 000';$('basicEnergy').value='4 000';qsa('[data-template]').forEach(b=>b.classList.toggle('is-active',b.dataset.template==='coupleTwoChildren'));syncBasicToAdvanced();$('savings').value='80 000';$('cars').value='1';$('homes').value='1';$('schoolOk').checked=true;$('solidFuel').checked=false;$('secondHomeException').checked=false;setMode('basic')});
function updateDeadline(){if(!el.days)return;const target=new Date(2026,9,1),today=new Date(),t=new Date(today.getFullYear(),today.getMonth(),today.getDate()),diff=Math.ceil((target-t)/86400000);el.days.textContent=diff>1?`Za ${diff} dní se mění model bydlení`:diff===1?'Zítra se mění model bydlení':diff===0?'Dnes se mění model bydlení':'Od 1. října 2026 platí nový model bydlení'}
if(el.menu&&el.mobile){el.menu.addEventListener('click',()=>{const open=el.menu.getAttribute('aria-expanded')==='true';el.menu.setAttribute('aria-expanded',String(!open));el.mobile.hidden=open});el.mobile.addEventListener('click',e=>{if(e.target.closest('a')){el.mobile.hidden=true;el.menu.setAttribute('aria-expanded','false')}})}
renderMembers();syncBasicToAdvanced();updateDeadline();calculate();
window.__RV_SD87__={engine,templates,LIFE,NORM};
})();