
(function(){
  const $ = (id) => document.getElementById(id);
  const cur = (value, digits=0) => new Intl.NumberFormat('cs-CZ', { style:'currency', currency:'CZK', maximumFractionDigits:digits }).format(Number.isFinite(value) ? value : 0);
  const num = (value, digits=0) => new Intl.NumberFormat('cs-CZ', { maximumFractionDigits:digits }).format(Number.isFinite(value) ? value : 0);
  const set = (id, value) => { const el = $(id); if (el) el.textContent = value; };
  const fields=['carPrice','ownershipYears','annualKm','resalePrice','downPayment','monthlyLoanPayment','fuelConsumption','fuelPrice','insuranceMonthly','serviceMonthly','tiresMonthly','parkingMonthly','feesMonthly','otherMonthly','incomeShare'];
  function values(){ return Object.fromEntries(fields.map((id)=>[id, Number($(id).value)])); }
  function calc(v){ const months=v.ownershipYears*12; const totalKm=v.annualKm*v.ownershipYears; const fuelTotal=totalKm/100*v.fuelConsumption*v.fuelPrice; const insuranceTotal=v.insuranceMonthly*months; const serviceTotal=v.serviceMonthly*months; const tiresTotal=v.tiresMonthly*months; const parkingTotal=v.parkingMonthly*months; const feesTotal=v.feesMonthly*months; const otherTotal=v.otherMonthly*months; const financingTotal=v.monthlyLoanPayment*months; const operatingTotal=insuranceTotal+serviceTotal+tiresTotal+parkingTotal+feesTotal+otherTotal; const depreciationCost=v.carPrice-v.resalePrice; const cashOut=v.downPayment+financingTotal+fuelTotal+operatingTotal; const totalOwnershipCost=cashOut+depreciationCost; const monthlyAverage=totalOwnershipCost/months; const costPerKm=totalOwnershipCost/totalKm; const neededIncome=monthlyAverage/(v.incomeShare/100); const items=[['Ztráta hodnoty auta',depreciationCost/months,depreciationCost],['Palivo',fuelTotal/months,fuelTotal],['Financování / splátky',v.monthlyLoanPayment,financingTotal],['Pojištění',v.insuranceMonthly,insuranceTotal],['Servis a údržba',v.serviceMonthly,serviceTotal],['Pneumatiky',v.tiresMonthly,tiresTotal],['Parkování / garáž',v.parkingMonthly,parkingTotal],['Dálniční známka a poplatky',v.feesMonthly,feesTotal],['Ostatní náklady',v.otherMonthly,otherTotal]].filter((item)=>item[2]>0); return {months,totalKm,fuelTotal,operatingTotal,financingTotal,depreciationCost,totalOwnershipCost,monthlyAverage,costPerKm,neededIncome,items}; }
  function decision(r){ if(r.monthlyAverage<=9000) return ['Spíše rozumné','Auto působí při zadaných hodnotách relativně rozumně. Teď se vyplatí porovnat cenu za kilometr a provozní položky.','Porovnejte provoz auta']; if(r.monthlyAverage>15000) return ['Dražší scénář','Vlastnictví auta vychází poměrně draze. Největší roli může hrát financování, amortizace nebo vysoké provozní náklady.','Prověřte amortizaci']; return ['Běžný scénář','Důležité není jen to, kolik stojí koupě auta, ale kolik stojí celé období vlastnictví.','Rozpadněte hlavní položky']; }
  function table(r){ $('breakdownBody').innerHTML = r.items.map(([name,monthly,total])=>{ const share = r.totalOwnershipCost>0 ? total/r.totalOwnershipCost*100 : 0; return `<tr><td>${name}</td><td>${cur(monthly)}</td><td>${cur(total)}</td><td>${num(share,1)} %</td></tr>`; }).join(''); }
  function run(){ const v=values(); if(!v.carPrice || !v.ownershipYears || !v.annualKm || !v.fuelConsumption || !v.fuelPrice || v.downPayment > v.carPrice || v.resalePrice > v.carPrice*1.2){ set('totalOwnershipCost','0 Kč'); set('resultNote','Zkontrolujte kupní cenu, období, nájezd, spotřebu a prodejní cenu.'); return; } const r=calc(v); set('totalOwnershipCost',cur(r.totalOwnershipCost)); set('monthlyAverage',cur(r.monthlyAverage)); set('costPerKm',cur(r.costPerKm,2)); set('depreciationCost',cur(r.depreciationCost)); set('fuelTotal',cur(r.fuelTotal)); set('operatingTotal',cur(r.operatingTotal)); set('financingTotal',cur(r.financingTotal)); set('totalKm',`${num(r.totalKm)} km`); set('neededIncome',cur(r.neededIncome)); const d=decision(r); set('ownershipBadge',d[0]); set('ownershipStatus',d[0]); set('ownershipText',d[1]); set('actionStatus',d[2]); set('decisionSummary',`Měsíční průměr vychází na ${cur(r.monthlyAverage)} a cena za kilometr na ${cur(r.costPerKm,2)}.`); set('nextActionText','Pokud výsledek vychází vysoko, porovnejte amortizaci, provoz a financování odděleně.'); set('resultNote','Celková cena vlastnictví je orientační součet hotovosti, financování, provozu, paliva a ztráty hodnoty.'); table(r); }
  function preset(name){ const p={standard:{carPrice:720000,ownershipYears:5,annualKm:18000,resalePrice:330000,downPayment:200000,monthlyLoanPayment:9500,fuelConsumption:6.7,fuelPrice:38.50,insuranceMonthly:1800,serviceMonthly:1400,tiresMonthly:450,parkingMonthly:900,feesMonthly:220,otherMonthly:300,incomeShare:15},cash:{carPrice:720000,ownershipYears:5,annualKm:18000,resalePrice:330000,downPayment:720000,monthlyLoanPayment:0,fuelConsumption:6.7,fuelPrice:38.50,insuranceMonthly:1800,serviceMonthly:1400,tiresMonthly:450,parkingMonthly:900,feesMonthly:220,otherMonthly:300,incomeShare:15},financed:{carPrice:720000,ownershipYears:5,annualKm:18000,resalePrice:310000,downPayment:120000,monthlyLoanPayment:11900,fuelConsumption:6.7,fuelPrice:38.50,insuranceMonthly:1900,serviceMonthly:1450,tiresMonthly:450,parkingMonthly:900,feesMonthly:220,otherMonthly:300,incomeShare:20},premium:{carPrice:1100000,ownershipYears:5,annualKm:20000,resalePrice:470000,downPayment:250000,monthlyLoanPayment:16500,fuelConsumption:7.8,fuelPrice:39.90,insuranceMonthly:2600,serviceMonthly:1900,tiresMonthly:650,parkingMonthly:900,feesMonthly:220,otherMonthly:450,incomeShare:20}}[name]; Object.entries(p).forEach(([id,value])=>{$(id).value=value;}); document.querySelectorAll('.scenario-chip').forEach((btn)=>btn.setAttribute('aria-pressed', String(btn.dataset.preset===name))); run(); }
  $('ownershipForm').addEventListener('submit',(e)=>{e.preventDefault(); run();});
  fields.forEach((id)=>{$(id).addEventListener('input',run); $(id).addEventListener('change',run);});
  document.querySelectorAll('.scenario-chip').forEach((btn)=>btn.addEventListener('click',()=>preset(btn.dataset.preset)));
  $('resetBtn').addEventListener('click',()=>preset('standard'));
  run();
})();
