(function(){
  const $=(id)=>document.getElementById(id), form=$('formulaForm'); if(!form) return;
  const money=(v)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(Math.max(0,v||0));
  const pct=(v,d=1)=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:d}).format(v)+' %';
  const num=(v,d=1)=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:d}).format(v);
  const ids=['packPrice','packsPerMonth','monthsPeriod','extrasMonthly','householdIncome','incomeShare'];
  const out=['monthlyCost','periodCost','yearlyCost','packPriceResult','packsPerMonthResult','monthlyWithExtras','yearlyWithExtras','incomeShareResult','neededIncome','budgetBadge','budgetStatus','budgetText','actionStatus','decisionSummary','nextActionText','scenarioTableBody','heroMonthly','heroPack','heroYearly','heroPacks','heroFormulaBar','heroExtrasBar','heroPeriodBar'];
  const el=Object.fromEntries(out.map(id=>[id,$(id)]));
  function val(){return Object.fromEntries(ids.map(id=>[id,Number($(id).value)||0]));}
  function calc(v){const monthly=v.packPrice*v.packsPerMonth; const monthlyWithExtras=monthly+v.extrasMonthly; return {monthly,monthlyWithExtras,yearly:monthly*12,yearlyWithExtras:monthlyWithExtras*12,period:monthlyWithExtras*v.monthsPeriod,share:v.householdIncome>0?monthlyWithExtras/v.householdIncome*100:0,needed:v.incomeShare>0?monthlyWithExtras/(v.incomeShare/100):0};}
  function msg(v,r){if(r.share<=3)return['success','Položka spíše v pohodě','Vůči příjmu domácnosti působí umělé mléko zvládnutelně. Pořád ho ale započítejte do prvního roku dítěte.','Dobrá pozice','Výsledek vypadá rozumně. Dál porovnejte hlavně pleny a celkový první rok.']; if(r.share>5||v.packPrice>=550||v.packsPerMonth>=7)return['risk','Položka: vyšší zátěž','Náklady na umělé mléko už tvoří výraznější pravidelný výdaj. Sledujte kombinaci ceny balení a spotřeby.','Pozor','Tento scénář je citlivý na dražší značku i vyšší počet balení za měsíc.']; return['warning','Položka na hraně','Umělé mléko je viditelná měsíční položka. Vyplatí se zpřesnit cenu balení, spotřebu a doplňky.','Další krok','Nejdřív ověřte, jestli náklad táhne cena balení, nebo množství balení za měsíc.'];}
  function rows(v){return[{label:'Levnější varianta',price:v.packPrice*.85,packs:v.packsPerMonth,extras:v.extrasMonthly},{label:'Běžný scénář',price:v.packPrice,packs:v.packsPerMonth,extras:v.extrasMonthly},{label:'Vyšší spotřeba',price:v.packPrice,packs:v.packsPerMonth*1.25,extras:v.extrasMonthly},{label:'Dražší značka',price:v.packPrice*1.18,packs:v.packsPerMonth,extras:v.extrasMonthly}].map(row=>{const monthly=row.price*row.packs+row.extras; return {label:row.label,price:row.price,monthly,yearly:monthly*12,share:v.householdIncome>0?monthly/v.householdIncome*100:0};});}
  function render(){const v=val(), r=calc(v), m=msg(v,r); el.monthlyCost.textContent=money(r.monthly); el.periodCost.textContent=money(r.period); el.yearlyCost.textContent=money(r.yearly); el.packPriceResult.textContent=money(v.packPrice); el.packsPerMonthResult.textContent=num(v.packsPerMonth,1); el.monthlyWithExtras.textContent=money(r.monthlyWithExtras); el.yearlyWithExtras.textContent=money(r.yearlyWithExtras); el.incomeShareResult.textContent=pct(r.share); el.neededIncome.textContent=money(r.needed); el.budgetBadge.textContent=m[1]; el.budgetBadge.className='rv-family-score '+m[0]; el.budgetStatus.textContent=m[1].replace('Položka: ',''); el.budgetText.textContent=m[2]; el.actionStatus.textContent=m[3]; el.decisionSummary.textContent=m[4]; el.nextActionText.textContent='Po výpočtu porovnejte umělé mléko s plenami a celým prvním rokem dítěte, aby rozpočet nebyl posuzovaný izolovaně.'; el.scenarioTableBody.innerHTML=rows(v).map(row=>`<tr><td>${row.label}</td><td>${money(row.price)}</td><td>${money(row.monthly)}</td><td>${money(row.yearly)}</td><td>${pct(row.share)}</td></tr>`).join(''); if(el.heroMonthly){el.heroMonthly.textContent=money(r.monthlyWithExtras); el.heroPack.textContent=money(v.packPrice); el.heroYearly.textContent=money(r.yearlyWithExtras); el.heroPacks.textContent=num(v.packsPerMonth,1)+' bal./měs.'; el.heroFormulaBar.style.width=Math.min(100,(r.monthly/r.monthlyWithExtras)*100)+'%'; el.heroExtrasBar.style.width=Math.min(100,(v.extrasMonthly/r.monthlyWithExtras)*100)+'%'; el.heroPeriodBar.style.width=Math.min(100,(v.monthsPeriod/24)*100)+'%';}}
  const presets={standard:{packPrice:419,packsPerMonth:5,monthsPeriod:12,extrasMonthly:250,householdIncome:65000,incomeShare:4},saving:{packPrice:339,packsPerMonth:5,monthsPeriod:12,extrasMonthly:180,householdIncome:65000,incomeShare:4},'higher-use':{packPrice:419,packsPerMonth:7,monthsPeriod:12,extrasMonthly:300,householdIncome:65000,incomeShare:5},premium:{packPrice:569,packsPerMonth:5,monthsPeriod:12,extrasMonthly:300,householdIncome:65000,incomeShare:5}};
  document.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>{const p=presets[btn.dataset.preset]; if(!p)return; Object.entries(p).forEach(([k,v])=>{$(k).value=v}); document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b===btn)); render();}));
  $('resetBtn')?.addEventListener('click',()=>document.querySelector('[data-preset="standard"]')?.click());
  ids.forEach(id=>{$(id).addEventListener('input',render);$(id).addEventListener('change',render)}); form.addEventListener('submit',e=>{e.preventDefault();render()}); render();
})();
