(()=>{"use strict";
const $=id=>document.getElementById(id);const nf=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:0});const pf=new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:1});
const TABLE={0:[14,12,10,8],1:[16,14,12,10],2:[18,16,14,12],3:[20,18,16,14]};
const money=v=>`${nf.format(Math.round(v||0))} Kč`;const pct=v=>`${pf.format(v)} %`;
const parse=v=>{const s=String(v??'').replace(/\s/g,'').replace(',','.').replace(/[^0-9.-]/g,'');return Number(s)||0};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function stage(age){if(age<=5)return{idx:0,label:'předškolní věk'};if(age<=10)return{idx:1,label:'1. stupeň ZŠ'};if(age<=15)return{idx:2,label:'2. stupeň ZŠ'};return{idx:3,label:'SŠ a vyšší vzdělávání'}}
function rate(age,obligations){const s=stage(age);return{...s,rate:TABLE[s.idx][clamp(Math.round(obligations),1,4)-1]}}
function modelOne(income,age,obligations,nights,careCosts=true){const r=rate(age,obligations);const base=income*r.rate/100;const careShare=careCosts?clamp(nights,0,30.4)/30.4:0;const amount=Math.max(0,base*(1-careShare));return{...r,base,careShare,amount,low:amount*.9,high:amount*1.1}}
function modelPair(a,b,age,nightsA,oblA,oblB){const ra=rate(age,oblA),rb=rate(age,oblB);const careA=clamp(nightsA,0,30.4)/30.4,careB=1-careA;const dutyA=a*ra.rate/100*(1-careA);const dutyB=b*rb.rate/100*(1-careB);return{ra,rb,careA,careB,dutyA,dutyB,net:dutyA-dutyB,amount:Math.abs(dutyA-dutyB)}}
function formatInput(el){if(!el)return;const v=parse(el.value);if(Number.isFinite(v))el.value=nf.format(Math.round(v))}
function mark(el,msg){const field=el?.closest('.sup82-field');const em=field?.querySelector('em');field?.classList.toggle('has-error',!!msg);if(em)em.textContent=msg||''}
let mode='basic';
function readBasic(){const income=parse($('basicIncome').value),age=parse($('basicAge').value),obl=parse($('basicObligations').value),nights=parse($('basicNights').value),care=$('basicCareCosts').checked;let ok=true;mark($('basicIncome'),income<1?'Zadejte kladný čistý příjem.':'');mark($('basicAge'),age<0||age>30?'Zadejte věk 0 až 30 let.':'');mark($('basicNights'),nights<0||nights>30.4?'Rozsah je 0 až 30,4 noci.':'');if(income<1||age<0||age>30||nights<0||nights>30.4)ok=false;return{ok,income,age,obl,nights,care}}
function readAdvanced(){const a=parse($('incomeA').value),b=parse($('incomeB').value),age=parse($('advancedAge').value),nights=parse($('nightsA').value),oa=parse($('obligationsA').value),ob=parse($('obligationsB').value);let ok=true;[['incomeA',a],['incomeB',b]].forEach(([id,v])=>{const m=v<1?'Zadejte kladný čistý příjem.':'';mark($(id),m);if(m)ok=false});mark($('advancedAge'),age<0||age>30?'Zadejte věk 0 až 30 let.':'');mark($('nightsA'),nights<0||nights>30.4?'Rozsah je 0 až 30,4 noci.':'');if(age<0||age>30||nights<0||nights>30.4)ok=false;return{ok,a,b,age,nights,oa,ob}}
function set(id,val){const el=$(id);if(el)el.textContent=val}
function renderBasic(v){const r=modelOne(v.income,v.age,v.obl,v.nights,v.care);set('resultKicker',`${r.label.toUpperCase()} · ${v.obl} ${v.obl===1?'POVINNOST':'POVINNOSTI'}`);set('resultTitle','Výživné po zohlednění péče');set('resultLabel','Orientační měsíční částka');set('resultAmount',money(r.amount));set('resultSentence',`Tabulkový základ ${money(r.base)} se ${v.care&&v.nights>0?`po zohlednění ${pf.format(v.nights)} nocí péče s běžnými náklady`:'bez korekce osobní péče'} orientačně dostává na tuto částku.`);set('rangeLow',money(r.low));set('rangeHigh',money(r.high));set('resultPercent',pct(r.rate));set('resultStage',r.label);set('resultBase',money(r.base));set('resultCare',pct(r.careShare*100));set('resultCareText',v.care?`${pf.format(v.nights)} nocí z 30,4 dne`:'péče není použita jako korekce');set('resultObligations',String(v.obl));set('heroIncome',money(v.income));set('heroStage',r.label);set('heroPercent',`${pct(r.rate)} tabulkově`);set('heroCare',`${pf.format(v.nights)} nocí / měsíc`);$('heroCareBar').style.width=`${Math.min(100,r.careShare*100)}%`;set('heroAmount',money(r.amount));set('heroRange',`pásmo kalkulačky ${money(r.low)}–${money(r.high)}`)}
function renderAdvanced(v){const r=modelPair(v.a,v.b,v.age,v.nights,v.oa,v.ob);const payer=r.net>=0?'Rodič A':'Rodič B',receiver=r.net>=0?'rodiči B':'rodiči A';const main=r.amount;set('resultKicker','OBA RODIČE · ČISTÝ ROZDÍL');set('resultTitle','Modelové peněžní dorovnání');set('resultLabel',`${payer} → ${receiver}`);set('resultAmount',money(main));set('resultSentence',`Modelová povinnost A po péči je ${money(r.dutyA)}, u rodiče B ${money(r.dutyB)}. Rozdíl ukazuje orientační směr peněžního dorovnání.`);set('rangeLow',money(main*.9));set('rangeHigh',money(main*1.1));set('resultPercent',`${pct(r.ra.rate)} / ${pct(r.rb.rate)}`);set('resultStage',r.ra.label);set('resultBase',`${money(r.dutyA)} / ${money(r.dutyB)}`);set('resultCare',`${pct(r.careA*100)} / ${pct(r.careB*100)}`);set('resultCareText','podíl péče A / B');set('resultObligations',`${v.oa} / ${v.ob}`);set('heroIncome',`${money(v.a)} / ${money(v.b)}`);set('heroStage',r.ra.label);set('heroPercent',`${pct(r.ra.rate)} / ${pct(r.rb.rate)}`);set('heroCare',`${pf.format(v.nights)} nocí u A`);$('heroCareBar').style.width=`${r.careA*100}%`;set('heroAmount',money(main));set('heroRange',`${payer} → ${receiver}`)}
function recalc(){if(mode==='basic'){const v=readBasic();if(v.ok)renderBasic(v)}else{const v=readAdvanced();if(v.ok)renderAdvanced(v)}}
function switchMode(next,focus=false){mode=next;const basic=next==='basic';$('sup82BasicPanel').hidden=!basic;$('sup82AdvancedPanel').hidden=basic;const tabs=[$('sup82BasicTab'),$('sup82AdvancedTab')];tabs.forEach((b,i)=>{const active=(i===0)===basic;b.classList.toggle('is-active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});set('modeHelp',basic?'Použijte dlouhodobý průměr čistého příjmu a reálný průměr péče, ne jeden výjimečný měsíc.':'Porovnáváme modelovou povinnost obou rodičů po zohlednění jejich příjmů, dalších dětí a podílu péče.');if(focus)(basic?$('sup82BasicTab'):$('sup82AdvancedTab')).focus();recalc()}
[$('sup82BasicTab'),$('sup82AdvancedTab')].forEach(btn=>btn.addEventListener('click',()=>switchMode(btn.dataset.mode)));const tablist=document.querySelector('.sup82-mode');tablist.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let target=mode;if(e.key==='ArrowLeft'||e.key==='Home')target='basic';if(e.key==='ArrowRight'||e.key==='End')target='advanced';switchMode(target,true)});
document.querySelectorAll('#supportForm input,#supportForm select').forEach(el=>{el.addEventListener('input',recalc);el.addEventListener('change',recalc);if(el.tagName==='INPUT'&&el.type==='text')el.addEventListener('blur',()=>formatInput(el))});$('supportForm').addEventListener('submit',e=>{e.preventDefault();recalc()});$('resetButton').addEventListener('click',()=>{if(mode==='basic'){ $('basicIncome').value='45 000';$('basicAge').value='8';$('basicObligations').value='1';$('basicNights').value='6';$('basicCareCosts').checked=true}else{$('incomeA').value='55 000';$('incomeB').value='38 000';$('advancedAge').value='8';$('nightsA').value='15.2';$('obligationsA').value='1';$('obligationsB').value='1'}recalc()});
const menu=document.querySelector('.sup82-menu'),mobile=document.querySelector('.sup82-mobile-nav');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));mobile.hidden=open});
recalc();
window.RVSupport82={rate,modelOne,modelPair};
})();
