(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const MS_DAY=86400000, NEW_RULES=new Date('2025-06-01T00:00:00');
function localDate(v){if(!v)return null;const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d,12,0,0)}
function iso(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:''}
function fmt(d){return d?new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'long',year:'numeric'}).format(d):'—'}
function fmtShort(d){return d?new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'numeric',year:'numeric'}).format(d):'—'}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function endFromMonths(start,months){const y=start.getFullYear(),m=start.getMonth()+months,day=start.getDate();const targetY=y+Math.floor(m/12),targetM=((m%12)+12)%12;const last=new Date(targetY,targetM+1,0,12).getDate();if(day>last)return new Date(targetY,targetM,last,12);const same=new Date(targetY,targetM,day,12);return addDays(same,-1)}
function inclusiveDays(a,b){return Math.floor((b-a)/MS_DAY)+1}
function minDate(a,b){if(!a)return b;if(!b)return a;return a<=b?a:b}
function workingExtension(end,count,weekdays){let d=new Date(end),left=Math.max(0,Math.floor(count||0)),guard=0;if(!left)return d;if(!weekdays.length)return d;while(left>0&&guard<3000){d=addDays(d,1);guard++;if(weekdays.includes(d.getDay()))left--}return d}
function rulesFor(agreementDate){return agreementDate&&agreementDate<NEW_RULES?{regular:3,leader:6,newRules:false}:{regular:4,leader:8,newRules:true}}
function calculate(state){const start=state.start;if(!start)return null;const rules=rulesFor(state.agreementDate||start),maxMonths=rules[state.role],statEnd=endFromMonths(start,maxMonths);let fixedHalfEnd=null,fixedDays=null;if(state.term==='fixed'&&state.fixedEnd&&state.fixedEnd>=start){const total=inclusiveDays(start,state.fixedEnd);fixedDays=Math.floor(total/2);fixedHalfEnd=addDays(start,Math.max(0,fixedDays-1))}
const legalCap=minDate(statEnd,fixedHalfEnd);const askedEnd=endFromMonths(start,state.months);const agreedLegal=minDate(askedEnd,legalCap);const missed=rules.newRules?state.missed:state.missed;const final=workingExtension(agreedLegal,missed,state.weekdays);return{rules,maxMonths,statEnd,fixedHalfEnd,fixedDays,legalCap,askedEnd,agreedLegal,final,overAsked:askedEnd>legalCap,termEndsFirst:state.term==='fixed'&&state.fixedEnd&&final>state.fixedEnd}}
function state(){const adv=document.body.dataset.mode==='advanced';const start=localDate($(adv?'#advancedStart':'#basicStart').value);const role=$(adv?'#advancedRole':'#basicRole').value;const term=$(adv?'#advancedTerm':'#basicTerm').value;const fixedEnd=term==='fixed'?localDate($(adv?'#advancedFixedEnd':'#basicFixedEnd').value):null;const months=Number($(adv?'#advancedMonths':'#basicMonths').value)||0;const agreementDate=adv?localDate($('#agreementDate').value)||start:start;const missed=adv?Number($('#missedShifts').value)||0:0;const weekdays=adv?$$('#weekdaySelector button.is-on').map(b=>Number(b.dataset.day)):[1,2,3,4,5];return{adv,start,role,term,fixedEnd,months,agreementDate,missed,weekdays}}
function render(){const s=state(),r=calculate(s);$('#basicFixedWrap').hidden=$('#basicTerm').value!=='fixed';$('#advancedFixedWrap').hidden=$('#advancedTerm').value!=='fixed';if(!r){$('#finalEnd').textContent='—';$('#resultMeaning').textContent='Zadejte datum nástupu.';return}
$('#finalEnd').textContent=fmt(r.termEndsFirst?s.fixedEnd:r.final);$('#agreedEnd').textContent=fmt(r.agreedLegal);$('#statutoryMax').textContent=`${r.maxMonths} ${r.maxMonths===1?'měsíc':'měsíců'}`;$('#statutoryNote').textContent=r.rules.newRules?'pravidla sjednaná od 1. 6. 2025':'starší režim před flexinovelou';$('#fixedLimit').textContent=r.fixedHalfEnd?fmt(r.fixedHalfEnd):'Nevztahuje se';$('#fixedNote').textContent=r.fixedHalfEnd?`polovina doby určité · ${r.fixedDays} kalendářních dnů`:'pracovní poměr na dobu neurčitou';$('#autoExtension').textContent=`${s.missed} ${s.missed===1?'směna':'směn'}`;$('#extensionNote').textContent=s.missed?`orientační posun na ${fmtShort(r.final)}`:'bez automatického prodloužení';$('#timelineStart').textContent=fmtShort(s.start);$('#timelineAgreed').textContent=fmtShort(r.agreedLegal);$('#timelineFinal').textContent=fmtShort(r.final);
let status='Běžný výpočet',cls='',meaning=`Při zadaných údajích vychází poslední den zkušební doby na ${fmt(r.final)}.`;let warn='Výsledek je orientační. U nepravidelných směn, neobvyklého sjednání nebo sporu o platnost ujednání ověřte konkrétní situaci s HR nebo právníkem.';
if(!r.rules.newRules){status='Starší pravidla';cls='is-warning';meaning=`Datum sjednání spadá před 1. 6. 2025. Obecné maximum je ${r.maxMonths} měsíců a smluvní prodlužování podle flexinovely se neuplatní.`}
if(r.overAsked){status='Délka nad limitem';cls='is-risk';meaning=`Zadaná sjednaná délka přesahuje použitelný zákonný limit. Kalkulačka proto pracuje s nejzazším přípustným datem ${fmt(r.legalCap)}.`}
if(r.termEndsFirst){status='Pracovní poměr končí dřív';cls='is-warning';meaning=`Automatické prodloužení by vycházelo až na ${fmt(r.final)}, ale pracovní poměr na dobu určitou končí už ${fmt(s.fixedEnd)}.`}
$('#resultStatus').className='trial-status '+cls;$('#resultStatus').textContent=status;$('#resultMeaning').textContent=meaning;$('#resultWarning').querySelector('p').textContent=warn;$('#resultLabel').textContent=r.termEndsFirst?'Dřívější konec pracovního poměru':'Orientační konec';}
function syncBasicToAdvanced(){['Start','Role','Months','Term','FixedEnd'].forEach(k=>{const a=$('#basic'+k),b=$('#advanced'+k);if(a&&b)b.value=a.value});if(!$('#agreementDate').value)$('#agreementDate').value=$('#advancedStart').value}
function mode(next){document.body.dataset.mode=next;const adv=next==='advanced';$('#basicModeTab').classList.toggle('is-active',!adv);$('#advancedModeTab').classList.toggle('is-active',adv);$('#basicModeTab').setAttribute('aria-selected',String(!adv));$('#advancedModeTab').setAttribute('aria-selected',String(adv));$('#basicMode').hidden=adv;$('#advancedMode').hidden=!adv;$('#basicMode').classList.toggle('is-active',!adv);$('#advancedMode').classList.toggle('is-active',adv);if(adv)syncBasicToAdvanced();render()}
function initDates(){const today=new Date();const v=iso(today);$('#basicStart').value=v;$('#advancedStart').value=v;$('#agreementDate').value=v;const fixed=endFromMonths(today,12);$('#basicFixedEnd').value=iso(fixed);$('#advancedFixedEnd').value=iso(fixed)}
$('#basicModeTab').addEventListener('click',()=>mode('basic'));$('#advancedModeTab').addEventListener('click',()=>mode('advanced'));$$('#trialForm input,#trialForm select').forEach(el=>el.addEventListener('input',render));$$('#weekdaySelector button').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('is-on');render()}));$('#resetBtn').addEventListener('click',()=>{initDates();$('#basicRole').value=$('#advancedRole').value='regular';$('#basicMonths').value=$('#advancedMonths').value='3';$('#basicTerm').value=$('#advancedTerm').value='indefinite';$('#missedShifts').value='0';$$('#weekdaySelector button').forEach(b=>b.classList.toggle('is-on',[1,2,3,4,5].includes(Number(b.dataset.day))));mode('basic')});const mt=$('#menuToggle');if(mt)mt.addEventListener('click',()=>{const nav=$('#mainNav'),open=!nav.classList.contains('is-open');nav.classList.toggle('is-open',open);mt.setAttribute('aria-expanded',String(open))});initDates();mode('basic');})();